/*
Copyright 2013, KISSY UI Library v1.40dev
MIT Licensed
build time: Jul 3 19:20
*/
KISSY.add("event/dom/base/utils",function(f,d){var a="ksEventTargetId_"+f.now(),b=f.Env.host.document;return{simpleAdd:b&&b.addEventListener?function(a,b,d,f){a.addEventListener&&a.addEventListener(b,d,!!f)}:function(a,b,d){a.attachEvent&&a.attachEvent("on"+b,d)},simpleRemove:b&&b.removeEventListener?function(a,b,d,f){a.removeEventListener&&a.removeEventListener(b,d,!!f)}:function(a,b,d){a.detachEvent&&a.detachEvent("on"+b,d)},data:function(b,f){return d.data(b,a,f)},removeData:function(b){return d.removeData(b,
a)}}},{requires:["dom"]});KISSY.add("event/dom/base/special",function(){return{}});
KISSY.add("event/dom/base/observer",function(f,d,a){function b(a){b.superclass.constructor.apply(this,arguments)}f.extend(b,a.Observer,{keys:"fn,filter,data,context,originalType,groups,last".split(","),notifyInternal:function(a,b){var f,j,p=a.type,l;(l=this.originalType)?a.type=l:l=p;(f=d[l])&&f.handle?(f=f.handle(a,this,b))&&0<f.length&&(j=f[0]):j=this.simpleNotify(a,b);a.type=p;return j}});return b},{requires:["./special","event/base"]});
KISSY.add("event/dom/base/object",function(f,d,a){function b(){return j}function q(){return p}function m(c){var k=c.type;m.superclass.constructor.call(this);this.originalEvent=c;this.isDefaultPrevented=c.defaultPrevented||c.returnValue===p||c.getPreventDefault&&c.getPreventDefault()?b:q;var h=null,g,n,i=l.concat();f.each(o,function(c){return k.match(c.reg)?(i=i.concat(c.props),h=c.fix,!1):a});for(g=i.length;g;)n=i[--g],this[n]=c[n];this.target||(this.target=c.srcElement||t);3===this.target.nodeType&&
(this.target=this.target.parentNode);h&&h(this,c)}var t=f.Env.host.document,j=!0,p=!1,l="altKey,bubbles,cancelable,ctrlKey,currentTarget,eventPhase,metaKey,shiftKey,target,timeStamp,view,type".split(","),o=[{reg:/^key/,props:["char","charCode","key","keyCode","which"],fix:function(c,k){null==c.which&&(c.which=null!=k.charCode?k.charCode:k.keyCode);c.metaKey===a&&(c.metaKey=c.ctrlKey)}},{reg:/^touch/,props:["touches","changedTouches","targetTouches"]},{reg:/^gesturechange$/i,props:["rotation","scale"]},
{reg:/^mousewheel$/,props:[],fix:function(c,k){var h,g,l,i=k.wheelDelta,b=k.axis,o=k.wheelDeltaY,f=k.wheelDeltaX,d=k.detail;i&&(l=i/120);d&&(l=-(0==d%3?d/3:d));b!==a&&(b===e.HORIZONTAL_AXIS?(g=0,h=-1*l):b===e.VERTICAL_AXIS&&(h=0,g=l));o!==a&&(g=o/120);f!==a&&(h=-1*f/120);!h&&!g&&(g=l);h!==a&&(c.deltaX=h);g!==a&&(c.deltaY=g);l!==a&&(c.delta=l)}},{reg:/^mouse|contextmenu|click|mspointer/i,props:"buttons,clientX,clientY,button,offsetX,relatedTarget,which,fromElement,toElement,offsetY,pageX,pageY,screenX,screenY".split(","),
fix:function(c,l){var h,g,b=c.target,i=l.button;null==c.pageX&&null!=l.clientX&&(h=b.ownerDocument||t,g=h.documentElement,h=h.body,c.pageX=l.clientX+(g&&g.scrollLeft||h&&h.scrollLeft||0)-(g&&g.clientLeft||h&&h.clientLeft||0),c.pageY=l.clientY+(g&&g.scrollTop||h&&h.scrollTop||0)-(g&&g.clientTop||h&&h.clientTop||0));!c.which&&i!==a&&(c.which=i&1?1:i&2?3:i&4?2:0);!c.relatedTarget&&c.fromElement&&(c.relatedTarget=c.fromElement===b?c.toElement:c.fromElement);return c}}];f.extend(m,d.Object,{constructor:m,
preventDefault:function(){var a=this.originalEvent;a.preventDefault?a.preventDefault():a.returnValue=p;m.superclass.preventDefault.call(this)},stopPropagation:function(){var a=this.originalEvent;a.stopPropagation?a.stopPropagation():a.cancelBubble=j;m.superclass.stopPropagation.call(this)}});return m},{requires:["event/base"]});
KISSY.add("event/dom/base/observable",function(f,d,a,b,q,m,t){function j(a){f.mix(this,a);this.reset()}var p=t.Utils;f.extend(j,t.Observable,{setup:function(){var l=this.type,o=a[l]||{},c=this.currentTarget,k=b.data(c).handle;(!o.setup||!1===o.setup.call(c,l))&&b.simpleAdd(c,l,k)},constructor:j,reset:function(){j.superclass.reset.call(this);this.lastCount=this.delegateCount=0},notify:function(a){var b=a.target,c=a.type,k=this.currentTarget,h=this.observers,g=[],n,i,f=this.delegateCount||0,s,u;if(f&&
b.nodeType)for(;b!=k;){if(!0!==b.disabled||"click"!==c){var r={},m,j,q;s=[];for(i=0;i<f;i++)u=h[i],q=u.filter,j=q+"",m=r[j],void 0===m&&(m=r[j]=d.test(b,q)),m&&s.push(u);s.length&&g.push({currentTarget:b,currentTargetObservers:s})}b=b.parentNode||k}f<h.length&&g.push({currentTarget:k,currentTargetObservers:h.slice(f)});i=0;for(b=g.length;!a.isPropagationStopped()&&i<b;++i){c=g[i];s=c.currentTargetObservers;c=c.currentTarget;a.currentTarget=c;for(c=0;!a.isImmediatePropagationStopped()&&c<s.length;c++)k=
s[c],k=k.notify(a,this),!1!==n&&(n=k)}return n},fire:function(b,o){var b=b||{},c=""+this.type,k,h,g=a[c]||{};k=!1!==g.bubbles;var n=this.currentTarget;if(!(g.fire&&!1===g.fire.call(n,o))&&(b instanceof m||(h=b,b=new m({currentTarget:n,type:c,target:n}),f.mix(b,h)),!(g.preFire&&!1===g.preFire.call(n,b,o)))){var i=n,v=d.getWindow(i),s=v.document;h=[];g=0;do h.push(i),i=i.parentNode||i.ownerDocument||i===s&&v;while(!o&&i&&k);i=h[g];do b.currentTarget=i,(k=j.getDomEventObservable(i,c))&&k.notify(b),i=
h[++g];while(!o&&i&&!b.isPropagationStopped());if(!o&&!b.isDefaultPrevented()){try{n[c]&&!f.isWindow(n)&&(j.triggeredEvent=c,n[c]())}catch(u){}j.triggeredEvent=""}}},on:function(b){var f=this.observers,c=a[this.type]||{},b=b instanceof q?b:new q(b);-1==this.findObserver(b)&&(b.filter?(f.splice(this.delegateCount,0,b),this.delegateCount++):b.last?(f.push(b),this.lastCount++):f.splice(f.length-this.lastCount,0,b),c.add&&c.add.call(this.currentTarget,b))},detach:function(b){var f,c=a[this.type]||{},
k="filter"in b,h=b.filter,g=b.context,n=b.fn,i=this.currentTarget,d=this.observers,b=b.groups;if(d.length){b&&(f=p.getGroupsRe(b));var s,u,r,m,j=d.length;if(n||k||f){g=g||i;s=b=0;for(u=[];b<j;++b)r=d[b],m=r.context||i,g!=m||n&&n!=r.fn||k&&(h&&h!=r.filter||!h&&!r.filter)||f&&!r.groups.match(f)?u[s++]=r:(r.filter&&this.delegateCount&&this.delegateCount--,r.last&&this.lastCount&&this.lastCount--,c.remove&&c.remove.call(i,r));this.observers=u}else this.reset();this.checkMemory()}},checkMemory:function(){var d=
this.type,m,c,k=a[d]||{},h=this.currentTarget,g=b.data(h);if(g&&(m=g.observables,this.hasObserver()||(c=g.handle,(!k.tearDown||!1===k.tearDown.call(h,d))&&b.simpleRemove(h,d,c),delete m[d]),f.isEmptyObject(m)))g.handle=null,b.removeData(h)}});j.triggeredEvent="";j.getDomEventObservable=function(a,f){var c=b.data(a),k;c&&(k=c.observables);return k?k[f]:null};j.getDomEventObservablesHolder=function(a,f){var c=b.data(a);!c&&f&&b.data(a,c={});return c};return j},{requires:"dom,./special,./utils,./observer,./object,event/base".split(",")});
KISSY.add("event/dom/base/dom-event",function(f,d,a,b,q,m,t){function j(a,b){var c=q[b]||{},f;if(!a.originalType&&(f=c.typeFix))a.originalType=b,b=f;return b}function p(a,b,c){var d,i,v,c=f.merge(c),b=j(c,b);d=m.getDomEventObservablesHolder(a,1);if(!(v=d.handle))v=d.handle=function(a){var b=a.type,c=v.currentTarget;if(!(m.triggeredEvent==b||"undefined"==typeof KISSY))if(b=m.getDomEventObservable(c,b))return a.currentTarget=c,a=new t(a),b.notify(a)},v.currentTarget=a;if(!(i=d.observables))i=d.observables=
{};d=i[b];d||(d=i[b]=new m({type:b,currentTarget:a}),d.setup());d.on(c);a=null}function l(a,b,c){var c=f.merge(c),b=j(c,b),a=m.getDomEventObservablesHolder(a),d=(a||{}).observables;if(a&&d)if(b)(b=d[b])&&b.detach(c);else for(b in d)d[b].detach(c)}var o=d.Utils,c={};f.mix(c,{on:function(a,c,g,d){a=b.query(a);o.batchForType(function(a,b,c,d){for(var c=o.normalizeParam(b,c,d),g,b=c.type,d=a.length-1;0<=d;d--)g=a[d],p(g,b,c)},1,a,c,g,d);return a},detach:function(a,c,d,f){a=b.query(a);o.batchForType(function(a,
b,c,d){for(var c=o.normalizeParam(b,c,d),g,f,b=c.type,d=a.length-1;0<=d;d--)if(g=a[d],l(g,b,c),c.deep&&g.getElementsByTagName){f=g.getElementsByTagName("*");for(g=f.length-1;0<=g;g--)l(f[g],b,c)}},1,a,c,d,f);return a},delegate:function(a,b,d,f,i){return c.on(a,b,{fn:f,context:i,filter:d})},undelegate:function(a,b,d,f,i){return c.detach(a,b,{fn:f,context:i,filter:d})},fire:function(a,c,d,f){var i=void 0,d=d||{};d.synthetic=1;o.splitAndRun(c,function(c){var h,j,l;o.fillGroupsForEvent(c,d);c=d.type;
if((j=q[c])&&j.typeFix)c=j.typeFix;a=b.query(a);for(j=a.length-1;0<=j;j--)h=a[j],l=m.getDomEventObservable(h,c),!f&&!l&&(l=new m({type:c,currentTarget:h})),l&&(h=l.fire(d,f),!1!==i&&(i=h))});return i},fireHandler:function(a,b,d){return c.fire(a,b,d,1)},clone:function(b,c){var d;if(d=m.getDomEventObservablesHolder(b)){var j=a.data(b);j&&j===a.data(c)&&a.removeData(c);f.each(d.observables,function(a,b){f.each(a.observers,function(a){p(c,b,a)})})}}});return c},{requires:"event/base,./utils,dom,./special,./observable,./object".split(",")});
KISSY.add("event/dom/base/key-codes",function(f){var d=f.UA,a={MAC_ENTER:3,BACKSPACE:8,TAB:9,NUM_CENTER:12,ENTER:13,SHIFT:16,CTRL:17,ALT:18,PAUSE:19,CAPS_LOCK:20,ESC:27,SPACE:32,PAGE_UP:33,PAGE_DOWN:34,END:35,HOME:36,LEFT:37,UP:38,RIGHT:39,DOWN:40,PRINT_SCREEN:44,INSERT:45,DELETE:46,ZERO:48,ONE:49,TWO:50,THREE:51,FOUR:52,FIVE:53,SIX:54,SEVEN:55,EIGHT:56,NINE:57,QUESTION_MARK:63,A:65,B:66,C:67,D:68,E:69,F:70,G:71,H:72,I:73,J:74,K:75,L:76,M:77,N:78,O:79,P:80,Q:81,R:82,S:83,T:84,U:85,V:86,W:87,X:88,
Y:89,Z:90,META:91,WIN_KEY_RIGHT:92,CONTEXT_MENU:93,NUM_ZERO:96,NUM_ONE:97,NUM_TWO:98,NUM_THREE:99,NUM_FOUR:100,NUM_FIVE:101,NUM_SIX:102,NUM_SEVEN:103,NUM_EIGHT:104,NUM_NINE:105,NUM_MULTIPLY:106,NUM_PLUS:107,NUM_MINUS:109,NUM_PERIOD:110,NUM_DIVISION:111,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,NUMLOCK:144,SEMICOLON:186,DASH:189,EQUALS:187,COMMA:188,PERIOD:190,SLASH:191,APOSTROPHE:192,SINGLE_QUOTE:222,OPEN_SQUARE_BRACKET:219,BACKSLASH:220,CLOSE_SQUARE_BRACKET:221,
WIN_KEY:224,MAC_FF_META:224,WIN_IME:229,isTextModifyingKeyEvent:function(b){if(b.altKey&&!b.ctrlKey||b.metaKey||b.keyCode>=a.F1&&b.keyCode<=a.F12)return!1;switch(b.keyCode){case a.ALT:case a.CAPS_LOCK:case a.CONTEXT_MENU:case a.CTRL:case a.DOWN:case a.END:case a.ESC:case a.HOME:case a.INSERT:case a.LEFT:case a.MAC_FF_META:case a.META:case a.NUMLOCK:case a.NUM_CENTER:case a.PAGE_DOWN:case a.PAGE_UP:case a.PAUSE:case a.PRINT_SCREEN:case a.RIGHT:case a.SHIFT:case a.UP:case a.WIN_KEY:case a.WIN_KEY_RIGHT:return!1;
default:return!0}},isCharacterKey:function(b){if(b>=a.ZERO&&b<=a.NINE||b>=a.NUM_ZERO&&b<=a.NUM_MULTIPLY||b>=a.A&&b<=a.Z||d.webkit&&0==b)return!0;switch(b){case a.SPACE:case a.QUESTION_MARK:case a.NUM_PLUS:case a.NUM_MINUS:case a.NUM_PERIOD:case a.NUM_DIVISION:case a.SEMICOLON:case a.DASH:case a.EQUALS:case a.COMMA:case a.PERIOD:case a.SLASH:case a.APOSTROPHE:case a.SINGLE_QUOTE:case a.OPEN_SQUARE_BRACKET:case a.BACKSLASH:case a.CLOSE_SQUARE_BRACKET:return!0;default:return!1}}};return a});
KISSY.add("event/dom/base/gesture",function(){return{start:"mousedown",move:"mousemove",end:"mouseup",tap:"click",doubleTap:"dblclick"}});
KISSY.add("event/dom/base/special-events",function(f,d,a){var b=b;return f.mix(a,{mousewheel:{typeFix:f.UA.gecko?"DOMMouseScroll":"mousewheel"},load:{bubbles:!1},click:{fire:function(a){return!a&&"checkbox"===""+this.type&&this.click&&"input"==this.nodeName.toLowerCase()?(this.click(),!1):b}},focus:{bubbles:!1,preFire:function(a,b){b||d.fire(this,"focusin")},fire:function(a){return!a&&this.ownerDocument&&this!==this.ownerDocument.activeElement&&this.focus?(this.focus(),!1):b}},blur:{bubbles:!1,preFire:function(a,
b){b||d.fire(this,"focusout")},fire:function(a){return!a&&this.ownerDocument&&this===this.ownerDocument.activeElement&&this.blur?(this.blur(),!1):b}}})},{requires:["./dom-event","./special"]});
KISSY.add("event/dom/base/mouseenter",function(f,d,a){f.each([{name:"mouseenter",fix:"mouseover"},{name:"mouseleave",fix:"mouseout"}],function(b){a[b.name]={typeFix:b.fix,handle:function(a,b,f){var j=a.currentTarget,p=a.relatedTarget;if(!p||p!==j&&!d.contains(j,p))return[b.simpleNotify(a,f)]}}})},{requires:["dom","./special"]});
KISSY.add("event/dom/base/valuechange",function(f,d,a,b){function q(b){if(a.hasData(b,g)){var c=a.data(b,g);clearTimeout(c);a.removeData(b,g)}}function m(a){q(a.target)}function t(b){var f=b.value,g=a.data(b,h);f!==g&&(d.fireHandler(b,c,{prevVal:g,newVal:f}),a.data(b,h,f))}function j(b){a.hasData(b,g)||a.data(b,g,setTimeout(function(){t(b);a.data(b,g,setTimeout(arguments.callee,n))},n))}function p(b){var c=b.target;"focus"==b.type&&a.data(c,h,c.value);j(c)}function l(a){t(a.target)}function o(b){a.removeData(b,
h);q(b);d.detach(b,"blur",m);d.detach(b,"webkitspeechchange",l);d.detach(b,"mousedown keyup keydown focus",p)}var c="valuechange",k=a.nodeName,h="event/valuechange/history",g="event/valuechange/poll",n=50;b[c]={setup:function(){var a=k(this);if("input"==a||"textarea"==a)o(this),d.on(this,"blur",m),d.on(this,"webkitspeechchange",l),d.on(this,"mousedown keyup keydown focus",p)},tearDown:function(){o(this)}};return d},{requires:["./dom-event","dom","./special"]});
KISSY.add("event/dom/base",function(f,d,a,b,q){return f.merge({add:d.on,remove:d.detach,KeyCode:a,Gesture:b,Special:q},d)},{requires:"./base/dom-event,./base/key-codes,./base/gesture,./base/special-events,./base/mouseenter,./base/valuechange".split(",")});
/*
Copyright 2013, KISSY UI Library v1.40dev
MIT Licensed
build time: Jul 3 19:20
*/
KISSY.add("event/dom/focusin",function(d,e){var g=e.Special;d.each([{name:"focusin",fix:"focus"},{name:"focusout",fix:"blur"}],function(c){function f(a){return e.fire(a.target,c.name)}var b=d.guid("attaches_"+d.now()+"_");g[c.name]={setup:function(){var a=this.ownerDocument||this;b in a||(a[b]=0);a[b]+=1;1===a[b]&&a.addEventListener(c.fix,f,!0)},tearDown:function(){var a=this.ownerDocument||this;a[b]-=1;0===a[b]&&a.removeEventListener(c.fix,f,!0)}}});return e},{requires:["event/dom/base"]});
/*
Copyright 2013, KISSY UI Library v1.40dev
MIT Licensed
build time: Jul 3 19:20
*/
KISSY.add("event/dom/base/utils",function(f,d){var a="ksEventTargetId_"+f.now(),b=f.Env.host.document;return{simpleAdd:b&&b.addEventListener?function(a,b,d,f){a.addEventListener&&a.addEventListener(b,d,!!f)}:function(a,b,d){a.attachEvent&&a.attachEvent("on"+b,d)},simpleRemove:b&&b.removeEventListener?function(a,b,d,f){a.removeEventListener&&a.removeEventListener(b,d,!!f)}:function(a,b,d){a.detachEvent&&a.detachEvent("on"+b,d)},data:function(b,f){return d.data(b,a,f)},removeData:function(b){return d.removeData(b,
a)}}},{requires:["dom"]});KISSY.add("event/dom/base/special",function(){return{}});
KISSY.add("event/dom/base/observer",function(f,d,a){function b(a){b.superclass.constructor.apply(this,arguments)}f.extend(b,a.Observer,{keys:"fn,filter,data,context,originalType,groups,last".split(","),notifyInternal:function(a,b){var f,j,p=a.type,l;(l=this.originalType)?a.type=l:l=p;(f=d[l])&&f.handle?(f=f.handle(a,this,b))&&0<f.length&&(j=f[0]):j=this.simpleNotify(a,b);a.type=p;return j}});return b},{requires:["./special","event/base"]});
KISSY.add("event/dom/base/object",function(f,d,a){function b(){return j}function q(){return p}function m(c){var k=c.type;m.superclass.constructor.call(this);this.originalEvent=c;this.isDefaultPrevented=c.defaultPrevented||c.returnValue===p||c.getPreventDefault&&c.getPreventDefault()?b:q;var h=null,g,n,i=l.concat();f.each(o,function(c){return k.match(c.reg)?(i=i.concat(c.props),h=c.fix,!1):a});for(g=i.length;g;)n=i[--g],this[n]=c[n];this.target||(this.target=c.srcElement||t);3===this.target.nodeType&&
(this.target=this.target.parentNode);h&&h(this,c)}var t=f.Env.host.document,j=!0,p=!1,l="altKey,bubbles,cancelable,ctrlKey,currentTarget,eventPhase,metaKey,shiftKey,target,timeStamp,view,type".split(","),o=[{reg:/^key/,props:["char","charCode","key","keyCode","which"],fix:function(c,k){null==c.which&&(c.which=null!=k.charCode?k.charCode:k.keyCode);c.metaKey===a&&(c.metaKey=c.ctrlKey)}},{reg:/^touch/,props:["touches","changedTouches","targetTouches"]},{reg:/^gesturechange$/i,props:["rotation","scale"]},
{reg:/^mousewheel$/,props:[],fix:function(c,k){var h,g,l,i=k.wheelDelta,b=k.axis,o=k.wheelDeltaY,f=k.wheelDeltaX,d=k.detail;i&&(l=i/120);d&&(l=-(0==d%3?d/3:d));b!==a&&(b===e.HORIZONTAL_AXIS?(g=0,h=-1*l):b===e.VERTICAL_AXIS&&(h=0,g=l));o!==a&&(g=o/120);f!==a&&(h=-1*f/120);!h&&!g&&(g=l);h!==a&&(c.deltaX=h);g!==a&&(c.deltaY=g);l!==a&&(c.delta=l)}},{reg:/^mouse|contextmenu|click|mspointer/i,props:"buttons,clientX,clientY,button,offsetX,relatedTarget,which,fromElement,toElement,offsetY,pageX,pageY,screenX,screenY".split(","),
fix:function(c,l){var h,g,b=c.target,i=l.button;null==c.pageX&&null!=l.clientX&&(h=b.ownerDocument||t,g=h.documentElement,h=h.body,c.pageX=l.clientX+(g&&g.scrollLeft||h&&h.scrollLeft||0)-(g&&g.clientLeft||h&&h.clientLeft||0),c.pageY=l.clientY+(g&&g.scrollTop||h&&h.scrollTop||0)-(g&&g.clientTop||h&&h.clientTop||0));!c.which&&i!==a&&(c.which=i&1?1:i&2?3:i&4?2:0);!c.relatedTarget&&c.fromElement&&(c.relatedTarget=c.fromElement===b?c.toElement:c.fromElement);return c}}];f.extend(m,d.Object,{constructor:m,
preventDefault:function(){var a=this.originalEvent;a.preventDefault?a.preventDefault():a.returnValue=p;m.superclass.preventDefault.call(this)},stopPropagation:function(){var a=this.originalEvent;a.stopPropagation?a.stopPropagation():a.cancelBubble=j;m.superclass.stopPropagation.call(this)}});return m},{requires:["event/base"]});
KISSY.add("event/dom/base/observable",function(f,d,a,b,q,m,t){function j(a){f.mix(this,a);this.reset()}var p=t.Utils;f.extend(j,t.Observable,{setup:function(){var l=this.type,o=a[l]||{},c=this.currentTarget,k=b.data(c).handle;(!o.setup||!1===o.setup.call(c,l))&&b.simpleAdd(c,l,k)},constructor:j,reset:function(){j.superclass.reset.call(this);this.lastCount=this.delegateCount=0},notify:function(a){var b=a.target,c=a.type,k=this.currentTarget,h=this.observers,g=[],n,i,f=this.delegateCount||0,s,u;if(f&&
b.nodeType)for(;b!=k;){if(!0!==b.disabled||"click"!==c){var r={},m,j,q;s=[];for(i=0;i<f;i++)u=h[i],q=u.filter,j=q+"",m=r[j],void 0===m&&(m=r[j]=d.test(b,q)),m&&s.push(u);s.length&&g.push({currentTarget:b,currentTargetObservers:s})}b=b.parentNode||k}f<h.length&&g.push({currentTarget:k,currentTargetObservers:h.slice(f)});i=0;for(b=g.length;!a.isPropagationStopped()&&i<b;++i){c=g[i];s=c.currentTargetObservers;c=c.currentTarget;a.currentTarget=c;for(c=0;!a.isImmediatePropagationStopped()&&c<s.length;c++)k=
s[c],k=k.notify(a,this),!1!==n&&(n=k)}return n},fire:function(b,o){var b=b||{},c=""+this.type,k,h,g=a[c]||{};k=!1!==g.bubbles;var n=this.currentTarget;if(!(g.fire&&!1===g.fire.call(n,o))&&(b instanceof m||(h=b,b=new m({currentTarget:n,type:c,target:n}),f.mix(b,h)),!(g.preFire&&!1===g.preFire.call(n,b,o)))){var i=n,v=d.getWindow(i),s=v.document;h=[];g=0;do h.push(i),i=i.parentNode||i.ownerDocument||i===s&&v;while(!o&&i&&k);i=h[g];do b.currentTarget=i,(k=j.getDomEventObservable(i,c))&&k.notify(b),i=
h[++g];while(!o&&i&&!b.isPropagationStopped());if(!o&&!b.isDefaultPrevented()){try{n[c]&&!f.isWindow(n)&&(j.triggeredEvent=c,n[c]())}catch(u){}j.triggeredEvent=""}}},on:function(b){var f=this.observers,c=a[this.type]||{},b=b instanceof q?b:new q(b);-1==this.findObserver(b)&&(b.filter?(f.splice(this.delegateCount,0,b),this.delegateCount++):b.last?(f.push(b),this.lastCount++):f.splice(f.length-this.lastCount,0,b),c.add&&c.add.call(this.currentTarget,b))},detach:function(b){var f,c=a[this.type]||{},
k="filter"in b,h=b.filter,g=b.context,n=b.fn,i=this.currentTarget,d=this.observers,b=b.groups;if(d.length){b&&(f=p.getGroupsRe(b));var s,u,r,m,j=d.length;if(n||k||f){g=g||i;s=b=0;for(u=[];b<j;++b)r=d[b],m=r.context||i,g!=m||n&&n!=r.fn||k&&(h&&h!=r.filter||!h&&!r.filter)||f&&!r.groups.match(f)?u[s++]=r:(r.filter&&this.delegateCount&&this.delegateCount--,r.last&&this.lastCount&&this.lastCount--,c.remove&&c.remove.call(i,r));this.observers=u}else this.reset();this.checkMemory()}},checkMemory:function(){var d=
this.type,m,c,k=a[d]||{},h=this.currentTarget,g=b.data(h);if(g&&(m=g.observables,this.hasObserver()||(c=g.handle,(!k.tearDown||!1===k.tearDown.call(h,d))&&b.simpleRemove(h,d,c),delete m[d]),f.isEmptyObject(m)))g.handle=null,b.removeData(h)}});j.triggeredEvent="";j.getDomEventObservable=function(a,f){var c=b.data(a),k;c&&(k=c.observables);return k?k[f]:null};j.getDomEventObservablesHolder=function(a,f){var c=b.data(a);!c&&f&&b.data(a,c={});return c};return j},{requires:"dom,./special,./utils,./observer,./object,event/base".split(",")});
KISSY.add("event/dom/base/dom-event",function(f,d,a,b,q,m,t){function j(a,b){var c=q[b]||{},f;if(!a.originalType&&(f=c.typeFix))a.originalType=b,b=f;return b}function p(a,b,c){var d,i,v,c=f.merge(c),b=j(c,b);d=m.getDomEventObservablesHolder(a,1);if(!(v=d.handle))v=d.handle=function(a){var b=a.type,c=v.currentTarget;if(!(m.triggeredEvent==b||"undefined"==typeof KISSY))if(b=m.getDomEventObservable(c,b))return a.currentTarget=c,a=new t(a),b.notify(a)},v.currentTarget=a;if(!(i=d.observables))i=d.observables=
{};d=i[b];d||(d=i[b]=new m({type:b,currentTarget:a}),d.setup());d.on(c);a=null}function l(a,b,c){var c=f.merge(c),b=j(c,b),a=m.getDomEventObservablesHolder(a),d=(a||{}).observables;if(a&&d)if(b)(b=d[b])&&b.detach(c);else for(b in d)d[b].detach(c)}var o=d.Utils,c={};f.mix(c,{on:function(a,c,g,d){a=b.query(a);o.batchForType(function(a,b,c,d){for(var c=o.normalizeParam(b,c,d),g,b=c.type,d=a.length-1;0<=d;d--)g=a[d],p(g,b,c)},1,a,c,g,d);return a},detach:function(a,c,d,f){a=b.query(a);o.batchForType(function(a,
b,c,d){for(var c=o.normalizeParam(b,c,d),g,f,b=c.type,d=a.length-1;0<=d;d--)if(g=a[d],l(g,b,c),c.deep&&g.getElementsByTagName){f=g.getElementsByTagName("*");for(g=f.length-1;0<=g;g--)l(f[g],b,c)}},1,a,c,d,f);return a},delegate:function(a,b,d,f,i){return c.on(a,b,{fn:f,context:i,filter:d})},undelegate:function(a,b,d,f,i){return c.detach(a,b,{fn:f,context:i,filter:d})},fire:function(a,c,d,f){var i=void 0,d=d||{};d.synthetic=1;o.splitAndRun(c,function(c){var h,j,l;o.fillGroupsForEvent(c,d);c=d.type;
if((j=q[c])&&j.typeFix)c=j.typeFix;a=b.query(a);for(j=a.length-1;0<=j;j--)h=a[j],l=m.getDomEventObservable(h,c),!f&&!l&&(l=new m({type:c,currentTarget:h})),l&&(h=l.fire(d,f),!1!==i&&(i=h))});return i},fireHandler:function(a,b,d){return c.fire(a,b,d,1)},clone:function(b,c){var d;if(d=m.getDomEventObservablesHolder(b)){var j=a.data(b);j&&j===a.data(c)&&a.removeData(c);f.each(d.observables,function(a,b){f.each(a.observers,function(a){p(c,b,a)})})}}});return c},{requires:"event/base,./utils,dom,./special,./observable,./object".split(",")});
KISSY.add("event/dom/base/key-codes",function(f){var d=f.UA,a={MAC_ENTER:3,BACKSPACE:8,TAB:9,NUM_CENTER:12,ENTER:13,SHIFT:16,CTRL:17,ALT:18,PAUSE:19,CAPS_LOCK:20,ESC:27,SPACE:32,PAGE_UP:33,PAGE_DOWN:34,END:35,HOME:36,LEFT:37,UP:38,RIGHT:39,DOWN:40,PRINT_SCREEN:44,INSERT:45,DELETE:46,ZERO:48,ONE:49,TWO:50,THREE:51,FOUR:52,FIVE:53,SIX:54,SEVEN:55,EIGHT:56,NINE:57,QUESTION_MARK:63,A:65,B:66,C:67,D:68,E:69,F:70,G:71,H:72,I:73,J:74,K:75,L:76,M:77,N:78,O:79,P:80,Q:81,R:82,S:83,T:84,U:85,V:86,W:87,X:88,
Y:89,Z:90,META:91,WIN_KEY_RIGHT:92,CONTEXT_MENU:93,NUM_ZERO:96,NUM_ONE:97,NUM_TWO:98,NUM_THREE:99,NUM_FOUR:100,NUM_FIVE:101,NUM_SIX:102,NUM_SEVEN:103,NUM_EIGHT:104,NUM_NINE:105,NUM_MULTIPLY:106,NUM_PLUS:107,NUM_MINUS:109,NUM_PERIOD:110,NUM_DIVISION:111,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,NUMLOCK:144,SEMICOLON:186,DASH:189,EQUALS:187,COMMA:188,PERIOD:190,SLASH:191,APOSTROPHE:192,SINGLE_QUOTE:222,OPEN_SQUARE_BRACKET:219,BACKSLASH:220,CLOSE_SQUARE_BRACKET:221,
WIN_KEY:224,MAC_FF_META:224,WIN_IME:229,isTextModifyingKeyEvent:function(b){if(b.altKey&&!b.ctrlKey||b.metaKey||b.keyCode>=a.F1&&b.keyCode<=a.F12)return!1;switch(b.keyCode){case a.ALT:case a.CAPS_LOCK:case a.CONTEXT_MENU:case a.CTRL:case a.DOWN:case a.END:case a.ESC:case a.HOME:case a.INSERT:case a.LEFT:case a.MAC_FF_META:case a.META:case a.NUMLOCK:case a.NUM_CENTER:case a.PAGE_DOWN:case a.PAGE_UP:case a.PAUSE:case a.PRINT_SCREEN:case a.RIGHT:case a.SHIFT:case a.UP:case a.WIN_KEY:case a.WIN_KEY_RIGHT:return!1;
default:return!0}},isCharacterKey:function(b){if(b>=a.ZERO&&b<=a.NINE||b>=a.NUM_ZERO&&b<=a.NUM_MULTIPLY||b>=a.A&&b<=a.Z||d.webkit&&0==b)return!0;switch(b){case a.SPACE:case a.QUESTION_MARK:case a.NUM_PLUS:case a.NUM_MINUS:case a.NUM_PERIOD:case a.NUM_DIVISION:case a.SEMICOLON:case a.DASH:case a.EQUALS:case a.COMMA:case a.PERIOD:case a.SLASH:case a.APOSTROPHE:case a.SINGLE_QUOTE:case a.OPEN_SQUARE_BRACKET:case a.BACKSLASH:case a.CLOSE_SQUARE_BRACKET:return!0;default:return!1}}};return a});
KISSY.add("event/dom/base/gesture",function(){return{start:"mousedown",move:"mousemove",end:"mouseup",tap:"click",doubleTap:"dblclick"}});
KISSY.add("event/dom/base/special-events",function(f,d,a){var b=b;return f.mix(a,{mousewheel:{typeFix:f.UA.gecko?"DOMMouseScroll":"mousewheel"},load:{bubbles:!1},click:{fire:function(a){return!a&&"checkbox"===""+this.type&&this.click&&"input"==this.nodeName.toLowerCase()?(this.click(),!1):b}},focus:{bubbles:!1,preFire:function(a,b){b||d.fire(this,"focusin")},fire:function(a){return!a&&this.ownerDocument&&this!==this.ownerDocument.activeElement&&this.focus?(this.focus(),!1):b}},blur:{bubbles:!1,preFire:function(a,
b){b||d.fire(this,"focusout")},fire:function(a){return!a&&this.ownerDocument&&this===this.ownerDocument.activeElement&&this.blur?(this.blur(),!1):b}}})},{requires:["./dom-event","./special"]});
KISSY.add("event/dom/base/mouseenter",function(f,d,a){f.each([{name:"mouseenter",fix:"mouseover"},{name:"mouseleave",fix:"mouseout"}],function(b){a[b.name]={typeFix:b.fix,handle:function(a,b,f){var j=a.currentTarget,p=a.relatedTarget;if(!p||p!==j&&!d.contains(j,p))return[b.simpleNotify(a,f)]}}})},{requires:["dom","./special"]});
KISSY.add("event/dom/base/valuechange",function(f,d,a,b){function q(b){if(a.hasData(b,g)){var c=a.data(b,g);clearTimeout(c);a.removeData(b,g)}}function m(a){q(a.target)}function t(b){var f=b.value,g=a.data(b,h);f!==g&&(d.fireHandler(b,c,{prevVal:g,newVal:f}),a.data(b,h,f))}function j(b){a.hasData(b,g)||a.data(b,g,setTimeout(function(){t(b);a.data(b,g,setTimeout(arguments.callee,n))},n))}function p(b){var c=b.target;"focus"==b.type&&a.data(c,h,c.value);j(c)}function l(a){t(a.target)}function o(b){a.removeData(b,
h);q(b);d.detach(b,"blur",m);d.detach(b,"webkitspeechchange",l);d.detach(b,"mousedown keyup keydown focus",p)}var c="valuechange",k=a.nodeName,h="event/valuechange/history",g="event/valuechange/poll",n=50;b[c]={setup:function(){var a=k(this);if("input"==a||"textarea"==a)o(this),d.on(this,"blur",m),d.on(this,"webkitspeechchange",l),d.on(this,"mousedown keyup keydown focus",p)},tearDown:function(){o(this)}};return d},{requires:["./dom-event","dom","./special"]});
KISSY.add("event/dom/base",function(f,d,a,b,q){return f.merge({add:d.on,remove:d.detach,KeyCode:a,Gesture:b,Special:q},d)},{requires:"./base/dom-event,./base/key-codes,./base/gesture,./base/special-events,./base/mouseenter,./base/valuechange".split(",")});
/*
Copyright 2013, KISSY UI Library v1.40dev
MIT Licensed
build time: Jul 3 19:20
*/
KISSY.add("event/dom/shake",function(d,k,f){function l(a){var b=a.accelerationIncludingGravity,a=b.x,d=b.y,b=b.z,g;c!==f&&(g=n(h(a-c),h(d-i),h(b-j)),g>o&&m(),g>p&&(e=1));c=a;i=d;j=b}var q=k.Special,o=5,p=20,e=0,c,i,j,n=Math.max,h=Math.abs,a=d.Env.host,m=d.buffer(function(){e&&(k.fireHandler(a,"shake",{accelerationIncludingGravity:{x:c,y:i,z:j}}),c=f,e=0)},250);q.shake={setup:function(){this==a&&a.addEventListener("devicemotion",l,!1)},tearDown:function(){this==a&&(m.stop(),c=f,e=0,a.removeEventListener("devicemotion",
l,!1))}}},{requires:["event/dom/base"]});
/*
Copyright 2013, KISSY UI Library v1.40dev
MIT Licensed
build time: Jul 3 13:48
*/
KISSY.add("anim",function(b,k,g,h,i){function a(a,e,d,f,c){if(a.node)c=a;else{"string"==typeof e?(e=b.unparam(""+e,";",":"),b.each(e,function(c,a){var d=b.trim(a);d&&(e[d]=b.trim(c));(!d||d!=a)&&delete e[a]})):e=b.clone(e);if(b.isPlainObject(d))c=b.clone(d);else if(c={complete:c},d&&(c.duration=d),f)c.easing=f;c.node=a;c.to=e}c=b.merge(j,c,{useTransition:b.config("anim/useTransition")});return c.useTransition&&i?new i(c):new h(c)}var f=g.Utils,j={duration:1,easing:"linear"};b.each(["pause","resume"],
function(b){a[b]=function(a,d){return null===d||"string"==typeof d||!1===d?f.pauseOrResumeQueue(a,d,b):f.pauseOrResumeQueue(a,void 0,b)}});a.isRunning=f.isElRunning;a.isPaused=f.isElPaused;a.stop=f.stopEl;a.Easing=h.Easing;b.Anim=a;a.Q=g.Q;return a},{requires:["dom","anim/base","anim/timer",KISSY.Features.isTransitionSupported()?"anim/transition":""]});
/*
Copyright 2013, KISSY UI Library v1.40dev
MIT Licensed
build time: Jul 3 19:20
*/
KISSY.add("event/base/utils",function(e){function f(a){if(0>a.indexOf("."))return[a,""];var b=a.match(/([^.]+)?(\..+)?$/),a=[b[1]];(b=b[2])?(b=b.split(".").sort(),a.push(b.join("."))):a.push("");return a}var d,c;return{splitAndRun:d=function(a,b){e.isArray(a)?e.each(a,b):(a=e.trim(a),-1==a.indexOf(" ")?b(a):e.each(a.split(/\s+/),b))},normalizeParam:function(a,b,c){var d=b||{},d=e.isFunction(b)?{fn:b,context:c}:e.merge(d),b=f(a),a=b[0];d.groups=b[1];d.type=a;return d},batchForType:function(a,b){var c=
e.makeArray(arguments),f=c[2+b];f&&"object"==typeof f?e.each(f,function(d,f){var e=[].concat(c);e.splice(0,2);e[b]=f;e[b+1]=d;a.apply(null,e)}):d(f,function(d){var e=[].concat(c);e.splice(0,2);e[b]=d;a.apply(null,e)})},fillGroupsForEvent:function(a,b){var d=f(a),e=d[1];e&&(e=c(e),b._ks_groups=e);b.type=d[0]},getGroupsRe:c=function(a){return RegExp(a.split(".").join(".*\\.")+"(?:\\.|$)")}}});
KISSY.add("event/base/object",function(e,f){function d(){this.timeStamp=e.now();this.currentTarget=this.target=f}var c=function(){return!1},a=function(){return!0};d.prototype={constructor:d,isDefaultPrevented:c,isPropagationStopped:c,isImmediatePropagationStopped:c,preventDefault:function(){this.isDefaultPrevented=a},stopPropagation:function(){this.isPropagationStopped=a},stopImmediatePropagation:function(){this.isImmediatePropagationStopped=a;this.stopPropagation()},halt:function(a){a?this.stopImmediatePropagation():
this.stopPropagation();this.preventDefault()}};return d});
KISSY.add("event/base/observer",function(e,f){function d(c){e.mix(this,c)}d.prototype={constructor:d,equals:function(c){var a=this;return!!e.reduce(a.keys,function(b,d){return b&&a[d]===c[d]},1)},simpleNotify:function(c,a){var b;b=this.fn.call(this.context||a.currentTarget,c,this.data);this.once&&a.removeObserver(this);return b},notifyInternal:function(c,a){return this.simpleNotify(c,a)},notify:function(c,a){var b;if((b=c._ks_groups)&&(!this.groups||!this.groups.match(b)))return f;b=this.notifyInternal(c,
a);!1===b&&c.halt();return b}};return d});
KISSY.add("event/base/observable",function(e){function f(d){this.currentTarget=null;e.mix(this,d);this.reset()}f.prototype={constructor:f,hasObserver:function(){return!!this.observers.length},reset:function(){this.observers=[]},removeObserver:function(d){var c,a=this.observers,b=a.length;for(c=0;c<b;c++)if(a[c]==d){a.splice(c,1);break}this.checkMemory()},checkMemory:function(){},findObserver:function(d){var c=this.observers,a;for(a=c.length-1;0<=a;--a)if(d.equals(c[a]))return a;return-1}};return f});
KISSY.add("event/base",function(e,f,d,c,a){return{Utils:f,Object:d,Observer:c,Observable:a}},{requires:["./base/utils","./base/object","./base/observer","./base/observable"]});
/*
Copyright 2013, KISSY UI Library v1.40dev
MIT Licensed
build time: Jul 3 13:48
*/
KISSY.add("anim/timer/easing",function(){function h(a){return a}function f(a,b,o,d){var m=3*a-3*o+1,e=3*o-6*a,g=3*a,c=3*b-3*d+1,h=3*d-6*b,f=3*b;return function(a){a:{for(var b=a,o,d,l=0;8>l;l++){d=((m*b+e)*b+g)*b-a;if(n(d)<j){a=b;break a}o=(3*m*b+2*e)*b+g;if(n(o)<j)break;b-=d/o}o=1;l=0;for(b=a;o>l;){d=((m*b+e)*b+g)*b-a;if(n(d)<j)break;0<d?o=b:l=b;b=(o+l)/2}a=b}return((c*a+h)*a+f)*a}}var i=Math.PI,c=Math.pow,k=Math.sin,b=parseFloat,g=/^cubic-bezier\(([^,]+),([^,]+),([^,]+),([^,]+)\)$/i,e={swing:function(a){return-Math.cos(a*
i)/2+0.5},easeNone:h,linear:h,easeIn:function(a){return a*a},ease:f(0.25,0.1,0.25,1),"ease-in":f(0.42,0,1,1),"ease-out":f(0,0,0.58,1),"ease-in-out":f(0.42,0,0.58,1),"ease-out-in":f(0,0.42,1,0.58),toFn:function(a){var j;return(j=a.match(g))?f(b(j[1]),b(j[2]),b(j[3]),b(j[4])):e[a]||h},easeOut:function(a){return(2-a)*a},easeBoth:function(a){return 1>(a*=2)?0.5*a*a:0.5*(1- --a*(a-2))},easeInStrong:function(a){return a*a*a*a},easeOutStrong:function(a){return 1- --a*a*a*a},easeBothStrong:function(a){return 1>
(a*=2)?0.5*a*a*a*a:0.5*(2-(a-=2)*a*a*a)},elasticIn:function(a){return 0===a||1===a?a:-(c(2,10*(a-=1))*k((a-0.075)*2*i/0.3))},elasticOut:function(a){return 0===a||1===a?a:c(2,-10*a)*k((a-0.075)*2*i/0.3)+1},elasticBoth:function(a){return 0===a||2===(a*=2)?a:1>a?-0.5*c(2,10*(a-=1))*k((a-0.1125)*2*i/0.45):0.5*c(2,-10*(a-=1))*k((a-0.1125)*2*i/0.45)+1},backIn:function(a){1===a&&(a-=0.001);return a*a*(2.70158*a-1.70158)},backOut:function(a){return(a-=1)*a*(2.70158*a+1.70158)+1},backBoth:function(a){var b,
o=(b=2.5949095)+1;return 1>(a*=2)?0.5*a*a*(o*a-b):0.5*((a-=2)*a*(o*a+b)+2)},bounceIn:function(a){return 1-e.bounceOut(1-a)},bounceOut:function(a){return a<1/2.75?7.5625*a*a:a<2/2.75?7.5625*(a-=1.5/2.75)*a+0.75:a<2.5/2.75?7.5625*(a-=2.25/2.75)*a+0.9375:7.5625*(a-=2.625/2.75)*a+0.984375},bounceBoth:function(a){return 0.5>a?0.5*e.bounceIn(2*a):0.5*e.bounceOut(2*a-1)+0.5}},j=1.0E-6,n=Math.abs;return e});
KISSY.add("anim/timer/manager",function(h,f){var i=h.stamp,c=h.Env.host,k=c.requestAnimationFrame,b=c.cancelAnimationFrame;if(!k)for(var g=["ms","moz","webkit","o"],e=0;e<g.length&&!k;++e)k=c[g[e]+"RequestAnimationFrame"],b=c[g[e]+"CancelAnimationFrame"]||c[g[e]+"CancelRequestAnimationFrame"];if(!k||h.UA.chrome)k=function(b){return setTimeout(b,15)},b=function(b){clearTimeout(b)};return{runnings:{},timer:null,start:function(b){var e=i(b);this.runnings[e]||(this.runnings[e]=b,this.startTimer())},stop:function(b){this.notRun(b)},
notRun:function(b){delete this.runnings[i(b)];h.isEmptyObject(this.runnings)&&this.stopTimer()},pause:function(b){this.notRun(b)},resume:function(b){this.start(b)},startTimer:function(){var b=this;b.timer||(b.timer=k(function a(){b.runFrames()?b.stopTimer():b.timer=k(a)}))},stopTimer:function(){var e=this.timer;e&&(b(e),this.timer=0)},runFrames:function(){var b,e,a=this.runnings;for(b in a)a[b].frame(),e=0;return e===f}}});
KISSY.add("anim/timer/fx",function(h,f,i){function c(b){this.load(b)}function k(b,g){return(!b.style||null==b.style[g])&&null!=f.attr(b,g,i,1)?1:0}c.prototype={isBasicFx:1,constructor:c,load:function(b){h.mix(this,b);this.pos=0;this.unit=this.unit||""},frame:function(b){this.pos=b;this.update();this.finished=this.finished||1==b},interpolate:function(b,g,e){return h.isNumber(b)&&h.isNumber(g)?(b+(g-b)*e).toFixed(3):i},update:function(){var b=this.prop,g=this.anim.node,e=this.to,c=this.interpolate(this.from,
e,this.pos);c===i?this.finished||(this.finished=1,f.css(g,b,e)):(c+=this.unit,k(g,b)?f.attr(g,b,c,1):f.css(g,b,c))},cur:function(){var b=this.prop,c=this.anim.node;if(k(c,b))return f.attr(c,b,i,1);var e,b=f.css(c,b);return isNaN(e=parseFloat(b))?!b||"auto"===b?0:b:e}};c.Factories={};c.getPos=function(b,c){var e=h.now(),f=c.duration,e=e-b.startTime-c.delay;return 0>=e?0:e>=f?1:c.easing(e/f)};c.getFx=function(b){return new (c.Factories[b.prop]||c)(b)};return c},{requires:["dom"]});
KISSY.add("anim/timer/short-hand",function(){return{background:[],border:["borderBottomWidth","borderLeftWidth","borderRightWidth","borderTopWidth"],borderBottom:["borderBottomWidth"],borderLeft:["borderLeftWidth"],borderTop:["borderTopWidth"],borderRight:["borderRightWidth"],font:["fontSize","fontWeight"],margin:["marginBottom","marginLeft","marginRight","marginTop"],padding:["paddingBottom","paddingLeft","paddingRight","paddingTop"]}});
KISSY.add("anim/timer/color",function(h,f,i,c){function k(b){var b=b+"",d;if(d=b.match(n))return[parseInt(d[1]),parseInt(d[2]),parseInt(d[3])];if(d=b.match(a))return[parseInt(d[1]),parseInt(d[2]),parseInt(d[3]),parseInt(d[4])];if(d=b.match(l)){for(b=1;b<d.length;b++)2>d[b].length&&(d[b]+=d[b]);return[parseInt(d[1],g),parseInt(d[2],g),parseInt(d[3],g)]}return j[b=b.toLowerCase()]?j[b]:[255,255,255]}function b(){b.superclass.constructor.apply(this,arguments)}var g=16,e=Math.floor,j={black:[0,0,0],silver:[192,
192,192],gray:[128,128,128],white:[255,255,255],maroon:[128,0,0],red:[255,0,0],purple:[128,0,128],fuchsia:[255,0,255],green:[0,128,0],lime:[0,255,0],olive:[128,128,0],yellow:[255,255,0],navy:[0,0,128],blue:[0,0,255],teal:[0,128,128],aqua:[0,255,255]},n=/^rgb\(([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+)\)$/i,a=/^rgba\(([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+),\s*([0-9]+)\)$/i,l=/^#?([0-9A-F]{1,2})([0-9A-F]{1,2})([0-9A-F]{1,2})$/i;c.background.push("backgroundColor");c.borderColor=["borderBottomColor","borderLeftColor",
"borderRightColor","borderTopColor"];c.border.push("borderBottomColor","borderLeftColor","borderRightColor","borderTopColor");c.borderBottom.push("borderBottomColor");c.borderLeft.push("borderLeftColor");c.borderRight.push("borderRightColor");c.borderTop.push("borderTopColor");h.extend(b,i,{load:function(){b.superclass.load.apply(this,arguments);this.from&&(this.from=k(this.from));this.to&&(this.to=k(this.to))},interpolate:function(a,d,c){var l=b.superclass.interpolate;return 3==a.length&&3==d.length?
"rgb("+[e(l(a[0],d[0],c)),e(l(a[1],d[1],c)),e(l(a[2],d[2],c))].join(", ")+")":4==a.length||4==d.length?"rgba("+[e(l(a[0],d[0],c)),e(l(a[1],d[1],c)),e(l(a[2],d[2],c)),e(l(a[3]||1,d[3]||1,c))].join(", ")+")":h.log("anim/color unknown value : "+a)}});h.each("backgroundColor,borderBottomColor,borderLeftColor,borderRightColor,borderTopColor,color,outlineColor".split(","),function(a){i.Factories[a]=b});return b},{requires:["dom","./fx","./short-hand"]});
KISSY.add("anim/timer",function(h,f,i,c,k,b,g,e){function j(){var a;j.superclass.constructor.apply(this,arguments);h.each(a=this.to,function(b,d){var c=n(d);d!=c&&(a[c]=a[d],delete a[d])})}var n=f._camelCase,a=/^([+\-]=)?([\d+.\-]+)([a-z%]*)$/i;h.extend(j,c,{prepareFx:function(){var b=this.node,c=this._propsData;h.each(c,function(a){a.duration*=1E3;a.delay*=1E3;"string"==typeof a.easing&&(a.easing=k.toFn(a.easing))});h.each(e,function(a,d){var e,m=c[d],g;m&&!m.fx&&(g=m.value,e={},h.each(a,function(a){e[a]=
f.css(b,a)}),f.css(b,d,g),h.each(e,function(a,d){d in c||(c[d]=h.merge(m,{value:f.css(b,d)}));f.css(b,d,a)}),delete c[d])});var d,m,p,j,i,n,r,q;for(d in c)if(m=c[d],m.fx)m.fx.prop=d;else{p=m.value;n={prop:d,anim:this,propData:m};r=g.getFx(n);j=p;i=r.cur();p+="";q="";if(p=p.match(a)){j=parseFloat(p[2]);if((q=p[3])&&"px"!==q&&i){var s=0,t=j;do++t,f.css(b,d,t+q),s=r.cur();while(0==s);i*=t/s;f.css(b,d,i+q)}p[1]&&(j=("-="===p[1]?-1:1)*j+i)}n.from=i;n.to=j;n.unit=q;r.load(n);m.fx=r}},frame:function(){var a,
b=1,d,c,e,f,h=this._propsData;for(a in h)if(f=h[a],c=f.fx,!c.finished&&(e=g.getPos(this,f),0!=e)){c.pos=e;if(c.isBasicFx){if(c.from==c.to){c.finished=c.finished||1==e;continue}d=0;if(f.frame&&(d=f.frame(this,c),!this.isRunning()))return;!1!==d&&c.frame(c.finished||e)}else if(c.finished=c.finished||1==e,c.frame(this,c),!this.isRunning())return;b&=c.finished}(!1===this.fire("step")||b)&&this.stop(b)},doStop:function(a){var c,d,e,f=this._propsData;b.stop(this);if(a)for(c in f)if(e=f[c],(a=e.fx)&&!a.finished)a.pos=
1,a.isBasicFx?(d=0,e.frame&&(d=e.frame(this,a)),!1!==d&&a.frame(1)):a.frame(this,a),a.finished=1},doStart:function(){b.start(this)}});j.Easing=k;return j},{requires:"dom,event,./base,./timer/easing,./timer/manager,./timer/fx,./timer/short-hand,./timer/color".split(",")});
/*
Copyright 2013, KISSY UI Library v1.40dev
MIT Licensed
build time: Jul 3 13:48
*/
KISSY.add("anim/transition",function(c,h,k,n){function o(b){var a="";c.each(b,function(b,f){a&&(a+=",");a+=f+" "+b.duration+"s "+b.easing+" "+b.delay+"s"});return a}function j(b){j.superclass.constructor.apply(this,arguments)}var l=c.Features.getTransitionPrefix(),m=l?l.toLowerCase()+"TransitionEnd":"transitionend",i=c.Features.getTransitionProperty();c.extend(j,n,{doStart:function(){var b=this,a=b.node,d=a.style,f=b._propsData,e=d[i],g={};c.each(f,function(f,d){var e=f.value,c=h.css(a,d);"number"==
typeof e&&(c=parseFloat(c));c==e&&setTimeout(function(){b._onTransitionEnd({originalEvent:{propertyName:d}})},0);g[d]=e});-1!=e.indexOf("none")?e="":e&&(e+=",");d[i]=e+o(f);k.on(a,m,b._onTransitionEnd,b);h.css(a,g)},beforeResume:function(){var b=this._propsData,a=c.merge(b),d=this._runTime/1E3;c.each(a,function(a,e){var c=d;a.delay>=c?a.delay-=c:(c-=a.delay,a.delay=0,a.duration>=c?a.duration-=c:delete b[e])})},_onTransitionEnd:function(b){var b=b.originalEvent,a=1,d=this._propsData;d[b.propertyName]&&
(d[b.propertyName].finished=1,c.each(d,function(b){if(!b.finished)return a=0,!1}),a&&this.stop(!0))},doStop:function(b){var a=this.node,d=a.style,f=this._propsData,e=[],g={};k.detach(a,m,this._onTransitionEnd,this);c.each(f,function(c,d){b||(g[d]=h.css(a,d));e.push(d)});f=c.trim(d[i].replace(RegExp("(^|,)\\s*(?:"+e.join("|")+")\\s+[^,]+","gi"),"$1")).replace(/^,|,,|,$/g,"")||"none";d[i]=f;h.css(a,g)}});return j},{requires:["dom","event","./base"]});
/*
Copyright 2013, KISSY UI Library v1.40dev
MIT Licensed
build time: Jul 3 19:20
*/
KISSY.add("event/custom/observer",function(h,m){function f(){f.superclass.constructor.apply(this,arguments)}h.extend(f,m.Observer,{keys:["fn","context","groups"]});return f},{requires:["event/base"]});KISSY.add("event/custom/object",function(h,m){function f(j){f.superclass.constructor.call(this);h.mix(this,j)}h.extend(f,m.Object);return f},{requires:["event/base"]});
KISSY.add("event/custom/observable",function(h,m,f,j){function i(){i.superclass.constructor.apply(this,arguments);this.defaultFn=null;this.defaultTargetOnly=!1;this.bubbles=!0}var b=j.Utils;h.extend(i,j.Observable,{on:function(a){a=new m(a);-1==this.findObserver(a)&&this.observers.push(a)},fire:function(a){var a=a||{},c=this.bubbles,d=this.currentTarget,e,l=this.type,k=this.defaultFn,n,g=a,b;a.type=l;g instanceof f||(g.target=d,g=new f(g));g.currentTarget=d;a=this.notify(g);!1!==b&&(b=a);if(c&&!g.isPropagationStopped()){e=
(c=d.getTargets(1))&&c.length||0;for(n=0;n<e&&!g.isPropagationStopped();n++)a=c[n].fire(l,g),!1!==b&&(b=a)}if(k&&!g.isDefaultPrevented()&&(l=i.getCustomEventObservable(g.target,g.type),!this.defaultTargetOnly&&!l.defaultTargetOnly||d==g.target))b=k.call(d,g);return b},notify:function(a){var c=[].concat(this.observers),d,e,b=c.length,k;for(k=0;k<b&&!a.isImmediatePropagationStopped();k++)d=c[k].notify(a,this),!1!==e&&(e=d),!1===d&&a.halt();return e},detach:function(a){var c,d=a.fn,e=a.context,l=this.currentTarget,
k=this.observers,a=a.groups;if(k.length){a&&(c=b.getGroupsRe(a));var n,g,f,h,j=k.length;if(d||c){e=e||l;n=a=0;for(g=[];a<j;++a)if(f=k[a],h=f.context||l,e!=h||d&&d!=f.fn||c&&!f.groups.match(c))g[n++]=f;this.observers=g}else this.reset()}}});i.getCustomEventObservable=function(a,c,d){var e,b=i.getCustomEventObservables(a,d);e=b&&b[c];!e&&d&&(e=b[c]=new i({currentTarget:a,type:c}));return e};i.getCustomEventObservables=function(a,b){!a["__~ks_custom_events"]&&b&&(a["__~ks_custom_events"]={});return a["__~ks_custom_events"]};
return i},{requires:["./observer","./object","event/base"]});
KISSY.add("event/custom/target",function(h,m,f){var j=m.Utils,i=j.splitAndRun;return{isTarget:1,fire:function(b,a){var c=this,d=void 0,e=c.getTargets(1),l=e&&e.length,a=a||{};i(b,function(b){var e;j.fillGroupsForEvent(b,a);b=a.type;if((e=f.getCustomEventObservable(c,b))||l){if(e){if(!e.hasObserver()&&!e.defaultFn&&(e.bubbles&&!l||!e.bubbles))return}else e=new f({currentTarget:c,type:b});b=e.fire(a);!1!==d&&(d=b)}});return d},publish:function(b,a){var c,d=this;i(b,function(e){c=f.getCustomEventObservable(d,
e,1);h.mix(c,a)});return d},addTarget:function(b){var a=this.getTargets();h.inArray(b,a)||a.push(b);return this},removeTarget:function(b){var a=this.getTargets(),b=h.indexOf(b,a);-1!=b&&a.splice(b,1);return this},getTargets:function(b){b||(this["__~ks_bubble_targets"]=this["__~ks_bubble_targets"]||[]);return this["__~ks_bubble_targets"]},on:function(b,a,c){var d=this;j.batchForType(function(a,b,c){b=j.normalizeParam(a,b,c);a=b.type;if(a=f.getCustomEventObservable(d,a,1))a.on(b)},0,b,a,c);return d},
detach:function(b,a,c){var d=this;j.batchForType(function(a,b,c){var i=j.normalizeParam(a,b,c);(a=i.type)?(a=f.getCustomEventObservable(d,a,1))&&a.detach(i):(a=f.getCustomEventObservables(d),h.each(a,function(a){a.detach(i)}))},0,b,a,c);return d}}},{requires:["event/base","./observable"]});KISSY.add("event/custom",function(h,m){return{Target:m}},{requires:["./custom/target"]});
/*
Copyright 2013, KISSY UI Library v1.40dev
MIT Licensed
build time: Jul 10 15:55
*/
KISSY.add("dom/base/api",function(c){var a=c.Env.host||{},h=a.document,r=c.UA,l={ELEMENT_NODE:1,ATTRIBUTE_NODE:2,TEXT_NODE:3,CDATA_SECTION_NODE:4,ENTITY_REFERENCE_NODE:5,ENTITY_NODE:6,PROCESSING_INSTRUCTION_NODE:7,COMMENT_NODE:8,DOCUMENT_NODE:9,DOCUMENT_TYPE_NODE:10,DOCUMENT_FRAGMENT_NODE:11,NOTATION_NODE:12},n={isCustomDomain:function(c){var c=c||a,c=n.get(c),g=c.document.domain,c=c.location.hostname;return g!=c&&g!="["+c+"]"},getEmptyIframeSrc:function(c){c=c||a;c=n.get(c);return r.ie&&n.isCustomDomain(c)?
"javascript:void(function(){"+encodeURIComponent("document.open();document.domain='"+c.document.domain+"';document.close();")+"}())":""},NodeType:l,getWindow:function(h){if(!h)return a;h=n.get(h);if(c.isWindow(h))return h;var g=h;g.nodeType!==l.DOCUMENT_NODE&&(g=h.ownerDocument);return g.defaultView||g.parentWindow},getDocument:function(a){if(!a)return h;a=n.get(a);return c.isWindow(a)?a.document:a.nodeType==l.DOCUMENT_NODE?a:a.ownerDocument},isDomNodeList:function(a){return a&&!a.nodeType&&a.item&&
!a.setTimeout},nodeName:function(a){var c=n.get(a),a=c.nodeName.toLowerCase();r.ie&&(c=c.scopeName)&&"HTML"!=c&&(a=c.toLowerCase()+":"+a);return a},_RE_NUM_NO_PX:RegExp("^("+/[\-+]?(?:\d*\.|)\d+(?:[eE][\-+]?\d+|)/.source+")(?!px)[a-z%]+$","i")};c.mix(n,l);return n});
KISSY.add("dom/base/attr",function(c,a,h){function r(a,d){var d=p[d]||d,e=y[d];return e&&e.get?e.get(a,d):a[d]}var l=c.Env.host.document,n=a.NodeType,l=l&&l.documentElement,s=a.nodeName,g=/^(?:autofocus|autoplay|async|checked|controls|defer|disabled|hidden|loop|multiple|open|readonly|required|scoped|selected)$/i,f=/^(?:button|input|object|select|textarea)$/i,j=/^a(?:rea)?$/i,q=/:|^on/,d=/\r/g,b={},m={val:1,css:1,html:1,text:1,data:1,width:1,height:1,offset:1,scrollTop:1,scrollLeft:1},u={tabindex:{get:function(a){var d=
a.getAttributeNode("tabindex");return d&&d.specified?parseInt(d.value,10):f.test(a.nodeName)||j.test(a.nodeName)&&a.href?0:h}}},p={hidefocus:"hideFocus",tabindex:"tabIndex",readonly:"readOnly","for":"htmlFor","class":"className",maxlength:"maxLength",cellspacing:"cellSpacing",cellpadding:"cellPadding",rowspan:"rowSpan",colspan:"colSpan",usemap:"useMap",frameborder:"frameBorder",contenteditable:"contentEditable"},B={get:function(d,b){return a.prop(d,b)?b.toLowerCase():h},set:function(d,b,e){!1===b?
a.removeAttr(d,e):(b=p[e]||e,b in d&&(d[b]=!0),d.setAttribute(e,e.toLowerCase()));return e}},y={},w={},x={select:{get:function(d){var b=d.selectedIndex,e=d.options,i;if(0>b)return null;if("select-one"===""+d.type)return a.val(e[b]);d=[];b=0;for(i=e.length;b<i;++b)e[b].selected&&d.push(a.val(e[b]));return d},set:function(d,b){var e=c.makeArray(b);c.each(d.options,function(d){d.selected=c.inArray(a.val(d),e)});e.length||(d.selectedIndex=-1);return e}}};c.each(["radio","checkbox"],function(d){x[d]={get:function(a){return null===
a.getAttribute("value")?"on":a.value},set:function(d,e){return c.isArray(e)?d.checked=c.inArray(a.val(d),e):h}}});u.style={get:function(a){return a.style.cssText}};c.mix(a,{_valHooks:x,_propFix:p,_attrHooks:u,_propHooks:y,_attrNodeHook:w,_attrFix:b,prop:function(d,b,e){var i=a.query(d),t,k;if(c.isPlainObject(b))return c.each(b,function(k,d){a.prop(i,d,k)}),h;b=p[b]||b;k=y[b];if(e!==h)for(d=i.length-1;0<=d;d--)t=i[d],k&&k.set?k.set(t,e,b):t[b]=e;else if(i.length)return r(i[0],b);return h},hasProp:function(d,
b){var e=a.query(d),i,c=e.length,k;for(i=0;i<c;i++)if(k=e[i],r(k,b)!==h)return!0;return!1},removeProp:function(d,b){var b=p[b]||b,e=a.query(d),i,c;for(i=e.length-1;0<=i;i--){c=e[i];try{c[b]=h,delete c[b]}catch(k){}}},attr:function(d,f,e,i){var t=a.query(d),k=t[0];if(c.isPlainObject(f)){var i=e,v;for(v in f)a.attr(t,v,f[v],i);return h}if(i&&m[f])return a[f](d,e);f=f.toLowerCase();if(i&&m[f])return a[f](d,e);f=b[f]||f;d=g.test(f)?B:q.test(f)?w:u[f];if(e===h){if(k&&k.nodeType===n.ELEMENT_NODE){"form"==
s(k)&&(d=w);if(d&&d.get)return d.get(k,f);e=k.getAttribute(f);return""===e&&(f=k.getAttributeNode(f),!f||!f.specified)?h:null===e?h:e}}else for(i=t.length-1;0<=i;i--)if((k=t[i])&&k.nodeType===n.ELEMENT_NODE)"form"==s(k)&&(d=w),d&&d.set?d.set(k,e,f):k.setAttribute(f,""+e);return h},removeAttr:function(d,c){var c=c.toLowerCase(),c=b[c]||c,e=a.query(d),i,f,k;for(k=e.length-1;0<=k;k--)if(f=e[k],f.nodeType==n.ELEMENT_NODE&&(f.removeAttribute(c),g.test(c)&&(i=p[c]||c)in f))f[i]=!1},hasAttr:l&&!l.hasAttribute?
function(d,b){var b=b.toLowerCase(),e=a.query(d),c,f;for(c=0;c<e.length;c++)if(f=e[c],(f=f.getAttributeNode(b))&&f.specified)return!0;return!1}:function(d,b){var e=a.query(d),c,f=e.length;for(c=0;c<f;c++)if(e[c].hasAttribute(b))return!0;return!1},val:function(b,f){var e,i,m,k,v;if(f===h){if(m=a.get(b)){if((e=x[s(m)]||x[m.type])&&"get"in e&&(i=e.get(m,"value"))!==h)return i;i=m.value;return"string"===typeof i?i.replace(d,""):null==i?"":i}return h}i=a.query(b);for(k=i.length-1;0<=k;k--){m=i[k];if(1!==
m.nodeType)break;v=f;null==v?v="":"number"===typeof v?v+="":c.isArray(v)&&(v=c.map(v,function(a){return a==null?"":a+""}));e=x[s(m)]||x[m.type];if(!e||!("set"in e)||e.set(m,v,"value")===h)m.value=v}return h},text:function(d,b){var e,c,f,k;if(b===h)return e=a.get(d),a._getText(e);c=a.query(d);for(f=c.length-1;0<=f;f--)if(e=c[f],k=e.nodeType,k==n.ELEMENT_NODE)a.empty(e),e.appendChild(e.ownerDocument.createTextNode(b));else if(k==n.TEXT_NODE||k==n.CDATA_SECTION_NODE)e.nodeValue=b;return h},_getText:function(a){return a.textContent}});
return a},{requires:["./api"]});
KISSY.add("dom/base/class",function(c,a){function h(a){for(var a=c.trim(a||""),a=a.split(g),h=[],q,d=a.length,b=0;b<d;b++)(q=a[b])&&h.push(q);return h}function r(a){return function(c,h){var d,b,m,g=c.classList,p=n.call(arguments,2);d=0;for(b=h.length;d<b;d++)(m=h[d])&&g[a].apply(g,[m].concat(p))}}function l(c){return function(g,q){var d=h(q),b=n.call(arguments,2);a.query(g).each(function(m){m.nodeType==s.ELEMENT_NODE&&a[c].apply(a,[m,d].concat(b))})}}var n=[].slice,s=a.NodeType,g=/[\.\s]\s*\.?/;c.mix(a,
{_hasClass:function(a,c){var h,d,b,m=a.classList;if(m.length){h=0;for(d=c.length;h<d;h++)if((b=c[h])&&!m.contains(b))return!1;return!0}return!1},_addClass:r("add"),_removeClass:r("remove"),_toggleClass:r("toggle"),hasClass:function(c,g){var q=a.get(c);return q&&q.nodeType==s.ELEMENT_NODE&&a._hasClass(q,h(g))},replaceClass:function(c,h,g){a.removeClass(c,h);a.addClass(c,g)},addClass:l("_addClass"),removeClass:l("_removeClass"),toggleClass:l("_toggleClass")});return a},{requires:["./api"]});
KISSY.add("dom/base/create",function(c,a,h){function r(d){var b=c.require("event/dom");b&&b.detach(d);a.removeData(d)}function l(a,e){var c=e&&e!=f?e.createElement(d):b;c.innerHTML="m<div>"+a+"</div>";return c.lastChild}function n(a,d,b){var e=d.nodeType;if(e==j.DOCUMENT_FRAGMENT_NODE){d=d.childNodes;b=b.childNodes;for(e=0;d[e];)b[e]&&n(a,d[e],b[e]),e++}else if(e==j.ELEMENT_NODE){d=d.getElementsByTagName("*");b=b.getElementsByTagName("*");for(e=0;d[e];)b[e]&&a(d[e],b[e]),e++}}function s(d,b){var e=
c.require("event/dom"),i,o;if(b.nodeType!=j.ELEMENT_NODE||a.hasData(d)){i=a.data(d);for(o in i)a.data(b,o,i[o]);e&&e.clone(d,b)}}function g(a){var d=null,b,e;if(a&&(a.push||a.item)&&a[0]){d=a[0].ownerDocument;d=d.createDocumentFragment();a=c.makeArray(a);b=0;for(e=a.length;b<e;b++)d.appendChild(a[b])}return d}var f=c.Env.host.document,j=a.NodeType,q=c.UA.ie,d="div",b=f&&f.createElement(d),m=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/ig,u=/<([\w:]+)/,p=/^\s+/,B=/\s+$/,y=
q&&9>q,w=/<|&#?\w+;/,x=f&&"outerHTML"in f.documentElement,A=/^<(\w+)\s*\/?>(?:<\/\1>)?$/;c.mix(a,{create:function(b,e,i,t){var o=null;if(!b)return o;if(b.nodeType)return a.clone(b);if("string"!=typeof b)return o;t===h&&(t=!0);t&&(b=c.trim(b));var t=a._creators,z,D,i=i||f,E,F=d;if(w.test(b))if(E=A.exec(b))o=i.createElement(E[1]);else{b=b.replace(m,"<$1></$2>");if((E=u.exec(b))&&(z=E[1]))F=z.toLowerCase();z=(t[F]||l)(b,i);y&&(D=b.match(p))&&z.insertBefore(i.createTextNode(D[0]),z.firstChild);y&&/\S/.test(b)&&
(D=b.match(B))&&z.appendChild(i.createTextNode(D[0]));b=z.childNodes;1===b.length?o=b[0].parentNode.removeChild(b[0]):b.length&&(o=g(b))}else o=i.createTextNode(b);c.isPlainObject(e)&&(o.nodeType==j.ELEMENT_NODE?a.attr(o,e,!0):o.nodeType==j.DOCUMENT_FRAGMENT_NODE&&a.attr(o.childNodes,e,!0));return o},_fixCloneAttributes:function(d,b){"textarea"===a.nodeName(d)&&(b.defaultValue=d.defaultValue,b.value=d.value)},_creators:{div:l},_defaultCreator:l,html:function(d,b,e){var d=a.query(d),c=d[0],o=!1,z,
f;if(!c)return null;if(b===h)return c.nodeType==j.ELEMENT_NODE?c.innerHTML:null;b+="";if(!b.match(/<(?:script|style|link)/i)&&(!y||!b.match(p))&&!i[(b.match(u)||["",""])[1].toLowerCase()])try{for(z=d.length-1;0<=z;z--)f=d[z],f.nodeType==j.ELEMENT_NODE&&(r(f.getElementsByTagName("*")),f.innerHTML=b);o=!0}catch(m){}o||(b=a.create(b,0,c.ownerDocument,0),a.empty(d),a.append(b,d,e));return h},outerHtml:function(e,c,i){var m=a.query(e),o=m.length,e=m[0];if(!e)return null;if(c===h){if(x)return e.outerHTML;
c=(c=e.ownerDocument)&&c!=f?c.createElement(d):b;c.innerHTML="";c.appendChild(a.clone(e,!0));c.appendChild(a.clone(e,!0));return c.innerHTML}c+="";if(!c.match(/<(?:script|style|link)/i)&&x)for(i=o-1;0<=i;i--)e=m[i],e.nodeType==j.ELEMENT_NODE&&(r(e),r(e.getElementsByTagName("*")),e.outerHTML=c);else e=a.create(c,0,e.ownerDocument,0),a.insertBefore(e,m,i),a.remove(m);return h},remove:function(d,b){var e,i=a.query(d),o,z,f=c.require("event/dom"),m;for(m=i.length-1;0<=m;m--)e=i[m],!b&&e.nodeType==j.ELEMENT_NODE&&
(o=c.makeArray(e.getElementsByTagName("*")),o.push(e),a.removeData(o),f&&f.detach(o)),(z=e.parentNode)&&z.removeChild(e)},clone:function(d,b,e,c){"object"===typeof b&&(c=b.deepWithDataAndEvent,e=b.withDataAndEvent,b=b.deep);var d=a.get(d),o,i=a._fixCloneAttributes,f;if(!d)return null;f=d.nodeType;o=d.cloneNode(b);if(f==j.ELEMENT_NODE||f==j.DOCUMENT_FRAGMENT_NODE)i&&f==j.ELEMENT_NODE&&i(d,o),b&&i&&n(i,d,o);e&&(s(d,o),b&&c&&n(s,d,o));return o},empty:function(d){var d=a.query(d),b,e;for(e=d.length-1;0<=
e;e--)b=d[e],a.remove(b.childNodes)},_nodeListToFragment:g});a.outerHTML=a.outerHtml;var C=a._creators,e=a.create,i={option:"select",optgroup:"select",area:"map",thead:"table",td:"tr",th:"tr",tr:"tbody",tbody:"table",tfoot:"table",caption:"table",colgroup:"table",col:"colgroup",legend:"fieldset"},t;for(t in i)(function(a){C[t]=function(d,b){return e("<"+a+">"+d+"</"+a+">",null,b)}})(i[t]);return a},{requires:["./api"]});
KISSY.add("dom/base/data",function(c,a,h){var r=c.Env.host,l="_ks_data_"+c.now(),n={},s={},g={applet:1,object:1,embed:1},f={hasData:function(a,b){if(a)if(b!==h){if(b in a)return!0}else if(!c.isEmptyObject(a))return!0;return!1}},j={hasData:function(a,b){return a==r?j.hasData(s,b):f.hasData(a[l],b)},data:function(a,b,c){if(a==r)return j.data(s,b,c);var f=a[l];if(c!==h)f=a[l]=a[l]||{},f[b]=c;else return b!==h?f&&f[b]:f=a[l]=a[l]||{}},removeData:function(a,b){if(a==r)return j.removeData(s,b);var f=a[l];
if(b!==h)delete f[b],c.isEmptyObject(f)&&j.removeData(a);else try{delete a[l]}catch(g){a[l]=h}}},q={hasData:function(a,b){var c=a[l];return!c?!1:f.hasData(n[c],b)},data:function(a,b,f){if(g[a.nodeName.toLowerCase()])return h;var u=a[l];if(!u){if(b!==h&&f===h)return h;u=a[l]=c.guid()}a=n[u];if(f!==h)a=n[u]=n[u]||{},a[b]=f;else return b!==h?a&&a[b]:a=n[u]=n[u]||{}},removeData:function(a,b){var f=a[l],g;if(f)if(g=n[f],b!==h)delete g[b],c.isEmptyObject(g)&&q.removeData(a);else{delete n[f];try{delete a[l]}catch(p){a[l]=
h}a.removeAttribute&&a.removeAttribute(l)}}};c.mix(a,{__EXPANDO:l,hasData:function(d,b){for(var c=!1,f=a.query(d),h=0;h<f.length&&!(c=f[h],c=c.nodeType?q.hasData(c,b):j.hasData(c,b));h++);return c},data:function(d,b,f){var d=a.query(d),g=d[0];if(c.isPlainObject(b)){for(var p in b)a.data(d,p,b[p]);return h}if(f===h){if(g)return g.nodeType?q.data(g,b):j.data(g,b)}else for(p=d.length-1;0<=p;p--)g=d[p],g.nodeType?q.data(g,b,f):j.data(g,b,f);return h},removeData:function(d,b){var c=a.query(d),f,h;for(h=
c.length-1;0<=h;h--)f=c[h],f.nodeType?q.removeData(f,b):j.removeData(f,b)}});return a},{requires:["./api"]});
KISSY.add("dom/base/insertion",function(c,a){function h(a,b){var c=[],l,p,r;for(l=0;a[l];l++)if(p=a[l],r=g(p),p.nodeType==n.DOCUMENT_FRAGMENT_NODE)c.push.apply(c,h(f(p.childNodes),b));else if("script"===r&&(!p.type||q.test(p.type)))p.parentNode&&p.parentNode.removeChild(p),b&&b.push(p);else{if(p.nodeType==n.ELEMENT_NODE&&!s.test(r)){r=[];var y,w,x=p.getElementsByTagName("script");for(w=0;w<x.length;w++)y=x[w],(!y.type||q.test(y.type))&&r.push(y);j.apply(a,[l+1,0].concat(r))}c.push(p)}return c}function r(a){a.src?
c.getScript(a.src):(a=c.trim(a.text||a.textContent||a.innerHTML||""))&&c.globalEval(a)}function l(d,b,f,g){d=a.query(d);g&&(g=[]);d=h(d,g);a._fixInsertionChecked&&a._fixInsertionChecked(d);var b=a.query(b),j,l,y,w,x=b.length;if((d.length||g&&g.length)&&x){d=a._nodeListToFragment(d);1<x&&(w=a.clone(d,!0),b=c.makeArray(b));for(j=0;j<x;j++)l=b[j],d&&(y=0<j?a.clone(w,!0):d,f(y,l)),g&&g.length&&c.each(g,r)}}var n=a.NodeType,s=/^(?:button|input|object|select|textarea)$/i,g=a.nodeName,f=c.makeArray,j=[].splice,
q=/\/(java|ecma)script/i;c.mix(a,{_fixInsertionChecked:null,insertBefore:function(a,b,c){l(a,b,function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)},c)},insertAfter:function(a,b,c){l(a,b,function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)},c)},appendTo:function(a,b,c){l(a,b,function(a,b){b.appendChild(a)},c)},prependTo:function(a,b,c){l(a,b,function(a,b){b.insertBefore(a,b.firstChild)},c)},wrapAll:function(c,b){b=a.clone(a.get(b),!0);c=a.query(c);c[0].parentNode&&a.insertBefore(b,
c[0]);for(var f;(f=b.firstChild)&&1==f.nodeType;)b=f;a.appendTo(c,b)},wrap:function(d,b){d=a.query(d);b=a.get(b);c.each(d,function(c){a.wrapAll(c,b)})},wrapInner:function(d,b){d=a.query(d);b=a.get(b);c.each(d,function(c){var d=c.childNodes;d.length?a.wrapAll(d,b):c.appendChild(b)})},unwrap:function(d){d=a.query(d);c.each(d,function(b){b=b.parentNode;a.replaceWith(b,b.childNodes)})},replaceWith:function(c,b){var f=a.query(c),b=a.query(b);a.remove(b,!0);a.insertBefore(b,f);a.remove(f)}});c.each({prepend:"prependTo",
append:"appendTo",before:"insertBefore",after:"insertAfter"},function(c,b){a[b]=a[c]});return a},{requires:["./api"]});
KISSY.add("dom/base/offset",function(c,a,h){function r(a){var c,d=a.ownerDocument.body;if(!a.getBoundingClientRect)return{left:0,top:0};c=a.getBoundingClientRect();a=c[b];c=c[m];a-=j.clientLeft||d.clientLeft||0;c-=j.clientTop||d.clientTop||0;return{left:a,top:c}}function l(b,c){var d={left:0,top:0},f=q(b),h,e=b,c=c||f;do{if(f==c){var i=e;h=r(i);i=q(i);h.left+=a[p](i);h.top+=a[B](i)}else h=r(e);d.left+=h.left;d.top+=h.top}while(f&&f!=c&&(e=f.frameElement)&&(f=f.parent));return d}var n=c.Env.host,s=
c.UA,g=n.document,f=a.NodeType,j=g&&g.documentElement,q=a.getWindow,d=Math.max,b="left",m="top",u=c.isNumber,p="scrollLeft",B="scrollTop";c.mix(a,{offset:function(b,c,d){if(c===h){var b=a.get(b),f;b&&(f=l(b,d));return f}d=a.query(b);for(f=d.length-1;0<=f;f--){var b=d[f],g=c;"static"===a.css(b,"position")&&(b.style.position="relative");var e=l(b),i={},t=void 0,k=void 0;for(k in g)t=parseFloat(a.css(b,k))||0,i[k]=t+g[k]-e[k];a.css(b,i)}return h},scrollIntoView:function(d,g,j,l){var p,e,i,t;if(i=a.get(d)){g&&
(g=a.get(g));g||(g=i.ownerDocument);g.nodeType==f.DOCUMENT_NODE&&(g=q(g));c.isPlainObject(j)&&(l=j.allowHorizontalScroll,t=j.onlyScrollIfNeeded,j=j.alignWithTop);l=l===h?!0:l;e=c.isWindow(g);var d=a.offset(i),k=a.outerHeight(i);p=a.outerWidth(i);var v,n,r,o;e?(e=g,v=a.height(e),n=a.width(e),o={left:a.scrollLeft(e),top:a.scrollTop(e)},e=d[b]-o[b],i=d[m]-o[m],p=d[b]+p-(o[b]+n),d=d[m]+k-(o[m]+v)):(v=a.offset(g),n=g.clientHeight,r=g.clientWidth,o={left:a.scrollLeft(g),top:a.scrollTop(g)},e=d[b]-(v[b]+
(parseFloat(a.css(g,"borderLeftWidth"))||0)),i=d[m]-(v[m]+(parseFloat(a.css(g,"borderTopWidth"))||0)),p=d[b]+p-(v[b]+r+(parseFloat(a.css(g,"borderRightWidth"))||0)),d=d[m]+k-(v[m]+n+(parseFloat(a.css(g,"borderBottomWidth"))||0)));if(t){if(0>i||0<d)!0===j?a.scrollTop(g,o.top+i):!1===j?a.scrollTop(g,o.top+d):0>i?a.scrollTop(g,o.top+i):a.scrollTop(g,o.top+d)}else(j=j===h?!0:!!j)?a.scrollTop(g,o.top+i):a.scrollTop(g,o.top+d);if(l)if(t){if(0>e||0<p)!0===j?a.scrollLeft(g,o.left+e):!1===j?a.scrollLeft(g,
o.left+p):0>e?a.scrollLeft(g,o.left+e):a.scrollLeft(g,o.left+p)}else(j=j===h?!0:!!j)?a.scrollLeft(g,o.left+e):a.scrollLeft(g,o.left+p)}},docWidth:0,docHeight:0,viewportHeight:0,viewportWidth:0,scrollTop:0,scrollLeft:0});c.each(["Left","Top"],function(b,c){var d="scroll"+b;a[d]=function(g,j){if(u(g))return arguments.callee(n,g);var g=a.get(g),e,i,t,k;g&&g.nodeType==f.ELEMENT_NODE?j!==h?g[d]=parseFloat(j):e=g[d]:(k=q(g),j!==h?(j=parseFloat(j),i="Left"==b?j:a.scrollLeft(k),t="Top"==b?j:a.scrollTop(k),
k.scrollTo(i,t)):(e=k["page"+(c?"Y":"X")+"Offset"],u(e)||(i=k.document,e=i.documentElement[d],u(e)||(e=i.body[d]))));return e}});c.each(["Width","Height"],function(b){a["doc"+b]=function(c){c=a.get(c);c=a.getDocument(c);return d(c.documentElement["scroll"+b],c.body["scroll"+b],a["viewport"+b](c))};a["viewport"+b]=function(c){var c=a.get(c),d=q(c),c=d["inner"+b];if(s.mobile&&c)return c;var c="client"+b,d=d.document,f=d.body,g=d.documentElement[c];return"CSS1Compat"===d.compatMode&&g||f&&f[c]||g}});
return a},{requires:["./api"]});
KISSY.add("dom/base/style",function(c,a,h){function r(a,b){return b.toUpperCase()}function l(a){return a.replace(w,"ms-").replace(v,r)}function n(a,b,c){var d={},e;for(e in b)d[e]=a[m][e],a[m][e]=b[e];c.call(a);for(e in b)a[m][e]=d[e]}function s(a,b,c){var d,e,f;if(3===a.nodeType||8===a.nodeType||!(d=a[m]))return h;b=l(b);f=i[b];b=t[b]||b;if(c!==h){null===c||c===A?c=A:!isNaN(Number(c))&&!y[b]&&(c+=C);f&&f.set&&(c=f.set(a,c));if(c!==h){try{d[b]=c}catch(g){}c===A&&d.removeAttribute&&d.removeAttribute(b)}d.cssText||
a.removeAttribute("style");return h}if(!f||!("get"in f&&(e=f.get(a,!1))!==h))e=d[b];return e===h?"":e}function g(a){var b,c=arguments;0!==a.offsetWidth?b=f.apply(h,c):n(a,G,function(){b=f.apply(h,c)});return b}function f(b,d,e){if(c.isWindow(b))return d==p?a.viewportWidth(b):a.viewportHeight(b);if(9==b.nodeType)return d==p?a.docWidth(b):a.docHeight(b);var f=d===p?["Left","Right"]:["Top","Bottom"],g=d===p?b.offsetWidth:b.offsetHeight;if(0<g)return"border"!==e&&c.each(f,function(c){e||(g-=parseFloat(a.css(b,
"padding"+c))||0);g="margin"===e?g+(parseFloat(a.css(b,e+c))||0):g-(parseFloat(a.css(b,"border"+c+"Width"))||0)}),g;g=a._getComputedStyle(b,d);if(null==g||0>Number(g))g=b.style[d]||0;g=parseFloat(g)||0;e&&c.each(f,function(c){g+=parseFloat(a.css(b,"padding"+c))||0;"padding"!==e&&(g+=parseFloat(a.css(b,"border"+c+"Width"))||0);"margin"===e&&(g+=parseFloat(a.css(b,e+c))||0)});return g}var j=c.Env.host,q=c.UA,d=a.nodeName,b=j.document,m="style",u=/^margin/,p="width",B="display"+c.now(),y={fillOpacity:1,
fontWeight:1,lineHeight:1,opacity:1,orphans:1,widows:1,zIndex:1,zoom:1},w=/^-ms-/,x=/([A-Z]|^ms)/g,A="",C="px",e=/\d(?!px)[a-z%]+$/i,i={},t={"float":"cssFloat"},k={},v=/-([a-z])/ig;c.mix(a,{_camelCase:l,_CUSTOM_STYLES:i,_cssProps:t,_getComputedStyle:function(b,c){var d="",e,f,g,i,h;f=b.ownerDocument;c=c.replace(x,"-$1").toLowerCase();if(e=f.defaultView.getComputedStyle(b,null))d=e.getPropertyValue(c)||e[c];""===d&&!a.contains(f,b)&&(c=t[c]||c,d=b[m][c]);a._RE_NUM_NO_PX.test(d)&&u.test(c)&&(h=b.style,
f=h.width,g=h.minWidth,i=h.maxWidth,h.minWidth=h.maxWidth=h.width=d,d=e.width,h.width=f,h.minWidth=g,h.maxWidth=i);return d},style:function(b,d,e){var b=a.query(b),f,g=b[0];if(c.isPlainObject(d)){for(f in d)for(g=b.length-1;0<=g;g--)s(b[g],f,d[f]);return h}if(e===h)return f="",g&&(f=s(g,d,e)),f;for(g=b.length-1;0<=g;g--)s(b[g],d,e);return h},css:function(b,d,e){var b=a.query(b),f=b[0],g;if(c.isPlainObject(d)){for(g in d)for(f=b.length-1;0<=f;f--)s(b[f],g,d[g]);return h}d=l(d);g=i[d];if(e===h){e="";
if(f&&(!g||!("get"in g&&(e=g.get(f,!0))!==h)))e=a._getComputedStyle(f,d);return"undefined"==typeof e?"":e}for(f=b.length-1;0<=f;f--)s(b[f],d,e);return h},show:function(c){var c=a.query(c),d,e,f;for(f=c.length-1;0<=f;f--)if(e=c[f],e[m].display=a.data(e,B)||A,"none"===a.css(e,"display")){d=e.tagName.toLowerCase();var g=void 0,i=k[d],h=void 0;k[d]||(g=b.body||b.documentElement,h=b.createElement(d),a.prepend(h,g),i=a.css(h,"display"),g.removeChild(h),k[d]=i);d=i;a.data(e,B,d);e[m].display=d}},hide:function(b){var b=
a.query(b),c,d;for(d=b.length-1;0<=d;d--){c=b[d];var e=c[m],f=e.display;"none"!==f&&(f&&a.data(c,B,f),e.display="none")}},toggle:function(b){var b=a.query(b),c,d;for(d=b.length-1;0<=d;d--)c=b[d],"none"===a.css(c,"display")?a.show(c):a.hide(c)},addStyleSheet:function(b,c,d){"string"==typeof b&&(d=c,c=b,b=j);var b=a.getDocument(b),e;if(d&&(d=d.replace("#",A)))e=a.get("#"+d,b);e||(e=a.create("<style>",{id:d},b),a.get("head",b).appendChild(e),e.styleSheet?e.styleSheet.cssText=c:e.appendChild(b.createTextNode(c)))},
unselectable:function(b){var b=a.query(b),e,f,g=0,i,h;for(f=b.length-1;0<=f;f--)if(e=b[f],h=e[m],h.UserSelect="none",q.gecko)h.MozUserSelect="none";else if(q.webkit)h.WebkitUserSelect="none";else if(q.ie||q.opera){h=e.getElementsByTagName("*");e.setAttribute("unselectable","on");for(i=["iframe","textarea","input","select"];e=h[g++];)c.inArray(d(e),i)||e.setAttribute("unselectable","on")}},innerWidth:0,innerHeight:0,outerWidth:0,outerHeight:0,width:0,height:0});c.each([p,"height"],function(b){a["inner"+
c.ucfirst(b)]=function(c){return(c=a.get(c))&&g(c,b,"padding")};a["outer"+c.ucfirst(b)]=function(c,d){var e=a.get(c);return e&&g(e,b,d?"margin":"border")};a[b]=function(c,d){var e=a.css(c,b,d);e&&(e=parseFloat(e));return e};i[b]={get:function(a,c){var d;c&&(d=g(a,b)+"px");return d}}});var G={position:"absolute",visibility:"hidden",display:"block"};c.each(["left","top"],function(c){i[c]={get:function(d,f){var g,i,h;if(f){h=a.css(d,"position");if("static"===h)return"auto";g=a._getComputedStyle(d,c);
if((i="auto"===g)&&"relative"===h)return"0px";if(i||e.test(g)){h={top:0,left:0};if("fixed"==a.css(d,"position"))i=d.getBoundingClientRect();else{for(g=d.offsetParent||(d.ownerDocument||b).body;g&&!H.test(g.nodeName)&&"static"===a.css(g,"position");)g=g.offsetParent;i=a.offset(d);h=a.offset(g);h.top+=parseFloat(a.css(g,"borderTopWidth"))||0;h.left+=parseFloat(a.css(g,"borderLeftWidth"))||0}i.top-=parseFloat(a.css(d,"marginTop"))||0;i.left-=parseFloat(a.css(d,"marginLeft"))||0;g={top:i.top-h.top,left:i.left-
h.left}[c]+"px"}}return g}}});var H=/^(?:body|html)$/i;return a},{requires:["./api"]});
KISSY.add("dom/base/selector",function(c,a,h){function r(a){var b=this.length,c;for(c=0;c<b&&!1!==a(this[c],c);c++);}function l(a){return"#"==a.charAt(0)?n(a.substr(1)):"."==a.charAt(0)?s(a.substr(1)):g(a.substr(0))}function n(a){return function(){var b=document.getElementById(a);return b?[b]:[]}}function s(a){return function(b){return b.getElementsByClassName(a)}}function g(a){return function(b){return b.getElementsByTagName(a)}}function f(d,g){var j,k;j="string"==typeof d;var m=g!==h?f(g):(k=1)&&
[b],q=m.length,n=/^\.([\w-]+)$/,o=/^#([\w-]*)$/,s=/^[\w-]+$/,u=/^[\w-]#[\w-]$/;if(d)if(j)if(d=C(d),k&&"body"==d)j=[b.body];else if(u.test(d))j=[b.getElementById(RegExp.$1)];else if(o.test(d)||"getElementsByTagName"in document&&s.test(d)||"getElementsByClassName"in document&&n.test(d))j=c.makeArray(l(d)(b));else{if(k="getElementsByTagName"in document)if(k="getElementsByClassName"in document)a:{k=d;j=[/\+/,/\=/,/\~/,/\[/,/\]/,/:/,/>/,/\|/,/\$/,/\^/,/\*/,/\(/,/\)/,/[\w-]\.[\w-]/i,/[\w-]\#[\w-]/i];for(n=
0;n<j.length;n++)if(k.match(j[n])){k=!1;break a}k=!0}if(k){q=d.split(/\s+/);k=0;for(j=q.length;k<j;k++)q[k]=l(q[k]);k=0;for(n=q.length;k<n;k++){o=q[k];s=[];u=0;for(j=m.length;u<j;u++)for(var w=o(m[u]),A=0,I=w.length;A<I;A++)s[s.length++]=w[A];m=s}console.log("speedup");j=m?m:[]}else if("querySelectorAll"in document&&1===q)console.log("simple querySelector"),j=c.makeArray(m[0].querySelectorAll(d));else{j=[];for(k=0;k<q;k++)"querySelectorAll"in document?(console.log("chain's querySelector"),j=j.concat(c.makeArray(m[k].querySelectorAll(d)))):
x.apply(j,a._selectInternal(d,m[k]));1<j.length&&1<q&&a.unique(j);console.log("normal")}}else{if(j=d.nodeType||d.setTimeout?[d]:d.getDOMNodes?d.getDOMNodes():p(d)?d:y(d)?B(d):[d],!k){n=j;s=n.length;j=[];for(k=0;k<s;k++)for(o=0;o<q;o++)if(a._contains(m[o],n[k])){j.push(n[k]);break}}}else j=[];j.each=r;return j}function j(a,b){var d=a&&(a.className||q(a,"class"));return d&&-1<(w+d+w).indexOf(w+b+w)}function q(a,b){var d=a&&a.getAttributeNode(b);return d&&d.specified?d.nodeValue:h}function d(a,b){return"*"==
b||a.nodeName.toLowerCase()===b.toLowerCase()}var b=c.Env.host.document,m=b.documentElement,u=m.matches||m.webkitMatchesSelector||m.mozMatchesSelector||m.oMatchesSelector||m.msMatchesSelector,p=c.isArray,B=c.makeArray,y=a.isDomNodeList,w=" ",x=Array.prototype.push,A=/^(?:#([\w-]+))?\s*([\w-]+|\*)?\.?([\w-]+)?$/,C=c.trim;c.mix(a,{_compareNodeOrder:function(a,b){return!a.compareDocumentPosition||!b.compareDocumentPosition?a.compareDocumentPosition?-1:1:a.compareDocumentPosition(b)&4?-1:1},_getSimpleAttr:q,
_isTag:d,_hasSingleClass:j,_matchesInternal:function(a,b){for(var d=[],c=0,f,g=b.length;c<g;c++)f=b[c],u.call(f,a)&&d.push(f);return d},_selectInternal:function(a,b){return B(b.querySelectorAll(a))},query:f,get:function(a,b){return f(a,b)[0]||null},unique:function(){function b(c,e){return c==e?(d=!0,0):a._compareNodeOrder(c,e)}var d,c=!0;[0,0].sort(function(){c=!1;return 0});return function(a){d=c;a.sort(b);if(d)for(var f=1,g=a.length;f<g;)a[f]===a[f-1]?(a.splice(f,1),--g):f++;return a}}(),filter:function(b,
g,h){var b=f(b,h),k,m,l,n,h=[];if("string"==typeof g&&(g=C(g))&&(l=A.exec(g)))k=l[1],m=l[2],n=l[3],k?k&&!m&&!n&&(g=function(a){return q(a,"id")==k}):g=function(a){var b=!0,c=!0;m&&(b=d(a,m));n&&(c=j(a,n));return c&&b};return h=c.isFunction(g)?c.filter(b,g):a._matchesInternal(g,b)},test:function(b,d,c){b=f(b,c);return b.length&&a.filter(b,d,c).length===b.length}});return a},{requires:["./api"]});
KISSY.add("dom/base/traversal",function(c,a,h){function r(g,f,j,q,d,b,m){if(!(g=a.get(g)))return null;if(0===f)return g;b||(g=g[j]);if(!g)return null;d=d&&a.get(d)||null;f===h&&(f=1);var b=[],n=c.isArray(f),p,r;c.isNumber(f)&&(p=0,r=f,f=function(){return++p===r});for(;g&&g!=d;){if((g.nodeType==s.ELEMENT_NODE||g.nodeType==s.TEXT_NODE&&m)&&l(g,f)&&(!q||q(g)))if(b.push(g),!n)break;g=g[j]}return n?b:b[0]||null}function l(g,f){if(!f)return!0;if(c.isArray(f)){var h,l=f.length;if(!l)return!0;for(h=0;h<l;h++)if(a.test(g,
f[h]))return!0}else if(a.test(g,f))return!0;return!1}function n(g,f,h,l){var d=[],b,m;if((b=g=a.get(g))&&h)b=g.parentNode;if(b){h=c.makeArray(b.childNodes);for(b=0;b<h.length;b++)m=h[b],(l||m.nodeType==s.ELEMENT_NODE)&&m!=g&&d.push(m);f&&(d=a.filter(d,f))}return d}var s=a.NodeType;c.mix(a,{_contains:function(a,c){return!!(a.compareDocumentPosition(c)&16)},closest:function(a,c,h,l){return r(a,c,"parentNode",function(a){return a.nodeType!=s.DOCUMENT_FRAGMENT_NODE},h,!0,l)},parent:function(a,c,j){return r(a,
c,"parentNode",function(a){return a.nodeType!=s.DOCUMENT_FRAGMENT_NODE},j,h)},first:function(c,f,j){c=a.get(c);return r(c&&c.firstChild,f,"nextSibling",h,h,!0,j)},last:function(c,f,j){c=a.get(c);return r(c&&c.lastChild,f,"previousSibling",h,h,!0,j)},next:function(a,c,j){return r(a,c,"nextSibling",h,h,h,j)},prev:function(a,c,j){return r(a,c,"previousSibling",h,h,h,j)},siblings:function(a,c,h){return n(a,c,!0,h)},children:function(a,c){return n(a,c,h)},contents:function(a,c){return n(a,c,h,1)},contains:function(c,
f){c=a.get(c);f=a.get(f);return c&&f?a._contains(c,f):!1},index:function(g,f){var h=a.query(g),l,d=0;l=h[0];if(!f){h=l&&l.parentNode;if(!h)return-1;for(;l=l.previousSibling;)l.nodeType==s.ELEMENT_NODE&&d++;return d}d=a.query(f);return"string"===typeof f?c.indexOf(l,d):c.indexOf(d[0],h)},equals:function(c,f){c=a.query(c);f=a.query(f);if(c.length!=f.length)return!1;for(var h=c.length;0<=h;h--)if(c[h]!=f[h])return!1;return!0}});return a},{requires:["./api"]});
KISSY.add("dom/base",function(c,a){c.mix(c,{DOM:a,get:a.get,query:a.query});return a},{requires:"./base/api,./base/attr,./base/class,./base/create,./base/data,./base/insertion,./base/offset,./base/style,./base/selector,./base/traversal".split(",")});
/*
Copyright 2013, KISSY UI Library v1.40dev
MIT Licensed
build time: Jul 3 19:20
*/
KISSY.add("event",function(a,c,b){a.EventTarget=b.Target;return a.Event=a.merge(c,b)},{requires:["event/dom","event/custom"]});
/*
Copyright 2013, KISSY UI Library v1.40dev
MIT Licensed
build time: Jul 3 13:57
*/
KISSY.add("node/base",function(b,h,i,j){function f(c,m,g){if(!(this instanceof f))return new f(c,m,g);if(c)if("string"==typeof c){if(c=h.create(c,m,g),c.nodeType===l.DOCUMENT_FRAGMENT_NODE)return d.apply(this,a(c.childNodes)),this}else{if(b.isArray(c)||e(c))return d.apply(this,a(c)),this}else return this;this[0]=c;this.length=1;return this}var g=Array.prototype,k=g.slice,l=h.NodeType,d=g.push,a=b.makeArray,e=h.isDomNodeList;f.prototype={constructor:f,isNodeList:!0,length:0,item:function(c){return b.isNumber(c)?
c>=this.length?null:new f(this[c]):new f(c)},add:function(c,a,e){b.isNumber(a)&&(e=a,a=j);c=f.all(c,a).getDOMNodes();a=new f(this);e===j?d.apply(a,c):(e=[e,0],e.push.apply(e,c),g.splice.apply(a,e));return a},slice:function(c,a){return new f(k.apply(this,arguments))},getDOMNodes:function(){return k.call(this)},each:function(c,a){var e=this;b.each(e,function(d,b){d=new f(d);return c.call(a||d,d,b,e)});return e},getDOMNode:function(){return this[0]},end:function(){return this.__parent||this},filter:function(c){return new f(h.filter(this,
c))},all:function(c){c=0<this.length?f.all(c,this):new f;c.__parent=this;return c},one:function(c){c=this.all(c);if(c=c.length?c.slice(0,1):null)c.__parent=this;return c}};b.mix(f,{all:function(c,a){return"string"==typeof c&&(c=b.trim(c))&&3<=c.length&&b.startsWith(c,"<")&&b.endsWith(c,">")?(a&&(a.getDOMNode&&(a=a[0]),a=a.ownerDocument||a),new f(c,j,a)):new f(h.query(c,a))},one:function(a,d){var e=f.all(a,d);return e.length?e.slice(0,1):null}});f.NodeType=l;f.KeyCode=i.KeyCode;f.Gesture=i.Gesture;
f.REPLACE_HISTORY=i.REPLACE_HISTORY;return f},{requires:["dom","event/dom"]});
KISSY.add("node/attach",function(b,h,i,j,f){function g(d,a,e){e.unshift(a);d=h[d].apply(h,e);return d===f?a:d}var k=j.prototype,l=b.makeArray;j.KeyCode=i.KeyCode;b.each("nodeName,isCustomDomain,getEmptyIframeSrc,equals,contains,index,scrollTop,scrollLeft,height,width,innerHeight,innerWidth,outerHeight,outerWidth,addStyleSheet,appendTo,prependTo,insertBefore,before,after,insertAfter,test,hasClass,addClass,removeClass,replaceClass,toggleClass,removeAttr,hasAttr,hasProp,scrollIntoView,remove,empty,removeData,hasData,unselectable,wrap,wrapAll,replaceWith,wrapInner,unwrap".split(","),function(d){k[d]=
function(){var a=l(arguments);return g(d,this,a)}});b.each("getWindow,getDocument,filter,first,last,parent,closest,next,prev,clone,siblings,contents,children".split(","),function(d){k[d]=function(){var a=l(arguments);a.unshift(this);a=h[d].apply(h,a);return a===f?this:a===null?null:new j(a)}});b.each({attr:1,text:0,css:1,style:1,val:0,prop:1,offset:0,html:0,outerHTML:0,outerHtml:0,data:1},function(d,a){k[a]=function(){var e;e=l(arguments);e[d]===f&&!b.isObject(e[0])?(e.unshift(this),e=h[a].apply(h,
e)):e=g(a,this,e);return e}});b.each("on,detach,fire,fireHandler,delegate,undelegate".split(","),function(d){k[d]=function(){var a=l(arguments);a.unshift(this);i[d].apply(i,a);return this}})},{requires:["dom","event/dom","./base"]});
KISSY.add("node/override",function(b,h,i){var j=i.prototype;b.each(["append","prepend","before","after"],function(b){j[b]=function(g){"string"==typeof g&&(g=h.create(g));if(g)h[b](g,this);return this}});b.each(["wrap","wrapAll","replaceWith","wrapInner"],function(b){var g=j[b];j[b]=function(b){"string"==typeof b&&(b=i.all(b,this[0].ownerDocument));return g.call(this,b)}})},{requires:["dom","./base"]});
KISSY.add("node/anim",function(b,h,i,j,f){function g(b,d,a){for(var e=[],c={},a=a||0;a<d;a++)e.push.apply(e,k[a]);for(a=0;a<e.length;a++)c[e[a]]=b;return c}var k=[["height","margin-top","margin-bottom","padding-top","padding-bottom"],["width","margin-left","margin-right","padding-left","padding-right"],["opacity"]];b.augment(j,{animate:function(g){var d=b.makeArray(arguments);b.each(this,function(a){var e=b.clone(d),c=e[0];c.to?(c.node=a,i(c).run()):i.apply(f,[a].concat(e)).run()});return this},stop:function(f,
d,a){b.each(this,function(b){i.stop(b,f,d,a)});return this},pause:function(f,d){b.each(this,function(a){i.pause(a,d)});return this},resume:function(f,d){b.each(this,function(a){i.resume(a,d)});return this},isRunning:function(){for(var b=0;b<this.length;b++)if(i.isRunning(this[b]))return!0;return!1},isPaused:function(){for(var b=0;b<this.length;b++)if(i.isPaused(this[b]))return!0;return!1}});b.each({show:g("show",3),hide:g("hide",3),toggle:g("toggle",3),fadeIn:g("show",3,2),fadeOut:g("hide",3,2),fadeToggle:g("toggle",
3,2),slideDown:g("show",1),slideUp:g("hide",1),slideToggle:g("toggle",1)},function(f,d){j.prototype[d]=function(a,e,c){if(h[d]&&!a)h[d](this);else b.each(this,function(b){i(b,f,a,c,e).run()});return this}})},{requires:["dom","anim","./base"]});KISSY.add("node",function(b,h){b.mix(b,{Node:h,NodeList:h,one:h.one,all:h.all});return h},{requires:["node/base","node/attach","node/override","node/anim"]});
