/*
Copyright 2013, KISSY UI Library v1.40dev
MIT Licensed
build time: Jul 3 19:20
*/
KISSY.add("event/dom/base/utils",function(f,d){var a="ksEventTargetId_"+f.now(),b=f.Env.host.document;return{simpleAdd:b&&b.addEventListener?function(a,b,d,f){a.addEventListener&&a.addEventListener(b,d,!!f)}:function(a,b,d){a.attachEvent&&a.attachEvent("on"+b,d)},simpleRemove:b&&b.removeEventListener?function(a,b,d,f){a.removeEventListener&&a.removeEventListener(b,d,!!f)}:function(a,b,d){a.detachEvent&&a.detachEvent("on"+b,d)},data:function(b,f){return d.data(b,a,f)},removeData:function(b){return d.removeData(b,
a)}}},{requires:["dom"]});KISSY.add("event/dom/base/special",function(){return{}});
KISSY.add("event/dom/base/observer",function(f,d,a){function b(a){b.superclass.constructor.apply(this,arguments)}f.extend(b,a.Observer,{keys:"fn,filter,data,context,originalType,groups,last".split(","),notifyInternal:function(a,b){var f,j,p=a.type,l;(l=this.originalType)?a.type=l:l=p;(f=d[l])&&f.handle?(f=f.handle(a,this,b))&&0<f.length&&(j=f[0]):j=this.simpleNotify(a,b);a.type=p;return j}});return b},{requires:["./special","event/base"]});
KISSY.add("event/dom/base/object",function(f,d,a){function b(){return j}function q(){return p}function m(c){var k=c.type;m.superclass.constructor.call(this);this.originalEvent=c;this.isDefaultPrevented=c.defaultPrevented||c.returnValue===p||c.getPreventDefault&&c.getPreventDefault()?b:q;var h=null,g,n,i=l.concat();f.each(o,function(c){return k.match(c.reg)?(i=i.concat(c.props),h=c.fix,!1):a});for(g=i.length;g;)n=i[--g],this[n]=c[n];this.target||(this.target=c.srcElement||t);3===this.target.nodeType&&
(this.target=this.target.parentNode);h&&h(this,c)}var t=f.Env.host.document,j=!0,p=!1,l="altKey,bubbles,cancelable,ctrlKey,currentTarget,eventPhase,metaKey,shiftKey,target,timeStamp,view,type".split(","),o=[{reg:/^key/,props:["char","charCode","key","keyCode","which"],fix:function(c,k){null==c.which&&(c.which=null!=k.charCode?k.charCode:k.keyCode);c.metaKey===a&&(c.metaKey=c.ctrlKey)}},{reg:/^touch/,props:["touches","changedTouches","targetTouches"]},{reg:/^gesturechange$/i,props:["rotation","scale"]},
{reg:/^mousewheel$/,props:[],fix:function(c,k){var h,g,l,i=k.wheelDelta,b=k.axis,o=k.wheelDeltaY,f=k.wheelDeltaX,d=k.detail;i&&(l=i/120);d&&(l=-(0==d%3?d/3:d));b!==a&&(b===e.HORIZONTAL_AXIS?(g=0,h=-1*l):b===e.VERTICAL_AXIS&&(h=0,g=l));o!==a&&(g=o/120);f!==a&&(h=-1*f/120);!h&&!g&&(g=l);h!==a&&(c.deltaX=h);g!==a&&(c.deltaY=g);l!==a&&(c.delta=l)}},{reg:/^mouse|contextmenu|click|mspointer/i,props:"buttons,clientX,clientY,button,offsetX,relatedTarget,which,fromElement,toElement,offsetY,pageX,pageY,screenX,screenY".split(","),
fix:function(c,l){var h,g,b=c.target,i=l.button;null==c.pageX&&null!=l.clientX&&(h=b.ownerDocument||t,g=h.documentElement,h=h.body,c.pageX=l.clientX+(g&&g.scrollLeft||h&&h.scrollLeft||0)-(g&&g.clientLeft||h&&h.clientLeft||0),c.pageY=l.clientY+(g&&g.scrollTop||h&&h.scrollTop||0)-(g&&g.clientTop||h&&h.clientTop||0));!c.which&&i!==a&&(c.which=i&1?1:i&2?3:i&4?2:0);!c.relatedTarget&&c.fromElement&&(c.relatedTarget=c.fromElement===b?c.toElement:c.fromElement);return c}}];f.extend(m,d.Object,{constructor:m,
preventDefault:function(){var a=this.originalEvent;a.preventDefault?a.preventDefault():a.returnValue=p;m.superclass.preventDefault.call(this)},stopPropagation:function(){var a=this.originalEvent;a.stopPropagation?a.stopPropagation():a.cancelBubble=j;m.superclass.stopPropagation.call(this)}});return m},{requires:["event/base"]});
KISSY.add("event/dom/base/observable",function(f,d,a,b,q,m,t){function j(a){f.mix(this,a);this.reset()}var p=t.Utils;f.extend(j,t.Observable,{setup:function(){var l=this.type,o=a[l]||{},c=this.currentTarget,k=b.data(c).handle;(!o.setup||!1===o.setup.call(c,l))&&b.simpleAdd(c,l,k)},constructor:j,reset:function(){j.superclass.reset.call(this);this.lastCount=this.delegateCount=0},notify:function(a){var b=a.target,c=a.type,k=this.currentTarget,h=this.observers,g=[],n,i,f=this.delegateCount||0,s,u;if(f&&
b.nodeType)for(;b!=k;){if(!0!==b.disabled||"click"!==c){var r={},m,j,q;s=[];for(i=0;i<f;i++)u=h[i],q=u.filter,j=q+"",m=r[j],void 0===m&&(m=r[j]=d.test(b,q)),m&&s.push(u);s.length&&g.push({currentTarget:b,currentTargetObservers:s})}b=b.parentNode||k}f<h.length&&g.push({currentTarget:k,currentTargetObservers:h.slice(f)});i=0;for(b=g.length;!a.isPropagationStopped()&&i<b;++i){c=g[i];s=c.currentTargetObservers;c=c.currentTarget;a.currentTarget=c;for(c=0;!a.isImmediatePropagationStopped()&&c<s.length;c++)k=
s[c],k=k.notify(a,this),!1!==n&&(n=k)}return n},fire:function(b,o){var b=b||{},c=""+this.type,k,h,g=a[c]||{};k=!1!==g.bubbles;var n=this.currentTarget;if(!(g.fire&&!1===g.fire.call(n,o))&&(b instanceof m||(h=b,b=new m({currentTarget:n,type:c,target:n}),f.mix(b,h)),!(g.preFire&&!1===g.preFire.call(n,b,o)))){var i=n,v=d.getWindow(i),s=v.document;h=[];g=0;do h.push(i),i=i.parentNode||i.ownerDocument||i===s&&v;while(!o&&i&&k);i=h[g];do b.currentTarget=i,(k=j.getDomEventObservable(i,c))&&k.notify(b),i=
h[++g];while(!o&&i&&!b.isPropagationStopped());if(!o&&!b.isDefaultPrevented()){try{n[c]&&!f.isWindow(n)&&(j.triggeredEvent=c,n[c]())}catch(u){}j.triggeredEvent=""}}},on:function(b){var f=this.observers,c=a[this.type]||{},b=b instanceof q?b:new q(b);-1==this.findObserver(b)&&(b.filter?(f.splice(this.delegateCount,0,b),this.delegateCount++):b.last?(f.push(b),this.lastCount++):f.splice(f.length-this.lastCount,0,b),c.add&&c.add.call(this.currentTarget,b))},detach:function(b){var f,c=a[this.type]||{},
k="filter"in b,h=b.filter,g=b.context,n=b.fn,i=this.currentTarget,d=this.observers,b=b.groups;if(d.length){b&&(f=p.getGroupsRe(b));var s,u,r,m,j=d.length;if(n||k||f){g=g||i;s=b=0;for(u=[];b<j;++b)r=d[b],m=r.context||i,g!=m||n&&n!=r.fn||k&&(h&&h!=r.filter||!h&&!r.filter)||f&&!r.groups.match(f)?u[s++]=r:(r.filter&&this.delegateCount&&this.delegateCount--,r.last&&this.lastCount&&this.lastCount--,c.remove&&c.remove.call(i,r));this.observers=u}else this.reset();this.checkMemory()}},checkMemory:function(){var d=
this.type,m,c,k=a[d]||{},h=this.currentTarget,g=b.data(h);if(g&&(m=g.observables,this.hasObserver()||(c=g.handle,(!k.tearDown||!1===k.tearDown.call(h,d))&&b.simpleRemove(h,d,c),delete m[d]),f.isEmptyObject(m)))g.handle=null,b.removeData(h)}});j.triggeredEvent="";j.getDomEventObservable=function(a,f){var c=b.data(a),k;c&&(k=c.observables);return k?k[f]:null};j.getDomEventObservablesHolder=function(a,f){var c=b.data(a);!c&&f&&b.data(a,c={});return c};return j},{requires:"dom,./special,./utils,./observer,./object,event/base".split(",")});
KISSY.add("event/dom/base/dom-event",function(f,d,a,b,q,m,t){function j(a,b){var c=q[b]||{},f;if(!a.originalType&&(f=c.typeFix))a.originalType=b,b=f;return b}function p(a,b,c){var d,i,v,c=f.merge(c),b=j(c,b);d=m.getDomEventObservablesHolder(a,1);if(!(v=d.handle))v=d.handle=function(a){var b=a.type,c=v.currentTarget;if(!(m.triggeredEvent==b||"undefined"==typeof KISSY))if(b=m.getDomEventObservable(c,b))return a.currentTarget=c,a=new t(a),b.notify(a)},v.currentTarget=a;if(!(i=d.observables))i=d.observables=
{};d=i[b];d||(d=i[b]=new m({type:b,currentTarget:a}),d.setup());d.on(c);a=null}function l(a,b,c){var c=f.merge(c),b=j(c,b),a=m.getDomEventObservablesHolder(a),d=(a||{}).observables;if(a&&d)if(b)(b=d[b])&&b.detach(c);else for(b in d)d[b].detach(c)}var o=d.Utils,c={};f.mix(c,{on:function(a,c,g,d){a=b.query(a);o.batchForType(function(a,b,c,d){for(var c=o.normalizeParam(b,c,d),g,b=c.type,d=a.length-1;0<=d;d--)g=a[d],p(g,b,c)},1,a,c,g,d);return a},detach:function(a,c,d,f){a=b.query(a);o.batchForType(function(a,
b,c,d){for(var c=o.normalizeParam(b,c,d),g,f,b=c.type,d=a.length-1;0<=d;d--)if(g=a[d],l(g,b,c),c.deep&&g.getElementsByTagName){f=g.getElementsByTagName("*");for(g=f.length-1;0<=g;g--)l(f[g],b,c)}},1,a,c,d,f);return a},delegate:function(a,b,d,f,i){return c.on(a,b,{fn:f,context:i,filter:d})},undelegate:function(a,b,d,f,i){return c.detach(a,b,{fn:f,context:i,filter:d})},fire:function(a,c,d,f){var i=void 0,d=d||{};d.synthetic=1;o.splitAndRun(c,function(c){var h,j,l;o.fillGroupsForEvent(c,d);c=d.type;
if((j=q[c])&&j.typeFix)c=j.typeFix;a=b.query(a);for(j=a.length-1;0<=j;j--)h=a[j],l=m.getDomEventObservable(h,c),!f&&!l&&(l=new m({type:c,currentTarget:h})),l&&(h=l.fire(d,f),!1!==i&&(i=h))});return i},fireHandler:function(a,b,d){return c.fire(a,b,d,1)},clone:function(b,c){var d;if(d=m.getDomEventObservablesHolder(b)){var j=a.data(b);j&&j===a.data(c)&&a.removeData(c);f.each(d.observables,function(a,b){f.each(a.observers,function(a){p(c,b,a)})})}}});return c},{requires:"event/base,./utils,dom,./special,./observable,./object".split(",")});
KISSY.add("event/dom/base/key-codes",function(f){var d=f.UA,a={MAC_ENTER:3,BACKSPACE:8,TAB:9,NUM_CENTER:12,ENTER:13,SHIFT:16,CTRL:17,ALT:18,PAUSE:19,CAPS_LOCK:20,ESC:27,SPACE:32,PAGE_UP:33,PAGE_DOWN:34,END:35,HOME:36,LEFT:37,UP:38,RIGHT:39,DOWN:40,PRINT_SCREEN:44,INSERT:45,DELETE:46,ZERO:48,ONE:49,TWO:50,THREE:51,FOUR:52,FIVE:53,SIX:54,SEVEN:55,EIGHT:56,NINE:57,QUESTION_MARK:63,A:65,B:66,C:67,D:68,E:69,F:70,G:71,H:72,I:73,J:74,K:75,L:76,M:77,N:78,O:79,P:80,Q:81,R:82,S:83,T:84,U:85,V:86,W:87,X:88,
Y:89,Z:90,META:91,WIN_KEY_RIGHT:92,CONTEXT_MENU:93,NUM_ZERO:96,NUM_ONE:97,NUM_TWO:98,NUM_THREE:99,NUM_FOUR:100,NUM_FIVE:101,NUM_SIX:102,NUM_SEVEN:103,NUM_EIGHT:104,NUM_NINE:105,NUM_MULTIPLY:106,NUM_PLUS:107,NUM_MINUS:109,NUM_PERIOD:110,NUM_DIVISION:111,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,NUMLOCK:144,SEMICOLON:186,DASH:189,EQUALS:187,COMMA:188,PERIOD:190,SLASH:191,APOSTROPHE:192,SINGLE_QUOTE:222,OPEN_SQUARE_BRACKET:219,BACKSLASH:220,CLOSE_SQUARE_BRACKET:221,
WIN_KEY:224,MAC_FF_META:224,WIN_IME:229,isTextModifyingKeyEvent:function(b){if(b.altKey&&!b.ctrlKey||b.metaKey||b.keyCode>=a.F1&&b.keyCode<=a.F12)return!1;switch(b.keyCode){case a.ALT:case a.CAPS_LOCK:case a.CONTEXT_MENU:case a.CTRL:case a.DOWN:case a.END:case a.ESC:case a.HOME:case a.INSERT:case a.LEFT:case a.MAC_FF_META:case a.META:case a.NUMLOCK:case a.NUM_CENTER:case a.PAGE_DOWN:case a.PAGE_UP:case a.PAUSE:case a.PRINT_SCREEN:case a.RIGHT:case a.SHIFT:case a.UP:case a.WIN_KEY:case a.WIN_KEY_RIGHT:return!1;
default:return!0}},isCharacterKey:function(b){if(b>=a.ZERO&&b<=a.NINE||b>=a.NUM_ZERO&&b<=a.NUM_MULTIPLY||b>=a.A&&b<=a.Z||d.webkit&&0==b)return!0;switch(b){case a.SPACE:case a.QUESTION_MARK:case a.NUM_PLUS:case a.NUM_MINUS:case a.NUM_PERIOD:case a.NUM_DIVISION:case a.SEMICOLON:case a.DASH:case a.EQUALS:case a.COMMA:case a.PERIOD:case a.SLASH:case a.APOSTROPHE:case a.SINGLE_QUOTE:case a.OPEN_SQUARE_BRACKET:case a.BACKSLASH:case a.CLOSE_SQUARE_BRACKET:return!0;default:return!1}}};return a});
KISSY.add("event/dom/base/gesture",function(){return{start:"mousedown",move:"mousemove",end:"mouseup",tap:"click",doubleTap:"dblclick"}});
KISSY.add("event/dom/base/special-events",function(f,d,a){var b=b;return f.mix(a,{mousewheel:{typeFix:f.UA.gecko?"DOMMouseScroll":"mousewheel"},load:{bubbles:!1},click:{fire:function(a){return!a&&"checkbox"===""+this.type&&this.click&&"input"==this.nodeName.toLowerCase()?(this.click(),!1):b}},focus:{bubbles:!1,preFire:function(a,b){b||d.fire(this,"focusin")},fire:function(a){return!a&&this.ownerDocument&&this!==this.ownerDocument.activeElement&&this.focus?(this.focus(),!1):b}},blur:{bubbles:!1,preFire:function(a,
b){b||d.fire(this,"focusout")},fire:function(a){return!a&&this.ownerDocument&&this===this.ownerDocument.activeElement&&this.blur?(this.blur(),!1):b}}})},{requires:["./dom-event","./special"]});
KISSY.add("event/dom/base/mouseenter",function(f,d,a){f.each([{name:"mouseenter",fix:"mouseover"},{name:"mouseleave",fix:"mouseout"}],function(b){a[b.name]={typeFix:b.fix,handle:function(a,b,f){var j=a.currentTarget,p=a.relatedTarget;if(!p||p!==j&&!d.contains(j,p))return[b.simpleNotify(a,f)]}}})},{requires:["dom","./special"]});
KISSY.add("event/dom/base/valuechange",function(f,d,a,b){function q(b){if(a.hasData(b,g)){var c=a.data(b,g);clearTimeout(c);a.removeData(b,g)}}function m(a){q(a.target)}function t(b){var f=b.value,g=a.data(b,h);f!==g&&(d.fireHandler(b,c,{prevVal:g,newVal:f}),a.data(b,h,f))}function j(b){a.hasData(b,g)||a.data(b,g,setTimeout(function(){t(b);a.data(b,g,setTimeout(arguments.callee,n))},n))}function p(b){var c=b.target;"focus"==b.type&&a.data(c,h,c.value);j(c)}function l(a){t(a.target)}function o(b){a.removeData(b,
h);q(b);d.detach(b,"blur",m);d.detach(b,"webkitspeechchange",l);d.detach(b,"mousedown keyup keydown focus",p)}var c="valuechange",k=a.nodeName,h="event/valuechange/history",g="event/valuechange/poll",n=50;b[c]={setup:function(){var a=k(this);if("input"==a||"textarea"==a)o(this),d.on(this,"blur",m),d.on(this,"webkitspeechchange",l),d.on(this,"mousedown keyup keydown focus",p)},tearDown:function(){o(this)}};return d},{requires:["./dom-event","dom","./special"]});
KISSY.add("event/dom/base",function(f,d,a,b,q){return f.merge({add:d.on,remove:d.detach,KeyCode:a,Gesture:b,Special:q},d)},{requires:"./base/dom-event,./base/key-codes,./base/gesture,./base/special-events,./base/mouseenter,./base/valuechange".split(",")});
/*
Copyright 2013, KISSY UI Library v1.40dev
MIT Licensed
build time: Jul 3 19:20
*/
KISSY.add("event/dom/focusin",function(d,e){var g=e.Special;d.each([{name:"focusin",fix:"focus"},{name:"focusout",fix:"blur"}],function(c){function f(a){return e.fire(a.target,c.name)}var b=d.guid("attaches_"+d.now()+"_");g[c.name]={setup:function(){var a=this.ownerDocument||this;b in a||(a[b]=0);a[b]+=1;1===a[b]&&a.addEventListener(c.fix,f,!0)},tearDown:function(){var a=this.ownerDocument||this;a[b]-=1;0===a[b]&&a.removeEventListener(c.fix,f,!0)}}});return e},{requires:["event/dom/base"]});
/*
Copyright 2013, KISSY UI Library v1.40dev
MIT Licensed
build time: Jul 3 19:20
*/
KISSY.add("event/dom/base/utils",function(f,d){var a="ksEventTargetId_"+f.now(),b=f.Env.host.document;return{simpleAdd:b&&b.addEventListener?function(a,b,d,f){a.addEventListener&&a.addEventListener(b,d,!!f)}:function(a,b,d){a.attachEvent&&a.attachEvent("on"+b,d)},simpleRemove:b&&b.removeEventListener?function(a,b,d,f){a.removeEventListener&&a.removeEventListener(b,d,!!f)}:function(a,b,d){a.detachEvent&&a.detachEvent("on"+b,d)},data:function(b,f){return d.data(b,a,f)},removeData:function(b){return d.removeData(b,
a)}}},{requires:["dom"]});KISSY.add("event/dom/base/special",function(){return{}});
KISSY.add("event/dom/base/observer",function(f,d,a){function b(a){b.superclass.constructor.apply(this,arguments)}f.extend(b,a.Observer,{keys:"fn,filter,data,context,originalType,groups,last".split(","),notifyInternal:function(a,b){var f,j,p=a.type,l;(l=this.originalType)?a.type=l:l=p;(f=d[l])&&f.handle?(f=f.handle(a,this,b))&&0<f.length&&(j=f[0]):j=this.simpleNotify(a,b);a.type=p;return j}});return b},{requires:["./special","event/base"]});
KISSY.add("event/dom/base/object",function(f,d,a){function b(){return j}function q(){return p}function m(c){var k=c.type;m.superclass.constructor.call(this);this.originalEvent=c;this.isDefaultPrevented=c.defaultPrevented||c.returnValue===p||c.getPreventDefault&&c.getPreventDefault()?b:q;var h=null,g,n,i=l.concat();f.each(o,function(c){return k.match(c.reg)?(i=i.concat(c.props),h=c.fix,!1):a});for(g=i.length;g;)n=i[--g],this[n]=c[n];this.target||(this.target=c.srcElement||t);3===this.target.nodeType&&
(this.target=this.target.parentNode);h&&h(this,c)}var t=f.Env.host.document,j=!0,p=!1,l="altKey,bubbles,cancelable,ctrlKey,currentTarget,eventPhase,metaKey,shiftKey,target,timeStamp,view,type".split(","),o=[{reg:/^key/,props:["char","charCode","key","keyCode","which"],fix:function(c,k){null==c.which&&(c.which=null!=k.charCode?k.charCode:k.keyCode);c.metaKey===a&&(c.metaKey=c.ctrlKey)}},{reg:/^touch/,props:["touches","changedTouches","targetTouches"]},{reg:/^gesturechange$/i,props:["rotation","scale"]},
{reg:/^mousewheel$/,props:[],fix:function(c,k){var h,g,l,i=k.wheelDelta,b=k.axis,o=k.wheelDeltaY,f=k.wheelDeltaX,d=k.detail;i&&(l=i/120);d&&(l=-(0==d%3?d/3:d));b!==a&&(b===e.HORIZONTAL_AXIS?(g=0,h=-1*l):b===e.VERTICAL_AXIS&&(h=0,g=l));o!==a&&(g=o/120);f!==a&&(h=-1*f/120);!h&&!g&&(g=l);h!==a&&(c.deltaX=h);g!==a&&(c.deltaY=g);l!==a&&(c.delta=l)}},{reg:/^mouse|contextmenu|click|mspointer/i,props:"buttons,clientX,clientY,button,offsetX,relatedTarget,which,fromElement,toElement,offsetY,pageX,pageY,screenX,screenY".split(","),
fix:function(c,l){var h,g,b=c.target,i=l.button;null==c.pageX&&null!=l.clientX&&(h=b.ownerDocument||t,g=h.documentElement,h=h.body,c.pageX=l.clientX+(g&&g.scrollLeft||h&&h.scrollLeft||0)-(g&&g.clientLeft||h&&h.clientLeft||0),c.pageY=l.clientY+(g&&g.scrollTop||h&&h.scrollTop||0)-(g&&g.clientTop||h&&h.clientTop||0));!c.which&&i!==a&&(c.which=i&1?1:i&2?3:i&4?2:0);!c.relatedTarget&&c.fromElement&&(c.relatedTarget=c.fromElement===b?c.toElement:c.fromElement);return c}}];f.extend(m,d.Object,{constructor:m,
preventDefault:function(){var a=this.originalEvent;a.preventDefault?a.preventDefault():a.returnValue=p;m.superclass.preventDefault.call(this)},stopPropagation:function(){var a=this.originalEvent;a.stopPropagation?a.stopPropagation():a.cancelBubble=j;m.superclass.stopPropagation.call(this)}});return m},{requires:["event/base"]});
KISSY.add("event/dom/base/observable",function(f,d,a,b,q,m,t){function j(a){f.mix(this,a);this.reset()}var p=t.Utils;f.extend(j,t.Observable,{setup:function(){var l=this.type,o=a[l]||{},c=this.currentTarget,k=b.data(c).handle;(!o.setup||!1===o.setup.call(c,l))&&b.simpleAdd(c,l,k)},constructor:j,reset:function(){j.superclass.reset.call(this);this.lastCount=this.delegateCount=0},notify:function(a){var b=a.target,c=a.type,k=this.currentTarget,h=this.observers,g=[],n,i,f=this.delegateCount||0,s,u;if(f&&
b.nodeType)for(;b!=k;){if(!0!==b.disabled||"click"!==c){var r={},m,j,q;s=[];for(i=0;i<f;i++)u=h[i],q=u.filter,j=q+"",m=r[j],void 0===m&&(m=r[j]=d.test(b,q)),m&&s.push(u);s.length&&g.push({currentTarget:b,currentTargetObservers:s})}b=b.parentNode||k}f<h.length&&g.push({currentTarget:k,currentTargetObservers:h.slice(f)});i=0;for(b=g.length;!a.isPropagationStopped()&&i<b;++i){c=g[i];s=c.currentTargetObservers;c=c.currentTarget;a.currentTarget=c;for(c=0;!a.isImmediatePropagationStopped()&&c<s.length;c++)k=
s[c],k=k.notify(a,this),!1!==n&&(n=k)}return n},fire:function(b,o){var b=b||{},c=""+this.type,k,h,g=a[c]||{};k=!1!==g.bubbles;var n=this.currentTarget;if(!(g.fire&&!1===g.fire.call(n,o))&&(b instanceof m||(h=b,b=new m({currentTarget:n,type:c,target:n}),f.mix(b,h)),!(g.preFire&&!1===g.preFire.call(n,b,o)))){var i=n,v=d.getWindow(i),s=v.document;h=[];g=0;do h.push(i),i=i.parentNode||i.ownerDocument||i===s&&v;while(!o&&i&&k);i=h[g];do b.currentTarget=i,(k=j.getDomEventObservable(i,c))&&k.notify(b),i=
h[++g];while(!o&&i&&!b.isPropagationStopped());if(!o&&!b.isDefaultPrevented()){try{n[c]&&!f.isWindow(n)&&(j.triggeredEvent=c,n[c]())}catch(u){}j.triggeredEvent=""}}},on:function(b){var f=this.observers,c=a[this.type]||{},b=b instanceof q?b:new q(b);-1==this.findObserver(b)&&(b.filter?(f.splice(this.delegateCount,0,b),this.delegateCount++):b.last?(f.push(b),this.lastCount++):f.splice(f.length-this.lastCount,0,b),c.add&&c.add.call(this.currentTarget,b))},detach:function(b){var f,c=a[this.type]||{},
k="filter"in b,h=b.filter,g=b.context,n=b.fn,i=this.currentTarget,d=this.observers,b=b.groups;if(d.length){b&&(f=p.getGroupsRe(b));var s,u,r,m,j=d.length;if(n||k||f){g=g||i;s=b=0;for(u=[];b<j;++b)r=d[b],m=r.context||i,g!=m||n&&n!=r.fn||k&&(h&&h!=r.filter||!h&&!r.filter)||f&&!r.groups.match(f)?u[s++]=r:(r.filter&&this.delegateCount&&this.delegateCount--,r.last&&this.lastCount&&this.lastCount--,c.remove&&c.remove.call(i,r));this.observers=u}else this.reset();this.checkMemory()}},checkMemory:function(){var d=
this.type,m,c,k=a[d]||{},h=this.currentTarget,g=b.data(h);if(g&&(m=g.observables,this.hasObserver()||(c=g.handle,(!k.tearDown||!1===k.tearDown.call(h,d))&&b.simpleRemove(h,d,c),delete m[d]),f.isEmptyObject(m)))g.handle=null,b.removeData(h)}});j.triggeredEvent="";j.getDomEventObservable=function(a,f){var c=b.data(a),k;c&&(k=c.observables);return k?k[f]:null};j.getDomEventObservablesHolder=function(a,f){var c=b.data(a);!c&&f&&b.data(a,c={});return c};return j},{requires:"dom,./special,./utils,./observer,./object,event/base".split(",")});
KISSY.add("event/dom/base/dom-event",function(f,d,a,b,q,m,t){function j(a,b){var c=q[b]||{},f;if(!a.originalType&&(f=c.typeFix))a.originalType=b,b=f;return b}function p(a,b,c){var d,i,v,c=f.merge(c),b=j(c,b);d=m.getDomEventObservablesHolder(a,1);if(!(v=d.handle))v=d.handle=function(a){var b=a.type,c=v.currentTarget;if(!(m.triggeredEvent==b||"undefined"==typeof KISSY))if(b=m.getDomEventObservable(c,b))return a.currentTarget=c,a=new t(a),b.notify(a)},v.currentTarget=a;if(!(i=d.observables))i=d.observables=
{};d=i[b];d||(d=i[b]=new m({type:b,currentTarget:a}),d.setup());d.on(c);a=null}function l(a,b,c){var c=f.merge(c),b=j(c,b),a=m.getDomEventObservablesHolder(a),d=(a||{}).observables;if(a&&d)if(b)(b=d[b])&&b.detach(c);else for(b in d)d[b].detach(c)}var o=d.Utils,c={};f.mix(c,{on:function(a,c,g,d){a=b.query(a);o.batchForType(function(a,b,c,d){for(var c=o.normalizeParam(b,c,d),g,b=c.type,d=a.length-1;0<=d;d--)g=a[d],p(g,b,c)},1,a,c,g,d);return a},detach:function(a,c,d,f){a=b.query(a);o.batchForType(function(a,
b,c,d){for(var c=o.normalizeParam(b,c,d),g,f,b=c.type,d=a.length-1;0<=d;d--)if(g=a[d],l(g,b,c),c.deep&&g.getElementsByTagName){f=g.getElementsByTagName("*");for(g=f.length-1;0<=g;g--)l(f[g],b,c)}},1,a,c,d,f);return a},delegate:function(a,b,d,f,i){return c.on(a,b,{fn:f,context:i,filter:d})},undelegate:function(a,b,d,f,i){return c.detach(a,b,{fn:f,context:i,filter:d})},fire:function(a,c,d,f){var i=void 0,d=d||{};d.synthetic=1;o.splitAndRun(c,function(c){var h,j,l;o.fillGroupsForEvent(c,d);c=d.type;
if((j=q[c])&&j.typeFix)c=j.typeFix;a=b.query(a);for(j=a.length-1;0<=j;j--)h=a[j],l=m.getDomEventObservable(h,c),!f&&!l&&(l=new m({type:c,currentTarget:h})),l&&(h=l.fire(d,f),!1!==i&&(i=h))});return i},fireHandler:function(a,b,d){return c.fire(a,b,d,1)},clone:function(b,c){var d;if(d=m.getDomEventObservablesHolder(b)){var j=a.data(b);j&&j===a.data(c)&&a.removeData(c);f.each(d.observables,function(a,b){f.each(a.observers,function(a){p(c,b,a)})})}}});return c},{requires:"event/base,./utils,dom,./special,./observable,./object".split(",")});
KISSY.add("event/dom/base/key-codes",function(f){var d=f.UA,a={MAC_ENTER:3,BACKSPACE:8,TAB:9,NUM_CENTER:12,ENTER:13,SHIFT:16,CTRL:17,ALT:18,PAUSE:19,CAPS_LOCK:20,ESC:27,SPACE:32,PAGE_UP:33,PAGE_DOWN:34,END:35,HOME:36,LEFT:37,UP:38,RIGHT:39,DOWN:40,PRINT_SCREEN:44,INSERT:45,DELETE:46,ZERO:48,ONE:49,TWO:50,THREE:51,FOUR:52,FIVE:53,SIX:54,SEVEN:55,EIGHT:56,NINE:57,QUESTION_MARK:63,A:65,B:66,C:67,D:68,E:69,F:70,G:71,H:72,I:73,J:74,K:75,L:76,M:77,N:78,O:79,P:80,Q:81,R:82,S:83,T:84,U:85,V:86,W:87,X:88,
Y:89,Z:90,META:91,WIN_KEY_RIGHT:92,CONTEXT_MENU:93,NUM_ZERO:96,NUM_ONE:97,NUM_TWO:98,NUM_THREE:99,NUM_FOUR:100,NUM_FIVE:101,NUM_SIX:102,NUM_SEVEN:103,NUM_EIGHT:104,NUM_NINE:105,NUM_MULTIPLY:106,NUM_PLUS:107,NUM_MINUS:109,NUM_PERIOD:110,NUM_DIVISION:111,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,NUMLOCK:144,SEMICOLON:186,DASH:189,EQUALS:187,COMMA:188,PERIOD:190,SLASH:191,APOSTROPHE:192,SINGLE_QUOTE:222,OPEN_SQUARE_BRACKET:219,BACKSLASH:220,CLOSE_SQUARE_BRACKET:221,
WIN_KEY:224,MAC_FF_META:224,WIN_IME:229,isTextModifyingKeyEvent:function(b){if(b.altKey&&!b.ctrlKey||b.metaKey||b.keyCode>=a.F1&&b.keyCode<=a.F12)return!1;switch(b.keyCode){case a.ALT:case a.CAPS_LOCK:case a.CONTEXT_MENU:case a.CTRL:case a.DOWN:case a.END:case a.ESC:case a.HOME:case a.INSERT:case a.LEFT:case a.MAC_FF_META:case a.META:case a.NUMLOCK:case a.NUM_CENTER:case a.PAGE_DOWN:case a.PAGE_UP:case a.PAUSE:case a.PRINT_SCREEN:case a.RIGHT:case a.SHIFT:case a.UP:case a.WIN_KEY:case a.WIN_KEY_RIGHT:return!1;
default:return!0}},isCharacterKey:function(b){if(b>=a.ZERO&&b<=a.NINE||b>=a.NUM_ZERO&&b<=a.NUM_MULTIPLY||b>=a.A&&b<=a.Z||d.webkit&&0==b)return!0;switch(b){case a.SPACE:case a.QUESTION_MARK:case a.NUM_PLUS:case a.NUM_MINUS:case a.NUM_PERIOD:case a.NUM_DIVISION:case a.SEMICOLON:case a.DASH:case a.EQUALS:case a.COMMA:case a.PERIOD:case a.SLASH:case a.APOSTROPHE:case a.SINGLE_QUOTE:case a.OPEN_SQUARE_BRACKET:case a.BACKSLASH:case a.CLOSE_SQUARE_BRACKET:return!0;default:return!1}}};return a});
KISSY.add("event/dom/base/gesture",function(){return{start:"mousedown",move:"mousemove",end:"mouseup",tap:"click",doubleTap:"dblclick"}});
KISSY.add("event/dom/base/special-events",function(f,d,a){var b=b;return f.mix(a,{mousewheel:{typeFix:f.UA.gecko?"DOMMouseScroll":"mousewheel"},load:{bubbles:!1},click:{fire:function(a){return!a&&"checkbox"===""+this.type&&this.click&&"input"==this.nodeName.toLowerCase()?(this.click(),!1):b}},focus:{bubbles:!1,preFire:function(a,b){b||d.fire(this,"focusin")},fire:function(a){return!a&&this.ownerDocument&&this!==this.ownerDocument.activeElement&&this.focus?(this.focus(),!1):b}},blur:{bubbles:!1,preFire:function(a,
b){b||d.fire(this,"focusout")},fire:function(a){return!a&&this.ownerDocument&&this===this.ownerDocument.activeElement&&this.blur?(this.blur(),!1):b}}})},{requires:["./dom-event","./special"]});
KISSY.add("event/dom/base/mouseenter",function(f,d,a){f.each([{name:"mouseenter",fix:"mouseover"},{name:"mouseleave",fix:"mouseout"}],function(b){a[b.name]={typeFix:b.fix,handle:function(a,b,f){var j=a.currentTarget,p=a.relatedTarget;if(!p||p!==j&&!d.contains(j,p))return[b.simpleNotify(a,f)]}}})},{requires:["dom","./special"]});
KISSY.add("event/dom/base/valuechange",function(f,d,a,b){function q(b){if(a.hasData(b,g)){var c=a.data(b,g);clearTimeout(c);a.removeData(b,g)}}function m(a){q(a.target)}function t(b){var f=b.value,g=a.data(b,h);f!==g&&(d.fireHandler(b,c,{prevVal:g,newVal:f}),a.data(b,h,f))}function j(b){a.hasData(b,g)||a.data(b,g,setTimeout(function(){t(b);a.data(b,g,setTimeout(arguments.callee,n))},n))}function p(b){var c=b.target;"focus"==b.type&&a.data(c,h,c.value);j(c)}function l(a){t(a.target)}function o(b){a.removeData(b,
h);q(b);d.detach(b,"blur",m);d.detach(b,"webkitspeechchange",l);d.detach(b,"mousedown keyup keydown focus",p)}var c="valuechange",k=a.nodeName,h="event/valuechange/history",g="event/valuechange/poll",n=50;b[c]={setup:function(){var a=k(this);if("input"==a||"textarea"==a)o(this),d.on(this,"blur",m),d.on(this,"webkitspeechchange",l),d.on(this,"mousedown keyup keydown focus",p)},tearDown:function(){o(this)}};return d},{requires:["./dom-event","dom","./special"]});
KISSY.add("event/dom/base",function(f,d,a,b,q){return f.merge({add:d.on,remove:d.detach,KeyCode:a,Gesture:b,Special:q},d)},{requires:"./base/dom-event,./base/key-codes,./base/gesture,./base/special-events,./base/mouseenter,./base/valuechange".split(",")});
/*
Copyright 2013, KISSY UI Library v1.40dev
MIT Licensed
build time: Jul 3 19:20
*/
KISSY.add("event/dom/shake",function(d,k,f){function l(a){var b=a.accelerationIncludingGravity,a=b.x,d=b.y,b=b.z,g;c!==f&&(g=n(h(a-c),h(d-i),h(b-j)),g>o&&m(),g>p&&(e=1));c=a;i=d;j=b}var q=k.Special,o=5,p=20,e=0,c,i,j,n=Math.max,h=Math.abs,a=d.Env.host,m=d.buffer(function(){e&&(k.fireHandler(a,"shake",{accelerationIncludingGravity:{x:c,y:i,z:j}}),c=f,e=0)},250);q.shake={setup:function(){this==a&&a.addEventListener("devicemotion",l,!1)},tearDown:function(){this==a&&(m.stop(),c=f,e=0,a.removeEventListener("devicemotion",
l,!1))}}},{requires:["event/dom/base"]});
/*
Copyright 2013, KISSY UI Library v1.40dev
MIT Licensed
build time: Jul 3 13:48
*/
KISSY.add("anim/base/queue",function(c,e){function h(b,d,a){var d=d||g,c,j=e.data(b,i);!j&&!a&&e.data(b,i,j={});j&&(c=j[d],!c&&!a&&(c=j[d]=[]));return c}var i=c.guid("ks-queue-"+c.now()+"-"),g=c.guid("ks-queue-"+c.now()+"-"),f;return f={queueCollectionKey:i,queue:function(b,c,a){b=h(b,c);b.push(a);return b},remove:function(b,d,a){var e=h(b,d,1);e&&(a=c.indexOf(a,e),-1<a&&e.splice(a,1));e&&!e.length&&f.clearQueue(b,d);return e},clearQueues:function(b){e.removeData(b,i)},clearQueue:function(b,d){var d=
d||g,a=e.data(b,i);a&&delete a[d];c.isEmptyObject(a)&&e.removeData(b,i)},dequeue:function(b,c){var a=h(b,c,1);a&&(a.shift(),a.length||f.clearQueue(b,c));return a}}},{requires:["dom"]});
KISSY.add("anim/base/utils",function(c,e,h,i){var g=c.guid("ks-anim-unqueued-"+c.now()+"-"),f=c.guid("ks-anim-paused-"+c.now()+"-");return{saveRunningAnim:function(b){var d=b.node,a=e.data(d,g);a||e.data(d,g,a={});a[c.stamp(b)]=b},removeRunningAnim:function(b){var d=b.node,a=e.data(d,g);a&&(delete a[c.stamp(b)],c.isEmptyObject(a)&&e.removeData(d,g))},isAnimPaused:function(b){var d=e.data(b.node,f);return d?!!d[c.stamp(b)]:0},removePausedAnim:function(b){var d=b.node,a=e.data(d,f);a&&(delete a[c.stamp(b)],
c.isEmptyObject(a)&&e.removeData(d,f))},savePausedAnim:function(b){var d=b.node,a=e.data(d,f);a||e.data(d,f,a={});a[c.stamp(b)]=b},isAnimRunning:function(b){var d=e.data(b.node,g);return d?!!d[c.stamp(b)]:0},isElPaused:function(b){return(b=e.data(b,f))&&!c.isEmptyObject(b)},isElRunning:function(b){return(b=e.data(b,g))&&!c.isEmptyObject(b)},pauseOrResumeQueue:function(b,d,a){b=e.data(b,"resume"==a?f:g);b=c.merge(b);c.each(b,function(b){if(d===i||b.config.queue==d)b[a]()})},stopEl:function(b,d,a,f){a&&
(f===i?h.clearQueues(b):!1!==f&&h.clearQueue(b,f));b=e.data(b,g);b=c.merge(b);c.each(b,function(a){(f===i||a.config.queue==f)&&a.stop(d)})}}},{requires:["dom","./queue"]});
KISSY.add("anim/base",function(c,e,h,i,g){function f(a){this.config=a;this.node=this.el=e.get(a.node);this._backupProps={};this._propsData={};if(a=a.complete)this.on("complete",a)}var b=e.NodeType,d={toggle:1,hide:1,show:1};c.augment(f,i.Target,{prepareFx:function(){},runInternal:function(){var a=this,f=a.config,j=a.node,g,i=a._backupProps,m=a._propsData,k=f.to,o=f.delay||0,p=f.duration;h.saveRunningAnim(a);if(!1===a.fire("beforeStart"))a.stop(0);else{c.each(k,function(a,b){c.isPlainObject(a)||(a=
{value:a});m[b]=c.mix({delay:o,easing:f.easing,frame:f.frame,duration:p},a)});if(j.nodeType==b.ELEMENT_NODE){if(k.width||k.height)k=j.style,c.mix(i,{overflow:k.overflow,"overflow-x":k.overflowX,"overflow-y":k.overflowY}),k.overflow="hidden","inline"===e.css(j,"display")&&"none"===e.css(j,"float")&&(c.UA.ie?k.zoom=1:k.display="inline-block");var n,l;l="none"===e.css(j,"display");c.each(m,function(b,c){g=b.value;if(d[g]){if("hide"==g&&l||"show"==g&&!l)return a.stop(1),n=!1;i[c]=e.style(j,c);"toggle"==
g?g=l?"show":"hide":"hide"==g?(b.value=0,i.display="none"):(b.value=e.css(j,c),e.css(j,c,0),e.show(j))}});if(!1===n)return}a.startTime=c.now();a.prepareFx();a.doStart()}},isRunning:function(){return h.isAnimRunning(this)},isPaused:function(){return h.isAnimPaused(this)},pause:function(){this.isRunning()&&(this._runTime=c.now()-this.startTime,h.removeRunningAnim(this),h.savePausedAnim(this),this.doStop());return this},doStop:function(){},doStart:function(){},resume:function(){this.isPaused()&&(this.startTime=
c.now()-this._runTime,h.removePausedAnim(this),h.saveRunningAnim(this),this.beforeResume(),this.doStart());return this},beforeResume:function(){},run:function(){var a;a=this.config.queue;!1===a?this.runInternal():(a=g.queue(this.node,a,this),1==a.length&&this.runInternal());return this},stop:function(a){var b=this.node,d=this.config.queue;if(!this.isRunning()&&!this.isPaused())return!1!==d&&g.remove(b,d,this),this;h.removeRunningAnim(this);h.removePausedAnim(this);this.doStop(a);if(a){var f;c.isEmptyObject(f=
this._backupProps)||e.css(this.node,f);this.fire("complete")}!1!==d&&(a=g.dequeue(b,d))&&a[0]&&a[0].runInternal();this.fire("end");return this}});f.Utils=h;f.Q=g;return f},{requires:["dom","./base/utils","event/custom","./base/queue"]});
/*
Copyright 2013, KISSY UI Library v1.40dev
MIT Licensed
build time: Jul 3 13:48
*/
KISSY.add("anim",function(b,k,g,h,i){function a(a,e,d,f,c){if(a.node)c=a;else{"string"==typeof e?(e=b.unparam(""+e,";",":"),b.each(e,function(c,a){var d=b.trim(a);d&&(e[d]=b.trim(c));(!d||d!=a)&&delete e[a]})):e=b.clone(e);if(b.isPlainObject(d))c=b.clone(d);else if(c={complete:c},d&&(c.duration=d),f)c.easing=f;c.node=a;c.to=e}c=b.merge(j,c,{useTransition:b.config("anim/useTransition")});return c.useTransition&&i?new i(c):new h(c)}var f=g.Utils,j={duration:1,easing:"linear"};b.each(["pause","resume"],
function(b){a[b]=function(a,d){return null===d||"string"==typeof d||!1===d?f.pauseOrResumeQueue(a,d,b):f.pauseOrResumeQueue(a,void 0,b)}});a.isRunning=f.isElRunning;a.isPaused=f.isElPaused;a.stop=f.stopEl;a.Easing=h.Easing;b.Anim=a;a.Q=g.Q;return a},{requires:["dom","anim/base","anim/timer",KISSY.Features.isTransitionSupported()?"anim/transition":""]});
/*
Copyright 2013, KISSY UI Library v1.40dev
MIT Licensed
build time: Jul 3 19:20
*/
KISSY.add("event/base/utils",function(e){function f(a){if(0>a.indexOf("."))return[a,""];var b=a.match(/([^.]+)?(\..+)?$/),a=[b[1]];(b=b[2])?(b=b.split(".").sort(),a.push(b.join("."))):a.push("");return a}var d,c;return{splitAndRun:d=function(a,b){e.isArray(a)?e.each(a,b):(a=e.trim(a),-1==a.indexOf(" ")?b(a):e.each(a.split(/\s+/),b))},normalizeParam:function(a,b,c){var d=b||{},d=e.isFunction(b)?{fn:b,context:c}:e.merge(d),b=f(a),a=b[0];d.groups=b[1];d.type=a;return d},batchForType:function(a,b){var c=
e.makeArray(arguments),f=c[2+b];f&&"object"==typeof f?e.each(f,function(d,f){var e=[].concat(c);e.splice(0,2);e[b]=f;e[b+1]=d;a.apply(null,e)}):d(f,function(d){var e=[].concat(c);e.splice(0,2);e[b]=d;a.apply(null,e)})},fillGroupsForEvent:function(a,b){var d=f(a),e=d[1];e&&(e=c(e),b._ks_groups=e);b.type=d[0]},getGroupsRe:c=function(a){return RegExp(a.split(".").join(".*\\.")+"(?:\\.|$)")}}});
KISSY.add("event/base/object",function(e,f){function d(){this.timeStamp=e.now();this.currentTarget=this.target=f}var c=function(){return!1},a=function(){return!0};d.prototype={constructor:d,isDefaultPrevented:c,isPropagationStopped:c,isImmediatePropagationStopped:c,preventDefault:function(){this.isDefaultPrevented=a},stopPropagation:function(){this.isPropagationStopped=a},stopImmediatePropagation:function(){this.isImmediatePropagationStopped=a;this.stopPropagation()},halt:function(a){a?this.stopImmediatePropagation():
this.stopPropagation();this.preventDefault()}};return d});
KISSY.add("event/base/observer",function(e,f){function d(c){e.mix(this,c)}d.prototype={constructor:d,equals:function(c){var a=this;return!!e.reduce(a.keys,function(b,d){return b&&a[d]===c[d]},1)},simpleNotify:function(c,a){var b;b=this.fn.call(this.context||a.currentTarget,c,this.data);this.once&&a.removeObserver(this);return b},notifyInternal:function(c,a){return this.simpleNotify(c,a)},notify:function(c,a){var b;if((b=c._ks_groups)&&(!this.groups||!this.groups.match(b)))return f;b=this.notifyInternal(c,
a);!1===b&&c.halt();return b}};return d});
KISSY.add("event/base/observable",function(e){function f(d){this.currentTarget=null;e.mix(this,d);this.reset()}f.prototype={constructor:f,hasObserver:function(){return!!this.observers.length},reset:function(){this.observers=[]},removeObserver:function(d){var c,a=this.observers,b=a.length;for(c=0;c<b;c++)if(a[c]==d){a.splice(c,1);break}this.checkMemory()},checkMemory:function(){},findObserver:function(d){var c=this.observers,a;for(a=c.length-1;0<=a;--a)if(d.equals(c[a]))return a;return-1}};return f});
KISSY.add("event/base",function(e,f,d,c,a){return{Utils:f,Object:d,Observer:c,Observable:a}},{requires:["./base/utils","./base/object","./base/observer","./base/observable"]});
/*
Copyright 2013, KISSY UI Library v1.40dev
MIT Licensed
build time: Jul 3 13:48
*/
KISSY.add("anim/timer/easing",function(){function h(a){return a}function f(a,b,o,d){var m=3*a-3*o+1,e=3*o-6*a,g=3*a,c=3*b-3*d+1,h=3*d-6*b,f=3*b;return function(a){a:{for(var b=a,o,d,l=0;8>l;l++){d=((m*b+e)*b+g)*b-a;if(n(d)<j){a=b;break a}o=(3*m*b+2*e)*b+g;if(n(o)<j)break;b-=d/o}o=1;l=0;for(b=a;o>l;){d=((m*b+e)*b+g)*b-a;if(n(d)<j)break;0<d?o=b:l=b;b=(o+l)/2}a=b}return((c*a+h)*a+f)*a}}var i=Math.PI,c=Math.pow,k=Math.sin,b=parseFloat,g=/^cubic-bezier\(([^,]+),([^,]+),([^,]+),([^,]+)\)$/i,e={swing:function(a){return-Math.cos(a*
i)/2+0.5},easeNone:h,linear:h,easeIn:function(a){return a*a},ease:f(0.25,0.1,0.25,1),"ease-in":f(0.42,0,1,1),"ease-out":f(0,0,0.58,1),"ease-in-out":f(0.42,0,0.58,1),"ease-out-in":f(0,0.42,1,0.58),toFn:function(a){var j;return(j=a.match(g))?f(b(j[1]),b(j[2]),b(j[3]),b(j[4])):e[a]||h},easeOut:function(a){return(2-a)*a},easeBoth:function(a){return 1>(a*=2)?0.5*a*a:0.5*(1- --a*(a-2))},easeInStrong:function(a){return a*a*a*a},easeOutStrong:function(a){return 1- --a*a*a*a},easeBothStrong:function(a){return 1>
(a*=2)?0.5*a*a*a*a:0.5*(2-(a-=2)*a*a*a)},elasticIn:function(a){return 0===a||1===a?a:-(c(2,10*(a-=1))*k((a-0.075)*2*i/0.3))},elasticOut:function(a){return 0===a||1===a?a:c(2,-10*a)*k((a-0.075)*2*i/0.3)+1},elasticBoth:function(a){return 0===a||2===(a*=2)?a:1>a?-0.5*c(2,10*(a-=1))*k((a-0.1125)*2*i/0.45):0.5*c(2,-10*(a-=1))*k((a-0.1125)*2*i/0.45)+1},backIn:function(a){1===a&&(a-=0.001);return a*a*(2.70158*a-1.70158)},backOut:function(a){return(a-=1)*a*(2.70158*a+1.70158)+1},backBoth:function(a){var b,
o=(b=2.5949095)+1;return 1>(a*=2)?0.5*a*a*(o*a-b):0.5*((a-=2)*a*(o*a+b)+2)},bounceIn:function(a){return 1-e.bounceOut(1-a)},bounceOut:function(a){return a<1/2.75?7.5625*a*a:a<2/2.75?7.5625*(a-=1.5/2.75)*a+0.75:a<2.5/2.75?7.5625*(a-=2.25/2.75)*a+0.9375:7.5625*(a-=2.625/2.75)*a+0.984375},bounceBoth:function(a){return 0.5>a?0.5*e.bounceIn(2*a):0.5*e.bounceOut(2*a-1)+0.5}},j=1.0E-6,n=Math.abs;return e});
KISSY.add("anim/timer/manager",function(h,f){var i=h.stamp,c=h.Env.host,k=c.requestAnimationFrame,b=c.cancelAnimationFrame;if(!k)for(var g=["ms","moz","webkit","o"],e=0;e<g.length&&!k;++e)k=c[g[e]+"RequestAnimationFrame"],b=c[g[e]+"CancelAnimationFrame"]||c[g[e]+"CancelRequestAnimationFrame"];if(!k||h.UA.chrome)k=function(b){return setTimeout(b,15)},b=function(b){clearTimeout(b)};return{runnings:{},timer:null,start:function(b){var e=i(b);this.runnings[e]||(this.runnings[e]=b,this.startTimer())},stop:function(b){this.notRun(b)},
notRun:function(b){delete this.runnings[i(b)];h.isEmptyObject(this.runnings)&&this.stopTimer()},pause:function(b){this.notRun(b)},resume:function(b){this.start(b)},startTimer:function(){var b=this;b.timer||(b.timer=k(function a(){b.runFrames()?b.stopTimer():b.timer=k(a)}))},stopTimer:function(){var e=this.timer;e&&(b(e),this.timer=0)},runFrames:function(){var b,e,a=this.runnings;for(b in a)a[b].frame(),e=0;return e===f}}});
KISSY.add("anim/timer/fx",function(h,f,i){function c(b){this.load(b)}function k(b,g){return(!b.style||null==b.style[g])&&null!=f.attr(b,g,i,1)?1:0}c.prototype={isBasicFx:1,constructor:c,load:function(b){h.mix(this,b);this.pos=0;this.unit=this.unit||""},frame:function(b){this.pos=b;this.update();this.finished=this.finished||1==b},interpolate:function(b,g,e){return h.isNumber(b)&&h.isNumber(g)?(b+(g-b)*e).toFixed(3):i},update:function(){var b=this.prop,g=this.anim.node,e=this.to,c=this.interpolate(this.from,
e,this.pos);c===i?this.finished||(this.finished=1,f.css(g,b,e)):(c+=this.unit,k(g,b)?f.attr(g,b,c,1):f.css(g,b,c))},cur:function(){var b=this.prop,c=this.anim.node;if(k(c,b))return f.attr(c,b,i,1);var e,b=f.css(c,b);return isNaN(e=parseFloat(b))?!b||"auto"===b?0:b:e}};c.Factories={};c.getPos=function(b,c){var e=h.now(),f=c.duration,e=e-b.startTime-c.delay;return 0>=e?0:e>=f?1:c.easing(e/f)};c.getFx=function(b){return new (c.Factories[b.prop]||c)(b)};return c},{requires:["dom"]});
KISSY.add("anim/timer/short-hand",function(){return{background:[],border:["borderBottomWidth","borderLeftWidth","borderRightWidth","borderTopWidth"],borderBottom:["borderBottomWidth"],borderLeft:["borderLeftWidth"],borderTop:["borderTopWidth"],borderRight:["borderRightWidth"],font:["fontSize","fontWeight"],margin:["marginBottom","marginLeft","marginRight","marginTop"],padding:["paddingBottom","paddingLeft","paddingRight","paddingTop"]}});
KISSY.add("anim/timer/color",function(h,f,i,c){function k(b){var b=b+"",d;if(d=b.match(n))return[parseInt(d[1]),parseInt(d[2]),parseInt(d[3])];if(d=b.match(a))return[parseInt(d[1]),parseInt(d[2]),parseInt(d[3]),parseInt(d[4])];if(d=b.match(l)){for(b=1;b<d.length;b++)2>d[b].length&&(d[b]+=d[b]);return[parseInt(d[1],g),parseInt(d[2],g),parseInt(d[3],g)]}return j[b=b.toLowerCase()]?j[b]:[255,255,255]}function b(){b.superclass.constructor.apply(this,arguments)}var g=16,e=Math.floor,j={black:[0,0,0],silver:[192,
192,192],gray:[128,128,128],white:[255,255,255],maroon:[128,0,0],red:[255,0,0],purple:[128,0,128],fuchsia:[255,0,255],green:[0,128,0],lime:[0,255,0],olive:[128,128,0],yellow:[255,255,0],navy:[0,0,128],blue:[0,0,255],teal:[0,128,128],aqua:[0,255,255]},n=/^rgb\(([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+)\)$/i,a=/^rgba\(([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+),\s*([0-9]+)\)$/i,l=/^#?([0-9A-F]{1,2})([0-9A-F]{1,2})([0-9A-F]{1,2})$/i;c.background.push("backgroundColor");c.borderColor=["borderBottomColor","borderLeftColor",
"borderRightColor","borderTopColor"];c.border.push("borderBottomColor","borderLeftColor","borderRightColor","borderTopColor");c.borderBottom.push("borderBottomColor");c.borderLeft.push("borderLeftColor");c.borderRight.push("borderRightColor");c.borderTop.push("borderTopColor");h.extend(b,i,{load:function(){b.superclass.load.apply(this,arguments);this.from&&(this.from=k(this.from));this.to&&(this.to=k(this.to))},interpolate:function(a,d,c){var l=b.superclass.interpolate;return 3==a.length&&3==d.length?
"rgb("+[e(l(a[0],d[0],c)),e(l(a[1],d[1],c)),e(l(a[2],d[2],c))].join(", ")+")":4==a.length||4==d.length?"rgba("+[e(l(a[0],d[0],c)),e(l(a[1],d[1],c)),e(l(a[2],d[2],c)),e(l(a[3]||1,d[3]||1,c))].join(", ")+")":h.log("anim/color unknown value : "+a)}});h.each("backgroundColor,borderBottomColor,borderLeftColor,borderRightColor,borderTopColor,color,outlineColor".split(","),function(a){i.Factories[a]=b});return b},{requires:["dom","./fx","./short-hand"]});
KISSY.add("anim/timer",function(h,f,i,c,k,b,g,e){function j(){var a;j.superclass.constructor.apply(this,arguments);h.each(a=this.to,function(b,d){var c=n(d);d!=c&&(a[c]=a[d],delete a[d])})}var n=f._camelCase,a=/^([+\-]=)?([\d+.\-]+)([a-z%]*)$/i;h.extend(j,c,{prepareFx:function(){var b=this.node,c=this._propsData;h.each(c,function(a){a.duration*=1E3;a.delay*=1E3;"string"==typeof a.easing&&(a.easing=k.toFn(a.easing))});h.each(e,function(a,d){var e,m=c[d],g;m&&!m.fx&&(g=m.value,e={},h.each(a,function(a){e[a]=
f.css(b,a)}),f.css(b,d,g),h.each(e,function(a,d){d in c||(c[d]=h.merge(m,{value:f.css(b,d)}));f.css(b,d,a)}),delete c[d])});var d,m,p,j,i,n,r,q;for(d in c)if(m=c[d],m.fx)m.fx.prop=d;else{p=m.value;n={prop:d,anim:this,propData:m};r=g.getFx(n);j=p;i=r.cur();p+="";q="";if(p=p.match(a)){j=parseFloat(p[2]);if((q=p[3])&&"px"!==q&&i){var s=0,t=j;do++t,f.css(b,d,t+q),s=r.cur();while(0==s);i*=t/s;f.css(b,d,i+q)}p[1]&&(j=("-="===p[1]?-1:1)*j+i)}n.from=i;n.to=j;n.unit=q;r.load(n);m.fx=r}},frame:function(){var a,
b=1,d,c,e,f,h=this._propsData;for(a in h)if(f=h[a],c=f.fx,!c.finished&&(e=g.getPos(this,f),0!=e)){c.pos=e;if(c.isBasicFx){if(c.from==c.to){c.finished=c.finished||1==e;continue}d=0;if(f.frame&&(d=f.frame(this,c),!this.isRunning()))return;!1!==d&&c.frame(c.finished||e)}else if(c.finished=c.finished||1==e,c.frame(this,c),!this.isRunning())return;b&=c.finished}(!1===this.fire("step")||b)&&this.stop(b)},doStop:function(a){var c,d,e,f=this._propsData;b.stop(this);if(a)for(c in f)if(e=f[c],(a=e.fx)&&!a.finished)a.pos=
1,a.isBasicFx?(d=0,e.frame&&(d=e.frame(this,a)),!1!==d&&a.frame(1)):a.frame(this,a),a.finished=1},doStart:function(){b.start(this)}});j.Easing=k;return j},{requires:"dom,event,./base,./timer/easing,./timer/manager,./timer/fx,./timer/short-hand,./timer/color".split(",")});
/*
Copyright 2013, KISSY UI Library v1.40dev
MIT Licensed
build time: Jul 3 13:48
*/
KISSY.add("anim/transition",function(c,h,k,n){function o(b){var a="";c.each(b,function(b,f){a&&(a+=",");a+=f+" "+b.duration+"s "+b.easing+" "+b.delay+"s"});return a}function j(b){j.superclass.constructor.apply(this,arguments)}var l=c.Features.getTransitionPrefix(),m=l?l.toLowerCase()+"TransitionEnd":"transitionend",i=c.Features.getTransitionProperty();c.extend(j,n,{doStart:function(){var b=this,a=b.node,d=a.style,f=b._propsData,e=d[i],g={};c.each(f,function(f,d){var e=f.value,c=h.css(a,d);"number"==
typeof e&&(c=parseFloat(c));c==e&&setTimeout(function(){b._onTransitionEnd({originalEvent:{propertyName:d}})},0);g[d]=e});-1!=e.indexOf("none")?e="":e&&(e+=",");d[i]=e+o(f);k.on(a,m,b._onTransitionEnd,b);h.css(a,g)},beforeResume:function(){var b=this._propsData,a=c.merge(b),d=this._runTime/1E3;c.each(a,function(a,e){var c=d;a.delay>=c?a.delay-=c:(c-=a.delay,a.delay=0,a.duration>=c?a.duration-=c:delete b[e])})},_onTransitionEnd:function(b){var b=b.originalEvent,a=1,d=this._propsData;d[b.propertyName]&&
(d[b.propertyName].finished=1,c.each(d,function(b){if(!b.finished)return a=0,!1}),a&&this.stop(!0))},doStop:function(b){var a=this.node,d=a.style,f=this._propsData,e=[],g={};k.detach(a,m,this._onTransitionEnd,this);c.each(f,function(c,d){b||(g[d]=h.css(a,d));e.push(d)});f=c.trim(d[i].replace(RegExp("(^|,)\\s*(?:"+e.join("|")+")\\s+[^,]+","gi"),"$1")).replace(/^,|,,|,$/g,"")||"none";d[i]=f;h.css(a,g)}});return j},{requires:["dom","event","./base"]});
/*
Copyright 2013, KISSY UI Library v1.40dev
MIT Licensed
build time: Jul 3 19:20
*/
KISSY.add("event/custom/observer",function(h,m){function f(){f.superclass.constructor.apply(this,arguments)}h.extend(f,m.Observer,{keys:["fn","context","groups"]});return f},{requires:["event/base"]});KISSY.add("event/custom/object",function(h,m){function f(j){f.superclass.constructor.call(this);h.mix(this,j)}h.extend(f,m.Object);return f},{requires:["event/base"]});
KISSY.add("event/custom/observable",function(h,m,f,j){function i(){i.superclass.constructor.apply(this,arguments);this.defaultFn=null;this.defaultTargetOnly=!1;this.bubbles=!0}var b=j.Utils;h.extend(i,j.Observable,{on:function(a){a=new m(a);-1==this.findObserver(a)&&this.observers.push(a)},fire:function(a){var a=a||{},c=this.bubbles,d=this.currentTarget,e,l=this.type,k=this.defaultFn,n,g=a,b;a.type=l;g instanceof f||(g.target=d,g=new f(g));g.currentTarget=d;a=this.notify(g);!1!==b&&(b=a);if(c&&!g.isPropagationStopped()){e=
(c=d.getTargets(1))&&c.length||0;for(n=0;n<e&&!g.isPropagationStopped();n++)a=c[n].fire(l,g),!1!==b&&(b=a)}if(k&&!g.isDefaultPrevented()&&(l=i.getCustomEventObservable(g.target,g.type),!this.defaultTargetOnly&&!l.defaultTargetOnly||d==g.target))b=k.call(d,g);return b},notify:function(a){var c=[].concat(this.observers),d,e,b=c.length,k;for(k=0;k<b&&!a.isImmediatePropagationStopped();k++)d=c[k].notify(a,this),!1!==e&&(e=d),!1===d&&a.halt();return e},detach:function(a){var c,d=a.fn,e=a.context,l=this.currentTarget,
k=this.observers,a=a.groups;if(k.length){a&&(c=b.getGroupsRe(a));var n,g,f,h,j=k.length;if(d||c){e=e||l;n=a=0;for(g=[];a<j;++a)if(f=k[a],h=f.context||l,e!=h||d&&d!=f.fn||c&&!f.groups.match(c))g[n++]=f;this.observers=g}else this.reset()}}});i.getCustomEventObservable=function(a,c,d){var e,b=i.getCustomEventObservables(a,d);e=b&&b[c];!e&&d&&(e=b[c]=new i({currentTarget:a,type:c}));return e};i.getCustomEventObservables=function(a,b){!a["__~ks_custom_events"]&&b&&(a["__~ks_custom_events"]={});return a["__~ks_custom_events"]};
return i},{requires:["./observer","./object","event/base"]});
KISSY.add("event/custom/target",function(h,m,f){var j=m.Utils,i=j.splitAndRun;return{isTarget:1,fire:function(b,a){var c=this,d=void 0,e=c.getTargets(1),l=e&&e.length,a=a||{};i(b,function(b){var e;j.fillGroupsForEvent(b,a);b=a.type;if((e=f.getCustomEventObservable(c,b))||l){if(e){if(!e.hasObserver()&&!e.defaultFn&&(e.bubbles&&!l||!e.bubbles))return}else e=new f({currentTarget:c,type:b});b=e.fire(a);!1!==d&&(d=b)}});return d},publish:function(b,a){var c,d=this;i(b,function(e){c=f.getCustomEventObservable(d,
e,1);h.mix(c,a)});return d},addTarget:function(b){var a=this.getTargets();h.inArray(b,a)||a.push(b);return this},removeTarget:function(b){var a=this.getTargets(),b=h.indexOf(b,a);-1!=b&&a.splice(b,1);return this},getTargets:function(b){b||(this["__~ks_bubble_targets"]=this["__~ks_bubble_targets"]||[]);return this["__~ks_bubble_targets"]},on:function(b,a,c){var d=this;j.batchForType(function(a,b,c){b=j.normalizeParam(a,b,c);a=b.type;if(a=f.getCustomEventObservable(d,a,1))a.on(b)},0,b,a,c);return d},
detach:function(b,a,c){var d=this;j.batchForType(function(a,b,c){var i=j.normalizeParam(a,b,c);(a=i.type)?(a=f.getCustomEventObservable(d,a,1))&&a.detach(i):(a=f.getCustomEventObservables(d),h.each(a,function(a){a.detach(i)}))},0,b,a,c);return d}}},{requires:["event/base","./observable"]});KISSY.add("event/custom",function(h,m){return{Target:m}},{requires:["./custom/target"]});
/*
Copyright 2013, KISSY UI Library v1.40dev
MIT Licensed
build time: Jul 10 23:28
*/
KISSY.add("dom/base/api",function(c){var a=c.Env.host||{},i=a.document,o=c.UA,j={ELEMENT_NODE:1,ATTRIBUTE_NODE:2,TEXT_NODE:3,CDATA_SECTION_NODE:4,ENTITY_REFERENCE_NODE:5,ENTITY_NODE:6,PROCESSING_INSTRUCTION_NODE:7,COMMENT_NODE:8,DOCUMENT_NODE:9,DOCUMENT_TYPE_NODE:10,DOCUMENT_FRAGMENT_NODE:11,NOTATION_NODE:12},n={isCustomDomain:function(c){var c=c||a,c=n.get(c),f=c.document.domain,c=c.location.hostname;return f!=c&&f!="["+c+"]"},getEmptyIframeSrc:function(c){c=c||a;c=n.get(c);return o.ie&&n.isCustomDomain(c)?
"javascript:void(function(){"+encodeURIComponent("document.open();document.domain='"+c.document.domain+"';document.close();")+"}())":""},NodeType:j,getWindow:function(i){if(!i)return a;i=n.get(i);if(c.isWindow(i))return i;var f=i;f.nodeType!==j.DOCUMENT_NODE&&(f=i.ownerDocument);return f.defaultView||f.parentWindow},getDocument:function(a){if(!a)return i;a=n.get(a);return c.isWindow(a)?a.document:a.nodeType==j.DOCUMENT_NODE?a:a.ownerDocument},isDomNodeList:function(a){return a&&!a.nodeType&&a.item&&
!a.setTimeout},nodeName:function(a){var c=n.get(a),a=c.nodeName.toLowerCase();o.ie&&(c=c.scopeName)&&"HTML"!=c&&(a=c.toLowerCase()+":"+a);return a},_RE_NUM_NO_PX:RegExp("^("+/[\-+]?(?:\d*\.|)\d+(?:[eE][\-+]?\d+|)/.source+")(?!px)[a-z%]+$","i")};c.mix(n,j);return n});
KISSY.add("dom/base/attr",function(c,a,i){function o(a,g){var g=q[g]||g,d=v[g];return d&&d.get?d.get(a,g):a[g]}var j=c.Env.host.document,n=a.NodeType,j=j&&j.documentElement,r=a.nodeName,f=/^(?:autofocus|autoplay|async|checked|controls|defer|disabled|hidden|loop|multiple|open|readonly|required|scoped|selected)$/i,l=/^(?:button|input|object|select|textarea)$/i,h=/^a(?:rea)?$/i,t=/:|^on/,d=/\r/g,b={},k={val:1,css:1,html:1,text:1,data:1,width:1,height:1,offset:1,scrollTop:1,scrollLeft:1},u={tabindex:{get:function(a){var g=
a.getAttributeNode("tabindex");return g&&g.specified?parseInt(g.value,10):l.test(a.nodeName)||h.test(a.nodeName)&&a.href?0:i}}},q={hidefocus:"hideFocus",tabindex:"tabIndex",readonly:"readOnly","for":"htmlFor","class":"className",maxlength:"maxLength",cellspacing:"cellSpacing",cellpadding:"cellPadding",rowspan:"rowSpan",colspan:"colSpan",usemap:"useMap",frameborder:"frameBorder",contenteditable:"contentEditable"},x={get:function(d,g){return a.prop(d,g)?g.toLowerCase():i},set:function(d,g,e){!1===g?
a.removeAttr(d,e):(g=q[e]||e,g in d&&(d[g]=!0),d.setAttribute(e,e.toLowerCase()));return e}},v={},e={},m={select:{get:function(d){var g=d.selectedIndex,e=d.options,b;if(0>g)return null;if("select-one"===""+d.type)return a.val(e[g]);d=[];g=0;for(b=e.length;g<b;++g)e[g].selected&&d.push(a.val(e[g]));return d},set:function(d,g){var e=c.makeArray(g);c.each(d.options,function(g){g.selected=c.inArray(a.val(g),e)});e.length||(d.selectedIndex=-1);return e}}};c.each(["radio","checkbox"],function(d){m[d]={get:function(a){return null===
a.getAttribute("value")?"on":a.value},set:function(d,e){return c.isArray(e)?d.checked=c.inArray(a.val(d),e):i}}});u.style={get:function(a){return a.style.cssText}};c.mix(a,{_valHooks:m,_propFix:q,_attrHooks:u,_propHooks:v,_attrNodeHook:e,_attrFix:b,prop:function(d,g,e){var b=a.query(d),k,p;if(c.isPlainObject(g))return c.each(g,function(d,g){a.prop(b,g,d)}),i;g=q[g]||g;p=v[g];if(e!==i)for(d=b.length-1;0<=d;d--)k=b[d],p&&p.set?p.set(k,e,g):k[g]=e;else if(b.length)return o(b[0],g);return i},hasProp:function(d,
g){var e=a.query(d),b,c=e.length,p;for(b=0;b<c;b++)if(p=e[b],o(p,g)!==i)return!0;return!1},removeProp:function(d,g){var g=q[g]||g,e=a.query(d),b,c;for(b=e.length-1;0<=b;b--){c=e[b];try{c[g]=i,delete c[g]}catch(p){}}},attr:function(d,g,m,l){var h=a.query(d),p=h[0];if(c.isPlainObject(g)){var l=m,w;for(w in g)a.attr(h,w,g[w],l);return i}if(l&&k[g])return a[g](d,m);g=g.toLowerCase();if(l&&k[g])return a[g](d,m);g=b[g]||g;d=f.test(g)?x:t.test(g)?e:u[g];if(m===i){if(p&&p.nodeType===n.ELEMENT_NODE){"form"==
r(p)&&(d=e);if(d&&d.get)return d.get(p,g);m=p.getAttribute(g);return""===m&&(g=p.getAttributeNode(g),!g||!g.specified)?i:null===m?i:m}}else for(l=h.length-1;0<=l;l--)if((p=h[l])&&p.nodeType===n.ELEMENT_NODE)"form"==r(p)&&(d=e),d&&d.set?d.set(p,m,g):p.setAttribute(g,""+m);return i},removeAttr:function(d,g){var g=g.toLowerCase(),g=b[g]||g,e=a.query(d),c,m,p;for(p=e.length-1;0<=p;p--)if(m=e[p],m.nodeType==n.ELEMENT_NODE&&(m.removeAttribute(g),f.test(g)&&(c=q[g]||g)in m))m[c]=!1},hasAttr:j&&!j.hasAttribute?
function(d,e){var e=e.toLowerCase(),b=a.query(d),c,m;for(c=0;c<b.length;c++)if(m=b[c],(m=m.getAttributeNode(e))&&m.specified)return!0;return!1}:function(d,e){var b=a.query(d),c,m=b.length;for(c=0;c<m;c++)if(b[c].hasAttribute(e))return!0;return!1},val:function(e,b){var k,l,h,p,w;if(b===i){if(h=a.get(e)){if((k=m[r(h)]||m[h.type])&&"get"in k&&(l=k.get(h,"value"))!==i)return l;l=h.value;return"string"===typeof l?l.replace(d,""):null==l?"":l}return i}l=a.query(e);for(p=l.length-1;0<=p;p--){h=l[p];if(1!==
h.nodeType)break;w=b;null==w?w="":"number"===typeof w?w+="":c.isArray(w)&&(w=c.map(w,function(a){return a==null?"":a+""}));k=m[r(h)]||m[h.type];if(!k||!("set"in k)||k.set(h,w,"value")===i)h.value=w}return i},text:function(d,e){var b,c,m,p;if(e===i)return b=a.get(d),a._getText(b);c=a.query(d);for(m=c.length-1;0<=m;m--)if(b=c[m],p=b.nodeType,p==n.ELEMENT_NODE)a.empty(b),b.appendChild(b.ownerDocument.createTextNode(e));else if(p==n.TEXT_NODE||p==n.CDATA_SECTION_NODE)b.nodeValue=e;return i},_getText:function(a){return a.textContent}});
return a},{requires:["./api"]});
KISSY.add("dom/base/class",function(c,a){function i(a){for(var a=c.trim(a||""),a=a.split(f),h=[],i,d=a.length,b=0;b<d;b++)(i=a[b])&&h.push(i);return h}function o(a){return function(c,i){var d,b,k,f=c.classList,q=n.call(arguments,2);d=0;for(b=i.length;d<b;d++)(k=i[d])&&f[a].apply(f,[k].concat(q))}}function j(c){return function(h,f){var d=i(f),b=n.call(arguments,2);a.query(h).each(function(k){k.nodeType==r.ELEMENT_NODE&&a[c].apply(a,[k,d].concat(b))})}}var n=[].slice,r=a.NodeType,f=/[\.\s]\s*\.?/;c.mix(a,
{_hasClass:function(a,c){var i,d,b,k=a.classList;if(k.length){i=0;for(d=c.length;i<d;i++)if((b=c[i])&&!k.contains(b))return!1;return!0}return!1},_addClass:o("add"),_removeClass:o("remove"),_toggleClass:o("toggle"),hasClass:function(c,h){var f=a.get(c);return f&&f.nodeType==r.ELEMENT_NODE&&a._hasClass(f,i(h))},replaceClass:function(c,i,f){a.removeClass(c,i);a.addClass(c,f)},addClass:j("_addClass"),removeClass:j("_removeClass"),toggleClass:j("_toggleClass")});return a},{requires:["./api"]});
KISSY.add("dom/base/create",function(c,a,i){function o(d){var e=c.require("event/dom");e&&e.detach(d);a.removeData(d)}function j(a,e){var c=e&&e!=l?e.createElement(d):b;c.innerHTML="m<div>"+a+"</div>";return c.lastChild}function n(a,d,e){var b=d.nodeType;if(b==h.DOCUMENT_FRAGMENT_NODE){d=d.childNodes;e=e.childNodes;for(b=0;d[b];)e[b]&&n(a,d[b],e[b]),b++}else if(b==h.ELEMENT_NODE){d=d.getElementsByTagName("*");e=e.getElementsByTagName("*");for(b=0;d[b];)e[b]&&a(d[b],e[b]),b++}}function r(d,e){var b=
c.require("event/dom"),g,s;if(e.nodeType!=h.ELEMENT_NODE||a.hasData(d)){g=a.data(d);for(s in g)a.data(e,s,g[s]);b&&b.clone(d,e)}}function f(a){var d=null,e,b;if(a&&(a.push||a.item)&&a[0]){d=a[0].ownerDocument;d=d.createDocumentFragment();a=c.makeArray(a);e=0;for(b=a.length;e<b;e++)d.appendChild(a[e])}return d}var l=c.Env.host.document,h=a.NodeType,t=c.UA.ie,d="div",b=l&&l.createElement(d),k=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/ig,u=/<([\w:]+)/,q=/^\s+/,x=/\s+$/,v=
t&&9>t,e=/<|&#?\w+;/,m=l&&"outerHTML"in l.documentElement,A=/^<(\w+)\s*\/?>(?:<\/\1>)?$/;c.mix(a,{create:function(b,g,m,y){var s=null;if(!b)return s;if(b.nodeType)return a.clone(b);if("string"!=typeof b)return s;y===i&&(y=!0);y&&(b=c.trim(b));var y=a._creators,C,D,m=m||l,E,F=d;if(e.test(b))if(E=A.exec(b))s=m.createElement(E[1]);else{b=b.replace(k,"<$1></$2>");if((E=u.exec(b))&&(C=E[1]))F=C.toLowerCase();C=(y[F]||j)(b,m);v&&(D=b.match(q))&&C.insertBefore(m.createTextNode(D[0]),C.firstChild);v&&/\S/.test(b)&&
(D=b.match(x))&&C.appendChild(m.createTextNode(D[0]));b=C.childNodes;1===b.length?s=b[0].parentNode.removeChild(b[0]):b.length&&(s=f(b))}else s=m.createTextNode(b);c.isPlainObject(g)&&(s.nodeType==h.ELEMENT_NODE?a.attr(s,g,!0):s.nodeType==h.DOCUMENT_FRAGMENT_NODE&&a.attr(s.childNodes,g,!0));return s},_fixCloneAttributes:function(d,b){"textarea"===a.nodeName(d)&&(b.defaultValue=d.defaultValue,b.value=d.value)},_creators:{div:j},_defaultCreator:j,html:function(d,b,e){var d=a.query(d),g=d[0],c=!1,m,
k;if(!g)return null;if(b===i)return g.nodeType==h.ELEMENT_NODE?g.innerHTML:null;b+="";if(!b.match(/<(?:script|style|link)/i)&&(!v||!b.match(q))&&!z[(b.match(u)||["",""])[1].toLowerCase()])try{for(m=d.length-1;0<=m;m--)k=d[m],k.nodeType==h.ELEMENT_NODE&&(o(k.getElementsByTagName("*")),k.innerHTML=b);c=!0}catch(f){}c||(b=a.create(b,0,g.ownerDocument,0),a.empty(d),a.append(b,d,e));return i},outerHtml:function(e,g,c){var k=a.query(e),s=k.length,e=k[0];if(!e)return null;if(g===i){if(m)return e.outerHTML;
g=(g=e.ownerDocument)&&g!=l?g.createElement(d):b;g.innerHTML="";g.appendChild(a.clone(e,!0));g.appendChild(a.clone(e,!0));return g.innerHTML}g+="";if(!g.match(/<(?:script|style|link)/i)&&m)for(c=s-1;0<=c;c--)e=k[c],e.nodeType==h.ELEMENT_NODE&&(o(e),o(e.getElementsByTagName("*")),e.outerHTML=g);else e=a.create(g,0,e.ownerDocument,0),a.insertBefore(e,k,c),a.remove(k);return i},remove:function(d,b){var e,g=a.query(d),s,m,k=c.require("event/dom"),i;for(i=g.length-1;0<=i;i--)e=g[i],!b&&e.nodeType==h.ELEMENT_NODE&&
(s=c.makeArray(e.getElementsByTagName("*")),s.push(e),a.removeData(s),k&&k.detach(s)),(m=e.parentNode)&&m.removeChild(e)},clone:function(d,b,e,g){"object"===typeof b&&(g=b.deepWithDataAndEvent,e=b.withDataAndEvent,b=b.deep);var d=a.get(d),c,m=a._fixCloneAttributes,k;if(!d)return null;k=d.nodeType;c=d.cloneNode(b);if(k==h.ELEMENT_NODE||k==h.DOCUMENT_FRAGMENT_NODE)m&&k==h.ELEMENT_NODE&&m(d,c),b&&m&&n(m,d,c);e&&(r(d,c),b&&g&&n(r,d,c));return c},empty:function(d){var d=a.query(d),b,e;for(e=d.length-1;0<=
e;e--)b=d[e],a.remove(b.childNodes)},_nodeListToFragment:f});a.outerHTML=a.outerHtml;var g=a._creators,y=a.create,z={option:"select",optgroup:"select",area:"map",thead:"table",td:"tr",th:"tr",tr:"tbody",tbody:"table",tfoot:"table",caption:"table",colgroup:"table",col:"colgroup",legend:"fieldset"},B;for(B in z)(function(a){g[B]=function(d,b){return y("<"+a+">"+d+"</"+a+">",null,b)}})(z[B]);return a},{requires:["./api"]});
KISSY.add("dom/base/data",function(c,a,i){var o=c.Env.host,j="_ks_data_"+c.now(),n={},r={},f={applet:1,object:1,embed:1},l={hasData:function(a,b){if(a)if(b!==i){if(b in a)return!0}else if(!c.isEmptyObject(a))return!0;return!1}},h={hasData:function(a,b){return a==o?h.hasData(r,b):l.hasData(a[j],b)},data:function(a,b,c){if(a==o)return h.data(r,b,c);var f=a[j];if(c!==i)f=a[j]=a[j]||{},f[b]=c;else return b!==i?f&&f[b]:f=a[j]=a[j]||{}},removeData:function(a,b){if(a==o)return h.removeData(r,b);var k=a[j];
if(b!==i)delete k[b],c.isEmptyObject(k)&&h.removeData(a);else try{delete a[j]}catch(f){a[j]=i}}},t={hasData:function(a,b){var c=a[j];return!c?!1:l.hasData(n[c],b)},data:function(a,b,k){if(f[a.nodeName.toLowerCase()])return i;var h=a[j];if(!h){if(b!==i&&k===i)return i;h=a[j]=c.guid()}a=n[h];if(k!==i)a=n[h]=n[h]||{},a[b]=k;else return b!==i?a&&a[b]:a=n[h]=n[h]||{}},removeData:function(a,b){var k=a[j],f;if(k)if(f=n[k],b!==i)delete f[b],c.isEmptyObject(f)&&t.removeData(a);else{delete n[k];try{delete a[j]}catch(h){a[j]=
i}a.removeAttribute&&a.removeAttribute(j)}}};c.mix(a,{__EXPANDO:j,hasData:function(d,b){for(var c=!1,i=a.query(d),f=0;f<i.length&&!(c=i[f],c=c.nodeType?t.hasData(c,b):h.hasData(c,b));f++);return c},data:function(d,b,f){var d=a.query(d),l=d[0];if(c.isPlainObject(b)){for(var q in b)a.data(d,q,b[q]);return i}if(f===i){if(l)return l.nodeType?t.data(l,b):h.data(l,b)}else for(q=d.length-1;0<=q;q--)l=d[q],l.nodeType?t.data(l,b,f):h.data(l,b,f);return i},removeData:function(d,b){var c=a.query(d),f,i;for(i=
c.length-1;0<=i;i--)f=c[i],f.nodeType?t.removeData(f,b):h.removeData(f,b)}});return a},{requires:["./api"]});
KISSY.add("dom/base/insertion",function(c,a){function i(a,b){var c=[],j,q,o;for(j=0;a[j];j++)if(q=a[j],o=f(q),q.nodeType==n.DOCUMENT_FRAGMENT_NODE)c.push.apply(c,i(l(q.childNodes),b));else if("script"===o&&(!q.type||t.test(q.type)))q.parentNode&&q.parentNode.removeChild(q),b&&b.push(q);else{if(q.nodeType==n.ELEMENT_NODE&&!r.test(o)){o=[];var v,e,m=q.getElementsByTagName("script");for(e=0;e<m.length;e++)v=m[e],(!v.type||t.test(v.type))&&o.push(v);h.apply(a,[j+1,0].concat(o))}c.push(q)}return c}function o(a){a.src?
c.getScript(a.src):(a=c.trim(a.text||a.textContent||a.innerHTML||""))&&c.globalEval(a)}function j(d,b,f,h){d=a.query(d);h&&(h=[]);d=i(d,h);a._fixInsertionChecked&&a._fixInsertionChecked(d);var b=a.query(b),l,j,v,e,m=b.length;if((d.length||h&&h.length)&&m){d=a._nodeListToFragment(d);1<m&&(e=a.clone(d,!0),b=c.makeArray(b));for(l=0;l<m;l++)j=b[l],d&&(v=0<l?a.clone(e,!0):d,f(v,j)),h&&h.length&&c.each(h,o)}}var n=a.NodeType,r=/^(?:button|input|object|select|textarea)$/i,f=a.nodeName,l=c.makeArray,h=[].splice,
t=/\/(java|ecma)script/i;c.mix(a,{_fixInsertionChecked:null,insertBefore:function(a,b,c){j(a,b,function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)},c)},insertAfter:function(a,b,c){j(a,b,function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)},c)},appendTo:function(a,b,c){j(a,b,function(a,b){b.appendChild(a)},c)},prependTo:function(a,b,c){j(a,b,function(a,b){b.insertBefore(a,b.firstChild)},c)},wrapAll:function(c,b){b=a.clone(a.get(b),!0);c=a.query(c);c[0].parentNode&&a.insertBefore(b,
c[0]);for(var f;(f=b.firstChild)&&1==f.nodeType;)b=f;a.appendTo(c,b)},wrap:function(d,b){d=a.query(d);b=a.get(b);c.each(d,function(c){a.wrapAll(c,b)})},wrapInner:function(d,b){d=a.query(d);b=a.get(b);c.each(d,function(c){var d=c.childNodes;d.length?a.wrapAll(d,b):c.appendChild(b)})},unwrap:function(d){d=a.query(d);c.each(d,function(b){b=b.parentNode;a.replaceWith(b,b.childNodes)})},replaceWith:function(c,b){var f=a.query(c),b=a.query(b);a.remove(b,!0);a.insertBefore(b,f);a.remove(f)}});c.each({prepend:"prependTo",
append:"appendTo",before:"insertBefore",after:"insertAfter"},function(c,b){a[b]=a[c]});return a},{requires:["./api"]});
KISSY.add("dom/base/offset",function(c,a,i){function o(a){var e,c=a.ownerDocument.body;if(!a.getBoundingClientRect)return{left:0,top:0};e=a.getBoundingClientRect();a=e[b];e=e[k];a-=h.clientLeft||c.clientLeft||0;e-=h.clientTop||c.clientTop||0;return{left:a,top:e}}function j(b,e){var c={left:0,top:0},d=t(b),g,f=b,e=e||d;do{if(d==e){var i=f;g=o(i);i=t(i);g.left+=a[q](i);g.top+=a[x](i)}else g=o(f);c.left+=g.left;c.top+=g.top}while(d&&d!=e&&(f=d.frameElement)&&(d=d.parent));return c}var n=c.Env.host,r=
c.UA,f=n.document,l=a.NodeType,h=f&&f.documentElement,t=a.getWindow,d=Math.max,b="left",k="top",u=c.isNumber,q="scrollLeft",x="scrollTop";c.mix(a,{offset:function(b,e,c){if(e===i){var b=a.get(b),d;b&&(d=j(b,c));return d}c=a.query(b);for(d=c.length-1;0<=d;d--){var b=c[d],g=e;"static"===a.css(b,"position")&&(b.style.position="relative");var f=j(b),h={},l=void 0,k=void 0;for(k in g)l=parseFloat(a.css(b,k))||0,h[k]=l+g[k]-f[k];a.css(b,h)}return i},scrollIntoView:function(d,e,f,h){var g,j,n,q;if(n=a.get(d)){e&&
(e=a.get(e));e||(e=n.ownerDocument);e.nodeType==l.DOCUMENT_NODE&&(e=t(e));c.isPlainObject(f)&&(h=f.allowHorizontalScroll,q=f.onlyScrollIfNeeded,f=f.alignWithTop);h=h===i?!0:h;j=c.isWindow(e);var d=a.offset(n),p=a.outerHeight(n);g=a.outerWidth(n);var o,r,u,s;j?(j=e,o=a.height(j),r=a.width(j),s={left:a.scrollLeft(j),top:a.scrollTop(j)},j=d[b]-s[b],n=d[k]-s[k],g=d[b]+g-(s[b]+r),d=d[k]+p-(s[k]+o)):(o=a.offset(e),r=e.clientHeight,u=e.clientWidth,s={left:a.scrollLeft(e),top:a.scrollTop(e)},j=d[b]-(o[b]+
(parseFloat(a.css(e,"borderLeftWidth"))||0)),n=d[k]-(o[k]+(parseFloat(a.css(e,"borderTopWidth"))||0)),g=d[b]+g-(o[b]+u+(parseFloat(a.css(e,"borderRightWidth"))||0)),d=d[k]+p-(o[k]+r+(parseFloat(a.css(e,"borderBottomWidth"))||0)));if(q){if(0>n||0<d)!0===f?a.scrollTop(e,s.top+n):!1===f?a.scrollTop(e,s.top+d):0>n?a.scrollTop(e,s.top+n):a.scrollTop(e,s.top+d)}else(f=f===i?!0:!!f)?a.scrollTop(e,s.top+n):a.scrollTop(e,s.top+d);if(h)if(q){if(0>j||0<g)!0===f?a.scrollLeft(e,s.left+j):!1===f?a.scrollLeft(e,
s.left+g):0>j?a.scrollLeft(e,s.left+j):a.scrollLeft(e,s.left+g)}else(f=f===i?!0:!!f)?a.scrollLeft(e,s.left+j):a.scrollLeft(e,s.left+g)}},docWidth:0,docHeight:0,viewportHeight:0,viewportWidth:0,scrollTop:0,scrollLeft:0});c.each(["Left","Top"],function(b,e){var c="scroll"+b;a[c]=function(d,g){if(u(d))return arguments.callee(n,d);var d=a.get(d),f,h,k,j;d&&d.nodeType==l.ELEMENT_NODE?g!==i?d[c]=parseFloat(g):f=d[c]:(j=t(d),g!==i?(g=parseFloat(g),h="Left"==b?g:a.scrollLeft(j),k="Top"==b?g:a.scrollTop(j),
j.scrollTo(h,k)):(f=j["page"+(e?"Y":"X")+"Offset"],u(f)||(h=j.document,f=h.documentElement[c],u(f)||(f=h.body[c]))));return f}});c.each(["Width","Height"],function(b){a["doc"+b]=function(e){e=a.get(e);e=a.getDocument(e);return d(e.documentElement["scroll"+b],e.body["scroll"+b],a["viewport"+b](e))};a["viewport"+b]=function(e){var e=a.get(e),c=t(e),e=c["inner"+b];if(r.mobile&&e)return e;var e="client"+b,c=c.document,d=c.body,g=c.documentElement[e];return"CSS1Compat"===c.compatMode&&g||d&&d[e]||g}});
return a},{requires:["./api"]});
KISSY.add("dom/base/style",function(c,a,i){function o(a,b){return b.toUpperCase()}function j(a){return a.replace(e,"ms-").replace(w,o)}function n(a,b,c){var e={},d;for(d in b)e[d]=a[k][d],a[k][d]=b[d];c.call(a);for(d in b)a[k][d]=e[d]}function r(a,b,c){var d,e,f;if(3===a.nodeType||8===a.nodeType||!(d=a[k]))return i;b=j(b);f=z[b];b=B[b]||b;if(c!==i){null===c||c===A?c=A:!isNaN(Number(c))&&!v[b]&&(c+=g);f&&f.set&&(c=f.set(a,c));if(c!==i){try{d[b]=c}catch(h){}c===A&&d.removeAttribute&&d.removeAttribute(b)}d.cssText||
a.removeAttribute("style");return i}if(!f||!("get"in f&&(e=f.get(a,!1))!==i))e=d[b];return e===i?"":e}function f(a){var b,c=arguments;0!==a.offsetWidth?b=l.apply(i,c):n(a,G,function(){b=l.apply(i,c)});return b}function l(b,d,e){if(c.isWindow(b))return d==q?a.viewportWidth(b):a.viewportHeight(b);if(9==b.nodeType)return d==q?a.docWidth(b):a.docHeight(b);var g=d===q?["Left","Right"]:["Top","Bottom"],f=d===q?b.offsetWidth:b.offsetHeight;if(0<f)return"border"!==e&&c.each(g,function(c){e||(f-=parseFloat(a.css(b,
"padding"+c))||0);f="margin"===e?f+(parseFloat(a.css(b,e+c))||0):f-(parseFloat(a.css(b,"border"+c+"Width"))||0)}),f;f=a._getComputedStyle(b,d);if(null==f||0>Number(f))f=b.style[d]||0;f=parseFloat(f)||0;e&&c.each(g,function(c){f+=parseFloat(a.css(b,"padding"+c))||0;"padding"!==e&&(f+=parseFloat(a.css(b,"border"+c+"Width"))||0);"margin"===e&&(f+=parseFloat(a.css(b,e+c))||0)});return f}var h=c.Env.host,t=c.UA,d=a.nodeName,b=h.document,k="style",u=/^margin/,q="width",x="display"+c.now(),v={fillOpacity:1,
fontWeight:1,lineHeight:1,opacity:1,orphans:1,widows:1,zIndex:1,zoom:1},e=/^-ms-/,m=/([A-Z]|^ms)/g,A="",g="px",y=/\d(?!px)[a-z%]+$/i,z={},B={"float":"cssFloat"},p={},w=/-([a-z])/ig;c.mix(a,{_camelCase:j,_CUSTOM_STYLES:z,_cssProps:B,_getComputedStyle:function(b,c){var d="",e,f,g,i,h;f=b.ownerDocument;c=c.replace(m,"-$1").toLowerCase();if(e=f.defaultView.getComputedStyle(b,null))d=e.getPropertyValue(c)||e[c];""===d&&!a.contains(f,b)&&(c=B[c]||c,d=b[k][c]);a._RE_NUM_NO_PX.test(d)&&u.test(c)&&(h=b.style,
f=h.width,g=h.minWidth,i=h.maxWidth,h.minWidth=h.maxWidth=h.width=d,d=e.width,h.width=f,h.minWidth=g,h.maxWidth=i);return d},style:function(b,d,e){var b=a.query(b),f,g=b[0];if(c.isPlainObject(d)){for(f in d)for(g=b.length-1;0<=g;g--)r(b[g],f,d[f]);return i}if(e===i)return f="",g&&(f=r(g,d,e)),f;for(g=b.length-1;0<=g;g--)r(b[g],d,e);return i},css:function(b,d,e){var b=a.query(b),f=b[0],g;if(c.isPlainObject(d)){for(g in d)for(f=b.length-1;0<=f;f--)r(b[f],g,d[g]);return i}d=j(d);g=z[d];if(e===i){e="";
if(f&&(!g||!("get"in g&&(e=g.get(f,!0))!==i)))e=a._getComputedStyle(f,d);return"undefined"==typeof e?"":e}for(f=b.length-1;0<=f;f--)r(b[f],d,e);return i},show:function(d){var d=a.query(d),c,e,f;for(f=d.length-1;0<=f;f--)if(e=d[f],e[k].display=a.data(e,x)||A,"none"===a.css(e,"display")){c=e.tagName.toLowerCase();var g=void 0,h=p[c],i=void 0;p[c]||(g=b.body||b.documentElement,i=b.createElement(c),a.prepend(i,g),h=a.css(i,"display"),g.removeChild(i),p[c]=h);c=h;a.data(e,x,c);e[k].display=c}},hide:function(b){var b=
a.query(b),c,d;for(d=b.length-1;0<=d;d--){c=b[d];var e=c[k],f=e.display;"none"!==f&&(f&&a.data(c,x,f),e.display="none")}},toggle:function(b){var b=a.query(b),c,d;for(d=b.length-1;0<=d;d--)c=b[d],"none"===a.css(c,"display")?a.show(c):a.hide(c)},addStyleSheet:function(b,c,d){"string"==typeof b&&(d=c,c=b,b=h);var b=a.getDocument(b),e;if(d&&(d=d.replace("#",A)))e=a.get("#"+d,b);e||(e=a.create("<style>",{id:d},b),a.get("head",b).appendChild(e),e.styleSheet?e.styleSheet.cssText=c:e.appendChild(b.createTextNode(c)))},
unselectable:function(b){var b=a.query(b),e,f,g=0,h,i;for(f=b.length-1;0<=f;f--)if(e=b[f],i=e[k],i.UserSelect="none",t.gecko)i.MozUserSelect="none";else if(t.webkit)i.WebkitUserSelect="none";else if(t.ie||t.opera){i=e.getElementsByTagName("*");e.setAttribute("unselectable","on");for(h=["iframe","textarea","input","select"];e=i[g++];)c.inArray(d(e),h)||e.setAttribute("unselectable","on")}},innerWidth:0,innerHeight:0,outerWidth:0,outerHeight:0,width:0,height:0});c.each([q,"height"],function(b){a["inner"+
c.ucfirst(b)]=function(d){return(d=a.get(d))&&f(d,b,"padding")};a["outer"+c.ucfirst(b)]=function(d,c){var e=a.get(d);return e&&f(e,b,c?"margin":"border")};a[b]=function(d,c){var e=a.css(d,b,c);e&&(e=parseFloat(e));return e};z[b]={get:function(a,d){var c;d&&(c=f(a,b)+"px");return c}}});var G={position:"absolute",visibility:"hidden",display:"block"};c.each(["left","top"],function(d){z[d]={get:function(c,e){var f,g,h;if(e){h=a.css(c,"position");if("static"===h)return"auto";f=a._getComputedStyle(c,d);
if((g="auto"===f)&&"relative"===h)return"0px";if(g||y.test(f)){h={top:0,left:0};if("fixed"==a.css(c,"position"))g=c.getBoundingClientRect();else{for(f=c.offsetParent||(c.ownerDocument||b).body;f&&!H.test(f.nodeName)&&"static"===a.css(f,"position");)f=f.offsetParent;g=a.offset(c);h=a.offset(f);h.top+=parseFloat(a.css(f,"borderTopWidth"))||0;h.left+=parseFloat(a.css(f,"borderLeftWidth"))||0}g.top-=parseFloat(a.css(c,"marginTop"))||0;g.left-=parseFloat(a.css(c,"marginLeft"))||0;f={top:g.top-h.top,left:g.left-
h.left}[d]+"px"}}return f}}});var H=/^(?:body|html)$/i;return a},{requires:["./api"]});
KISSY.add("dom/base/selector",function(c,a,i){function o(a){var b=this.length,c;for(c=0;c<b&&!1!==a(this[c],c);c++);}function j(e,f){var h,g;h="string"==typeof e;var n=f!==i?j(f):(g=1)&&[l],t=n.length;if(e)if(h){e=v(e);a:{h=e;for(var r=[/\+/,/\=/,/\~/,/\[/,/\]/,/:/,/>/,/\|/,/\$/,/\^/,/\*/,/\(/,/\)/,/[\w-]+\.[\w-]+/i,/[\w-]+\#[\w-]+/i],p=0;p<r.length;p++)if(h.match(r[p])){h=!1;break a}h=!0}if(g&&"body"==e)h=[l.body];else if("getElementsByTagName"in document&&"getElementsByClassName"in document&&h)h=
l.querySelectorAll(e);else{h=[];for(g=0;g<t;g++)"querySelectorAll"in document?(console.log("chain's querySelector"),h=h.concat(c.makeArray(n[g].querySelectorAll(e)))):q.apply(h,a._selectInternal(e,n[g]));1<h.length&&1<t&&a.unique(h);console.log("normal")}}else{if(h=e.nodeType||e.setTimeout?[e]:e.getDOMNodes?e.getDOMNodes():d(e)?e:k(e)?b(e):[e],!g){var r=h,u=r.length;h=[];for(g=0;g<u;g++)for(p=0;p<t;p++)if(a._contains(n[p],r[g])){h.push(r[g]);break}}}else h=[];h.each=o;return h}function n(a,b){var c=
a&&(a.className||r(a,"class"));return c&&-1<(u+c+u).indexOf(u+b+u)}function r(a,b){var c=a&&a.getAttributeNode(b);return c&&c.specified?c.nodeValue:i}function f(a,b){return"*"==b||a.nodeName.toLowerCase()===b.toLowerCase()}var l=c.Env.host.document,h=l.documentElement,t=h.matches||h.webkitMatchesSelector||h.mozMatchesSelector||h.oMatchesSelector||h.msMatchesSelector,d=c.isArray,b=c.makeArray,k=a.isDomNodeList,u=" ",q=Array.prototype.push,x=/^(?:#([\w-]+))?\s*([\w-]+|\*)?\.?([\w-]+)?$/,v=c.trim;c.mix(a,
{_compareNodeOrder:function(a,b){return!a.compareDocumentPosition||!b.compareDocumentPosition?a.compareDocumentPosition?-1:1:a.compareDocumentPosition(b)&4?-1:1},_getSimpleAttr:r,_isTag:f,_hasSingleClass:n,_matchesInternal:function(a,b){for(var c=[],d=0,f,h=b.length;d<h;d++)f=b[d],t.call(f,a)&&c.push(f);return c},_selectInternal:function(a,c){return b(c.querySelectorAll(a))},query:j,get:function(a,b){return j(a,b)[0]||null},unique:function(){function b(d,e){return d==e?(c=!0,0):a._compareNodeOrder(d,
e)}var c,d=!0;[0,0].sort(function(){d=!1;return 0});return function(a){c=d;a.sort(b);if(c)for(var f=1,h=a.length;f<h;)a[f]===a[f-1]?(a.splice(f,1),--h):f++;return a}}(),filter:function(b,d,h){var b=j(b,h),g,i,l,k,h=[];if("string"==typeof d&&(d=v(d))&&(l=x.exec(d)))g=l[1],i=l[2],k=l[3],g?g&&!i&&!k&&(d=function(a){return r(a,"id")==g}):d=function(a){var b=!0,c=!0;i&&(b=f(a,i));k&&(c=n(a,k));return c&&b};return h=c.isFunction(d)?c.filter(b,d):a._matchesInternal(d,b)},test:function(b,c,d){b=j(b,d);return b.length&&
a.filter(b,c,d).length===b.length}});return a},{requires:["./api"]});
KISSY.add("dom/base/traversal",function(c,a,i){function o(f,l,h,n,d,b,k){if(!(f=a.get(f)))return null;if(0===l)return f;b||(f=f[h]);if(!f)return null;d=d&&a.get(d)||null;l===i&&(l=1);var b=[],o=c.isArray(l),q,x;c.isNumber(l)&&(q=0,x=l,l=function(){return++q===x});for(;f&&f!=d;){if((f.nodeType==r.ELEMENT_NODE||f.nodeType==r.TEXT_NODE&&k)&&j(f,l)&&(!n||n(f)))if(b.push(f),!o)break;f=f[h]}return o?b:b[0]||null}function j(f,i){if(!i)return!0;if(c.isArray(i)){var h,j=i.length;if(!j)return!0;for(h=0;h<j;h++)if(a.test(f,
i[h]))return!0}else if(a.test(f,i))return!0;return!1}function n(f,i,h,j){var d=[],b,k;if((b=f=a.get(f))&&h)b=f.parentNode;if(b){h=c.makeArray(b.childNodes);for(b=0;b<h.length;b++)k=h[b],(j||k.nodeType==r.ELEMENT_NODE)&&k!=f&&d.push(k);i&&(d=a.filter(d,i))}return d}var r=a.NodeType;c.mix(a,{_contains:function(a,c){return!!(a.compareDocumentPosition(c)&16)},closest:function(a,c,h,i){return o(a,c,"parentNode",function(a){return a.nodeType!=r.DOCUMENT_FRAGMENT_NODE},h,!0,i)},parent:function(a,c,h){return o(a,
c,"parentNode",function(a){return a.nodeType!=r.DOCUMENT_FRAGMENT_NODE},h,i)},first:function(c,l,h){c=a.get(c);return o(c&&c.firstChild,l,"nextSibling",i,i,!0,h)},last:function(c,l,h){c=a.get(c);return o(c&&c.lastChild,l,"previousSibling",i,i,!0,h)},next:function(a,c,h){return o(a,c,"nextSibling",i,i,i,h)},prev:function(a,c,h){return o(a,c,"previousSibling",i,i,i,h)},siblings:function(a,c,h){return n(a,c,!0,h)},children:function(a,c){return n(a,c,i)},contents:function(a,c){return n(a,c,i,1)},contains:function(c,
i){c=a.get(c);i=a.get(i);return c&&i?a._contains(c,i):!1},index:function(f,i){var h=a.query(f),j,d=0;j=h[0];if(!i){h=j&&j.parentNode;if(!h)return-1;for(;j=j.previousSibling;)j.nodeType==r.ELEMENT_NODE&&d++;return d}d=a.query(i);return"string"===typeof i?c.indexOf(j,d):c.indexOf(d[0],h)},equals:function(c,i){c=a.query(c);i=a.query(i);if(c.length!=i.length)return!1;for(var h=c.length;0<=h;h--)if(c[h]!=i[h])return!1;return!0}});return a},{requires:["./api"]});
KISSY.add("dom/base",function(c,a){c.mix(c,{DOM:a,get:a.get,query:a.query});return a},{requires:"./base/api,./base/attr,./base/class,./base/create,./base/data,./base/insertion,./base/offset,./base/style,./base/selector,./base/traversal".split(",")});
/*
Copyright 2013, KISSY UI Library v1.40dev
MIT Licensed
build time: Jul 3 19:20
*/
KISSY.add("event",function(a,c,b){a.EventTarget=b.Target;return a.Event=a.merge(c,b)},{requires:["event/dom","event/custom"]});
/*
Copyright 2013, KISSY UI Library v1.40dev
MIT Licensed
build time: Jul 3 13:57
*/
KISSY.add("node/base",function(b,h,i,j){function f(c,m,g){if(!(this instanceof f))return new f(c,m,g);if(c)if("string"==typeof c){if(c=h.create(c,m,g),c.nodeType===l.DOCUMENT_FRAGMENT_NODE)return d.apply(this,a(c.childNodes)),this}else{if(b.isArray(c)||e(c))return d.apply(this,a(c)),this}else return this;this[0]=c;this.length=1;return this}var g=Array.prototype,k=g.slice,l=h.NodeType,d=g.push,a=b.makeArray,e=h.isDomNodeList;f.prototype={constructor:f,isNodeList:!0,length:0,item:function(c){return b.isNumber(c)?
c>=this.length?null:new f(this[c]):new f(c)},add:function(c,a,e){b.isNumber(a)&&(e=a,a=j);c=f.all(c,a).getDOMNodes();a=new f(this);e===j?d.apply(a,c):(e=[e,0],e.push.apply(e,c),g.splice.apply(a,e));return a},slice:function(c,a){return new f(k.apply(this,arguments))},getDOMNodes:function(){return k.call(this)},each:function(c,a){var e=this;b.each(e,function(d,b){d=new f(d);return c.call(a||d,d,b,e)});return e},getDOMNode:function(){return this[0]},end:function(){return this.__parent||this},filter:function(c){return new f(h.filter(this,
c))},all:function(c){c=0<this.length?f.all(c,this):new f;c.__parent=this;return c},one:function(c){c=this.all(c);if(c=c.length?c.slice(0,1):null)c.__parent=this;return c}};b.mix(f,{all:function(c,a){return"string"==typeof c&&(c=b.trim(c))&&3<=c.length&&b.startsWith(c,"<")&&b.endsWith(c,">")?(a&&(a.getDOMNode&&(a=a[0]),a=a.ownerDocument||a),new f(c,j,a)):new f(h.query(c,a))},one:function(a,d){var e=f.all(a,d);return e.length?e.slice(0,1):null}});f.NodeType=l;f.KeyCode=i.KeyCode;f.Gesture=i.Gesture;
f.REPLACE_HISTORY=i.REPLACE_HISTORY;return f},{requires:["dom","event/dom"]});
KISSY.add("node/attach",function(b,h,i,j,f){function g(d,a,e){e.unshift(a);d=h[d].apply(h,e);return d===f?a:d}var k=j.prototype,l=b.makeArray;j.KeyCode=i.KeyCode;b.each("nodeName,isCustomDomain,getEmptyIframeSrc,equals,contains,index,scrollTop,scrollLeft,height,width,innerHeight,innerWidth,outerHeight,outerWidth,addStyleSheet,appendTo,prependTo,insertBefore,before,after,insertAfter,test,hasClass,addClass,removeClass,replaceClass,toggleClass,removeAttr,hasAttr,hasProp,scrollIntoView,remove,empty,removeData,hasData,unselectable,wrap,wrapAll,replaceWith,wrapInner,unwrap".split(","),function(d){k[d]=
function(){var a=l(arguments);return g(d,this,a)}});b.each("getWindow,getDocument,filter,first,last,parent,closest,next,prev,clone,siblings,contents,children".split(","),function(d){k[d]=function(){var a=l(arguments);a.unshift(this);a=h[d].apply(h,a);return a===f?this:a===null?null:new j(a)}});b.each({attr:1,text:0,css:1,style:1,val:0,prop:1,offset:0,html:0,outerHTML:0,outerHtml:0,data:1},function(d,a){k[a]=function(){var e;e=l(arguments);e[d]===f&&!b.isObject(e[0])?(e.unshift(this),e=h[a].apply(h,
e)):e=g(a,this,e);return e}});b.each("on,detach,fire,fireHandler,delegate,undelegate".split(","),function(d){k[d]=function(){var a=l(arguments);a.unshift(this);i[d].apply(i,a);return this}})},{requires:["dom","event/dom","./base"]});
KISSY.add("node/override",function(b,h,i){var j=i.prototype;b.each(["append","prepend","before","after"],function(b){j[b]=function(g){"string"==typeof g&&(g=h.create(g));if(g)h[b](g,this);return this}});b.each(["wrap","wrapAll","replaceWith","wrapInner"],function(b){var g=j[b];j[b]=function(b){"string"==typeof b&&(b=i.all(b,this[0].ownerDocument));return g.call(this,b)}})},{requires:["dom","./base"]});
KISSY.add("node/anim",function(b,h,i,j,f){function g(b,d,a){for(var e=[],c={},a=a||0;a<d;a++)e.push.apply(e,k[a]);for(a=0;a<e.length;a++)c[e[a]]=b;return c}var k=[["height","margin-top","margin-bottom","padding-top","padding-bottom"],["width","margin-left","margin-right","padding-left","padding-right"],["opacity"]];b.augment(j,{animate:function(g){var d=b.makeArray(arguments);b.each(this,function(a){var e=b.clone(d),c=e[0];c.to?(c.node=a,i(c).run()):i.apply(f,[a].concat(e)).run()});return this},stop:function(f,
d,a){b.each(this,function(b){i.stop(b,f,d,a)});return this},pause:function(f,d){b.each(this,function(a){i.pause(a,d)});return this},resume:function(f,d){b.each(this,function(a){i.resume(a,d)});return this},isRunning:function(){for(var b=0;b<this.length;b++)if(i.isRunning(this[b]))return!0;return!1},isPaused:function(){for(var b=0;b<this.length;b++)if(i.isPaused(this[b]))return!0;return!1}});b.each({show:g("show",3),hide:g("hide",3),toggle:g("toggle",3),fadeIn:g("show",3,2),fadeOut:g("hide",3,2),fadeToggle:g("toggle",
3,2),slideDown:g("show",1),slideUp:g("hide",1),slideToggle:g("toggle",1)},function(f,d){j.prototype[d]=function(a,e,c){if(h[d]&&!a)h[d](this);else b.each(this,function(b){i(b,f,a,c,e).run()});return this}})},{requires:["dom","anim","./base"]});KISSY.add("node",function(b,h){b.mix(b,{Node:h,NodeList:h,one:h.one,all:h.all});return h},{requires:["node/base","node/attach","node/override","node/anim"]});
