/*
Copyright 2013, KISSY UI Library v1.40dev
MIT Licensed
build time: Jul 3 19:20
*/
KISSY.add("event/dom/base/utils",function(f,d){var a="ksEventTargetId_"+f.now(),b=f.Env.host.document;return{simpleAdd:b&&b.addEventListener?function(a,b,d,f){a.addEventListener&&a.addEventListener(b,d,!!f)}:function(a,b,d){a.attachEvent&&a.attachEvent("on"+b,d)},simpleRemove:b&&b.removeEventListener?function(a,b,d,f){a.removeEventListener&&a.removeEventListener(b,d,!!f)}:function(a,b,d){a.detachEvent&&a.detachEvent("on"+b,d)},data:function(b,f){return d.data(b,a,f)},removeData:function(b){return d.removeData(b,
a)}}},{requires:["dom"]});KISSY.add("event/dom/base/special",function(){return{}});
KISSY.add("event/dom/base/observer",function(f,d,a){function b(a){b.superclass.constructor.apply(this,arguments)}f.extend(b,a.Observer,{keys:"fn,filter,data,context,originalType,groups,last".split(","),notifyInternal:function(a,b){var f,j,p=a.type,l;(l=this.originalType)?a.type=l:l=p;(f=d[l])&&f.handle?(f=f.handle(a,this,b))&&0<f.length&&(j=f[0]):j=this.simpleNotify(a,b);a.type=p;return j}});return b},{requires:["./special","event/base"]});
KISSY.add("event/dom/base/object",function(f,d,a){function b(){return j}function q(){return p}function m(c){var k=c.type;m.superclass.constructor.call(this);this.originalEvent=c;this.isDefaultPrevented=c.defaultPrevented||c.returnValue===p||c.getPreventDefault&&c.getPreventDefault()?b:q;var h=null,g,n,i=l.concat();f.each(o,function(c){return k.match(c.reg)?(i=i.concat(c.props),h=c.fix,!1):a});for(g=i.length;g;)n=i[--g],this[n]=c[n];this.target||(this.target=c.srcElement||t);3===this.target.nodeType&&
(this.target=this.target.parentNode);h&&h(this,c)}var t=f.Env.host.document,j=!0,p=!1,l="altKey,bubbles,cancelable,ctrlKey,currentTarget,eventPhase,metaKey,shiftKey,target,timeStamp,view,type".split(","),o=[{reg:/^key/,props:["char","charCode","key","keyCode","which"],fix:function(c,k){null==c.which&&(c.which=null!=k.charCode?k.charCode:k.keyCode);c.metaKey===a&&(c.metaKey=c.ctrlKey)}},{reg:/^touch/,props:["touches","changedTouches","targetTouches"]},{reg:/^gesturechange$/i,props:["rotation","scale"]},
{reg:/^mousewheel$/,props:[],fix:function(c,k){var h,g,l,i=k.wheelDelta,b=k.axis,o=k.wheelDeltaY,f=k.wheelDeltaX,d=k.detail;i&&(l=i/120);d&&(l=-(0==d%3?d/3:d));b!==a&&(b===e.HORIZONTAL_AXIS?(g=0,h=-1*l):b===e.VERTICAL_AXIS&&(h=0,g=l));o!==a&&(g=o/120);f!==a&&(h=-1*f/120);!h&&!g&&(g=l);h!==a&&(c.deltaX=h);g!==a&&(c.deltaY=g);l!==a&&(c.delta=l)}},{reg:/^mouse|contextmenu|click|mspointer/i,props:"buttons,clientX,clientY,button,offsetX,relatedTarget,which,fromElement,toElement,offsetY,pageX,pageY,screenX,screenY".split(","),
fix:function(c,l){var h,g,b=c.target,i=l.button;null==c.pageX&&null!=l.clientX&&(h=b.ownerDocument||t,g=h.documentElement,h=h.body,c.pageX=l.clientX+(g&&g.scrollLeft||h&&h.scrollLeft||0)-(g&&g.clientLeft||h&&h.clientLeft||0),c.pageY=l.clientY+(g&&g.scrollTop||h&&h.scrollTop||0)-(g&&g.clientTop||h&&h.clientTop||0));!c.which&&i!==a&&(c.which=i&1?1:i&2?3:i&4?2:0);!c.relatedTarget&&c.fromElement&&(c.relatedTarget=c.fromElement===b?c.toElement:c.fromElement);return c}}];f.extend(m,d.Object,{constructor:m,
preventDefault:function(){var a=this.originalEvent;a.preventDefault?a.preventDefault():a.returnValue=p;m.superclass.preventDefault.call(this)},stopPropagation:function(){var a=this.originalEvent;a.stopPropagation?a.stopPropagation():a.cancelBubble=j;m.superclass.stopPropagation.call(this)}});return m},{requires:["event/base"]});
KISSY.add("event/dom/base/observable",function(f,d,a,b,q,m,t){function j(a){f.mix(this,a);this.reset()}var p=t.Utils;f.extend(j,t.Observable,{setup:function(){var l=this.type,o=a[l]||{},c=this.currentTarget,k=b.data(c).handle;(!o.setup||!1===o.setup.call(c,l))&&b.simpleAdd(c,l,k)},constructor:j,reset:function(){j.superclass.reset.call(this);this.lastCount=this.delegateCount=0},notify:function(a){var b=a.target,c=a.type,k=this.currentTarget,h=this.observers,g=[],n,i,f=this.delegateCount||0,s,u;if(f&&
b.nodeType)for(;b!=k;){if(!0!==b.disabled||"click"!==c){var r={},m,j,q;s=[];for(i=0;i<f;i++)u=h[i],q=u.filter,j=q+"",m=r[j],void 0===m&&(m=r[j]=d.test(b,q)),m&&s.push(u);s.length&&g.push({currentTarget:b,currentTargetObservers:s})}b=b.parentNode||k}f<h.length&&g.push({currentTarget:k,currentTargetObservers:h.slice(f)});i=0;for(b=g.length;!a.isPropagationStopped()&&i<b;++i){c=g[i];s=c.currentTargetObservers;c=c.currentTarget;a.currentTarget=c;for(c=0;!a.isImmediatePropagationStopped()&&c<s.length;c++)k=
s[c],k=k.notify(a,this),!1!==n&&(n=k)}return n},fire:function(b,o){var b=b||{},c=""+this.type,k,h,g=a[c]||{};k=!1!==g.bubbles;var n=this.currentTarget;if(!(g.fire&&!1===g.fire.call(n,o))&&(b instanceof m||(h=b,b=new m({currentTarget:n,type:c,target:n}),f.mix(b,h)),!(g.preFire&&!1===g.preFire.call(n,b,o)))){var i=n,v=d.getWindow(i),s=v.document;h=[];g=0;do h.push(i),i=i.parentNode||i.ownerDocument||i===s&&v;while(!o&&i&&k);i=h[g];do b.currentTarget=i,(k=j.getDomEventObservable(i,c))&&k.notify(b),i=
h[++g];while(!o&&i&&!b.isPropagationStopped());if(!o&&!b.isDefaultPrevented()){try{n[c]&&!f.isWindow(n)&&(j.triggeredEvent=c,n[c]())}catch(u){}j.triggeredEvent=""}}},on:function(b){var f=this.observers,c=a[this.type]||{},b=b instanceof q?b:new q(b);-1==this.findObserver(b)&&(b.filter?(f.splice(this.delegateCount,0,b),this.delegateCount++):b.last?(f.push(b),this.lastCount++):f.splice(f.length-this.lastCount,0,b),c.add&&c.add.call(this.currentTarget,b))},detach:function(b){var f,c=a[this.type]||{},
k="filter"in b,h=b.filter,g=b.context,n=b.fn,i=this.currentTarget,d=this.observers,b=b.groups;if(d.length){b&&(f=p.getGroupsRe(b));var s,u,r,m,j=d.length;if(n||k||f){g=g||i;s=b=0;for(u=[];b<j;++b)r=d[b],m=r.context||i,g!=m||n&&n!=r.fn||k&&(h&&h!=r.filter||!h&&!r.filter)||f&&!r.groups.match(f)?u[s++]=r:(r.filter&&this.delegateCount&&this.delegateCount--,r.last&&this.lastCount&&this.lastCount--,c.remove&&c.remove.call(i,r));this.observers=u}else this.reset();this.checkMemory()}},checkMemory:function(){var d=
this.type,m,c,k=a[d]||{},h=this.currentTarget,g=b.data(h);if(g&&(m=g.observables,this.hasObserver()||(c=g.handle,(!k.tearDown||!1===k.tearDown.call(h,d))&&b.simpleRemove(h,d,c),delete m[d]),f.isEmptyObject(m)))g.handle=null,b.removeData(h)}});j.triggeredEvent="";j.getDomEventObservable=function(a,f){var c=b.data(a),k;c&&(k=c.observables);return k?k[f]:null};j.getDomEventObservablesHolder=function(a,f){var c=b.data(a);!c&&f&&b.data(a,c={});return c};return j},{requires:"dom,./special,./utils,./observer,./object,event/base".split(",")});
KISSY.add("event/dom/base/dom-event",function(f,d,a,b,q,m,t){function j(a,b){var c=q[b]||{},f;if(!a.originalType&&(f=c.typeFix))a.originalType=b,b=f;return b}function p(a,b,c){var d,i,v,c=f.merge(c),b=j(c,b);d=m.getDomEventObservablesHolder(a,1);if(!(v=d.handle))v=d.handle=function(a){var b=a.type,c=v.currentTarget;if(!(m.triggeredEvent==b||"undefined"==typeof KISSY))if(b=m.getDomEventObservable(c,b))return a.currentTarget=c,a=new t(a),b.notify(a)},v.currentTarget=a;if(!(i=d.observables))i=d.observables=
{};d=i[b];d||(d=i[b]=new m({type:b,currentTarget:a}),d.setup());d.on(c);a=null}function l(a,b,c){var c=f.merge(c),b=j(c,b),a=m.getDomEventObservablesHolder(a),d=(a||{}).observables;if(a&&d)if(b)(b=d[b])&&b.detach(c);else for(b in d)d[b].detach(c)}var o=d.Utils,c={};f.mix(c,{on:function(a,c,g,d){a=b.query(a);o.batchForType(function(a,b,c,d){for(var c=o.normalizeParam(b,c,d),g,b=c.type,d=a.length-1;0<=d;d--)g=a[d],p(g,b,c)},1,a,c,g,d);return a},detach:function(a,c,d,f){a=b.query(a);o.batchForType(function(a,
b,c,d){for(var c=o.normalizeParam(b,c,d),g,f,b=c.type,d=a.length-1;0<=d;d--)if(g=a[d],l(g,b,c),c.deep&&g.getElementsByTagName){f=g.getElementsByTagName("*");for(g=f.length-1;0<=g;g--)l(f[g],b,c)}},1,a,c,d,f);return a},delegate:function(a,b,d,f,i){return c.on(a,b,{fn:f,context:i,filter:d})},undelegate:function(a,b,d,f,i){return c.detach(a,b,{fn:f,context:i,filter:d})},fire:function(a,c,d,f){var i=void 0,d=d||{};d.synthetic=1;o.splitAndRun(c,function(c){var h,j,l;o.fillGroupsForEvent(c,d);c=d.type;
if((j=q[c])&&j.typeFix)c=j.typeFix;a=b.query(a);for(j=a.length-1;0<=j;j--)h=a[j],l=m.getDomEventObservable(h,c),!f&&!l&&(l=new m({type:c,currentTarget:h})),l&&(h=l.fire(d,f),!1!==i&&(i=h))});return i},fireHandler:function(a,b,d){return c.fire(a,b,d,1)},clone:function(b,c){var d;if(d=m.getDomEventObservablesHolder(b)){var j=a.data(b);j&&j===a.data(c)&&a.removeData(c);f.each(d.observables,function(a,b){f.each(a.observers,function(a){p(c,b,a)})})}}});return c},{requires:"event/base,./utils,dom,./special,./observable,./object".split(",")});
KISSY.add("event/dom/base/key-codes",function(f){var d=f.UA,a={MAC_ENTER:3,BACKSPACE:8,TAB:9,NUM_CENTER:12,ENTER:13,SHIFT:16,CTRL:17,ALT:18,PAUSE:19,CAPS_LOCK:20,ESC:27,SPACE:32,PAGE_UP:33,PAGE_DOWN:34,END:35,HOME:36,LEFT:37,UP:38,RIGHT:39,DOWN:40,PRINT_SCREEN:44,INSERT:45,DELETE:46,ZERO:48,ONE:49,TWO:50,THREE:51,FOUR:52,FIVE:53,SIX:54,SEVEN:55,EIGHT:56,NINE:57,QUESTION_MARK:63,A:65,B:66,C:67,D:68,E:69,F:70,G:71,H:72,I:73,J:74,K:75,L:76,M:77,N:78,O:79,P:80,Q:81,R:82,S:83,T:84,U:85,V:86,W:87,X:88,
Y:89,Z:90,META:91,WIN_KEY_RIGHT:92,CONTEXT_MENU:93,NUM_ZERO:96,NUM_ONE:97,NUM_TWO:98,NUM_THREE:99,NUM_FOUR:100,NUM_FIVE:101,NUM_SIX:102,NUM_SEVEN:103,NUM_EIGHT:104,NUM_NINE:105,NUM_MULTIPLY:106,NUM_PLUS:107,NUM_MINUS:109,NUM_PERIOD:110,NUM_DIVISION:111,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,NUMLOCK:144,SEMICOLON:186,DASH:189,EQUALS:187,COMMA:188,PERIOD:190,SLASH:191,APOSTROPHE:192,SINGLE_QUOTE:222,OPEN_SQUARE_BRACKET:219,BACKSLASH:220,CLOSE_SQUARE_BRACKET:221,
WIN_KEY:224,MAC_FF_META:224,WIN_IME:229,isTextModifyingKeyEvent:function(b){if(b.altKey&&!b.ctrlKey||b.metaKey||b.keyCode>=a.F1&&b.keyCode<=a.F12)return!1;switch(b.keyCode){case a.ALT:case a.CAPS_LOCK:case a.CONTEXT_MENU:case a.CTRL:case a.DOWN:case a.END:case a.ESC:case a.HOME:case a.INSERT:case a.LEFT:case a.MAC_FF_META:case a.META:case a.NUMLOCK:case a.NUM_CENTER:case a.PAGE_DOWN:case a.PAGE_UP:case a.PAUSE:case a.PRINT_SCREEN:case a.RIGHT:case a.SHIFT:case a.UP:case a.WIN_KEY:case a.WIN_KEY_RIGHT:return!1;
default:return!0}},isCharacterKey:function(b){if(b>=a.ZERO&&b<=a.NINE||b>=a.NUM_ZERO&&b<=a.NUM_MULTIPLY||b>=a.A&&b<=a.Z||d.webkit&&0==b)return!0;switch(b){case a.SPACE:case a.QUESTION_MARK:case a.NUM_PLUS:case a.NUM_MINUS:case a.NUM_PERIOD:case a.NUM_DIVISION:case a.SEMICOLON:case a.DASH:case a.EQUALS:case a.COMMA:case a.PERIOD:case a.SLASH:case a.APOSTROPHE:case a.SINGLE_QUOTE:case a.OPEN_SQUARE_BRACKET:case a.BACKSLASH:case a.CLOSE_SQUARE_BRACKET:return!0;default:return!1}}};return a});
KISSY.add("event/dom/base/gesture",function(){return{start:"mousedown",move:"mousemove",end:"mouseup",tap:"click",doubleTap:"dblclick"}});
KISSY.add("event/dom/base/special-events",function(f,d,a){var b=b;return f.mix(a,{mousewheel:{typeFix:f.UA.gecko?"DOMMouseScroll":"mousewheel"},load:{bubbles:!1},click:{fire:function(a){return!a&&"checkbox"===""+this.type&&this.click&&"input"==this.nodeName.toLowerCase()?(this.click(),!1):b}},focus:{bubbles:!1,preFire:function(a,b){b||d.fire(this,"focusin")},fire:function(a){return!a&&this.ownerDocument&&this!==this.ownerDocument.activeElement&&this.focus?(this.focus(),!1):b}},blur:{bubbles:!1,preFire:function(a,
b){b||d.fire(this,"focusout")},fire:function(a){return!a&&this.ownerDocument&&this===this.ownerDocument.activeElement&&this.blur?(this.blur(),!1):b}}})},{requires:["./dom-event","./special"]});
KISSY.add("event/dom/base/mouseenter",function(f,d,a){f.each([{name:"mouseenter",fix:"mouseover"},{name:"mouseleave",fix:"mouseout"}],function(b){a[b.name]={typeFix:b.fix,handle:function(a,b,f){var j=a.currentTarget,p=a.relatedTarget;if(!p||p!==j&&!d.contains(j,p))return[b.simpleNotify(a,f)]}}})},{requires:["dom","./special"]});
KISSY.add("event/dom/base/valuechange",function(f,d,a,b){function q(b){if(a.hasData(b,g)){var c=a.data(b,g);clearTimeout(c);a.removeData(b,g)}}function m(a){q(a.target)}function t(b){var f=b.value,g=a.data(b,h);f!==g&&(d.fireHandler(b,c,{prevVal:g,newVal:f}),a.data(b,h,f))}function j(b){a.hasData(b,g)||a.data(b,g,setTimeout(function(){t(b);a.data(b,g,setTimeout(arguments.callee,n))},n))}function p(b){var c=b.target;"focus"==b.type&&a.data(c,h,c.value);j(c)}function l(a){t(a.target)}function o(b){a.removeData(b,
h);q(b);d.detach(b,"blur",m);d.detach(b,"webkitspeechchange",l);d.detach(b,"mousedown keyup keydown focus",p)}var c="valuechange",k=a.nodeName,h="event/valuechange/history",g="event/valuechange/poll",n=50;b[c]={setup:function(){var a=k(this);if("input"==a||"textarea"==a)o(this),d.on(this,"blur",m),d.on(this,"webkitspeechchange",l),d.on(this,"mousedown keyup keydown focus",p)},tearDown:function(){o(this)}};return d},{requires:["./dom-event","dom","./special"]});
KISSY.add("event/dom/base",function(f,d,a,b,q){return f.merge({add:d.on,remove:d.detach,KeyCode:a,Gesture:b,Special:q},d)},{requires:"./base/dom-event,./base/key-codes,./base/gesture,./base/special-events,./base/mouseenter,./base/valuechange".split(",")});
/*
Copyright 2013, KISSY UI Library v1.40dev
MIT Licensed
build time: Jul 3 19:20
*/
KISSY.add("event/dom/focusin",function(d,e){var g=e.Special;d.each([{name:"focusin",fix:"focus"},{name:"focusout",fix:"blur"}],function(c){function f(a){return e.fire(a.target,c.name)}var b=d.guid("attaches_"+d.now()+"_");g[c.name]={setup:function(){var a=this.ownerDocument||this;b in a||(a[b]=0);a[b]+=1;1===a[b]&&a.addEventListener(c.fix,f,!0)},tearDown:function(){var a=this.ownerDocument||this;a[b]-=1;0===a[b]&&a.removeEventListener(c.fix,f,!0)}}});return e},{requires:["event/dom/base"]});
/*
Copyright 2013, KISSY UI Library v1.40dev
MIT Licensed
build time: Jul 3 19:20
*/
KISSY.add("event/dom/base/utils",function(f,d){var a="ksEventTargetId_"+f.now(),b=f.Env.host.document;return{simpleAdd:b&&b.addEventListener?function(a,b,d,f){a.addEventListener&&a.addEventListener(b,d,!!f)}:function(a,b,d){a.attachEvent&&a.attachEvent("on"+b,d)},simpleRemove:b&&b.removeEventListener?function(a,b,d,f){a.removeEventListener&&a.removeEventListener(b,d,!!f)}:function(a,b,d){a.detachEvent&&a.detachEvent("on"+b,d)},data:function(b,f){return d.data(b,a,f)},removeData:function(b){return d.removeData(b,
a)}}},{requires:["dom"]});KISSY.add("event/dom/base/special",function(){return{}});
KISSY.add("event/dom/base/observer",function(f,d,a){function b(a){b.superclass.constructor.apply(this,arguments)}f.extend(b,a.Observer,{keys:"fn,filter,data,context,originalType,groups,last".split(","),notifyInternal:function(a,b){var f,j,p=a.type,l;(l=this.originalType)?a.type=l:l=p;(f=d[l])&&f.handle?(f=f.handle(a,this,b))&&0<f.length&&(j=f[0]):j=this.simpleNotify(a,b);a.type=p;return j}});return b},{requires:["./special","event/base"]});
KISSY.add("event/dom/base/object",function(f,d,a){function b(){return j}function q(){return p}function m(c){var k=c.type;m.superclass.constructor.call(this);this.originalEvent=c;this.isDefaultPrevented=c.defaultPrevented||c.returnValue===p||c.getPreventDefault&&c.getPreventDefault()?b:q;var h=null,g,n,i=l.concat();f.each(o,function(c){return k.match(c.reg)?(i=i.concat(c.props),h=c.fix,!1):a});for(g=i.length;g;)n=i[--g],this[n]=c[n];this.target||(this.target=c.srcElement||t);3===this.target.nodeType&&
(this.target=this.target.parentNode);h&&h(this,c)}var t=f.Env.host.document,j=!0,p=!1,l="altKey,bubbles,cancelable,ctrlKey,currentTarget,eventPhase,metaKey,shiftKey,target,timeStamp,view,type".split(","),o=[{reg:/^key/,props:["char","charCode","key","keyCode","which"],fix:function(c,k){null==c.which&&(c.which=null!=k.charCode?k.charCode:k.keyCode);c.metaKey===a&&(c.metaKey=c.ctrlKey)}},{reg:/^touch/,props:["touches","changedTouches","targetTouches"]},{reg:/^gesturechange$/i,props:["rotation","scale"]},
{reg:/^mousewheel$/,props:[],fix:function(c,k){var h,g,l,i=k.wheelDelta,b=k.axis,o=k.wheelDeltaY,f=k.wheelDeltaX,d=k.detail;i&&(l=i/120);d&&(l=-(0==d%3?d/3:d));b!==a&&(b===e.HORIZONTAL_AXIS?(g=0,h=-1*l):b===e.VERTICAL_AXIS&&(h=0,g=l));o!==a&&(g=o/120);f!==a&&(h=-1*f/120);!h&&!g&&(g=l);h!==a&&(c.deltaX=h);g!==a&&(c.deltaY=g);l!==a&&(c.delta=l)}},{reg:/^mouse|contextmenu|click|mspointer/i,props:"buttons,clientX,clientY,button,offsetX,relatedTarget,which,fromElement,toElement,offsetY,pageX,pageY,screenX,screenY".split(","),
fix:function(c,l){var h,g,b=c.target,i=l.button;null==c.pageX&&null!=l.clientX&&(h=b.ownerDocument||t,g=h.documentElement,h=h.body,c.pageX=l.clientX+(g&&g.scrollLeft||h&&h.scrollLeft||0)-(g&&g.clientLeft||h&&h.clientLeft||0),c.pageY=l.clientY+(g&&g.scrollTop||h&&h.scrollTop||0)-(g&&g.clientTop||h&&h.clientTop||0));!c.which&&i!==a&&(c.which=i&1?1:i&2?3:i&4?2:0);!c.relatedTarget&&c.fromElement&&(c.relatedTarget=c.fromElement===b?c.toElement:c.fromElement);return c}}];f.extend(m,d.Object,{constructor:m,
preventDefault:function(){var a=this.originalEvent;a.preventDefault?a.preventDefault():a.returnValue=p;m.superclass.preventDefault.call(this)},stopPropagation:function(){var a=this.originalEvent;a.stopPropagation?a.stopPropagation():a.cancelBubble=j;m.superclass.stopPropagation.call(this)}});return m},{requires:["event/base"]});
KISSY.add("event/dom/base/observable",function(f,d,a,b,q,m,t){function j(a){f.mix(this,a);this.reset()}var p=t.Utils;f.extend(j,t.Observable,{setup:function(){var l=this.type,o=a[l]||{},c=this.currentTarget,k=b.data(c).handle;(!o.setup||!1===o.setup.call(c,l))&&b.simpleAdd(c,l,k)},constructor:j,reset:function(){j.superclass.reset.call(this);this.lastCount=this.delegateCount=0},notify:function(a){var b=a.target,c=a.type,k=this.currentTarget,h=this.observers,g=[],n,i,f=this.delegateCount||0,s,u;if(f&&
b.nodeType)for(;b!=k;){if(!0!==b.disabled||"click"!==c){var r={},m,j,q;s=[];for(i=0;i<f;i++)u=h[i],q=u.filter,j=q+"",m=r[j],void 0===m&&(m=r[j]=d.test(b,q)),m&&s.push(u);s.length&&g.push({currentTarget:b,currentTargetObservers:s})}b=b.parentNode||k}f<h.length&&g.push({currentTarget:k,currentTargetObservers:h.slice(f)});i=0;for(b=g.length;!a.isPropagationStopped()&&i<b;++i){c=g[i];s=c.currentTargetObservers;c=c.currentTarget;a.currentTarget=c;for(c=0;!a.isImmediatePropagationStopped()&&c<s.length;c++)k=
s[c],k=k.notify(a,this),!1!==n&&(n=k)}return n},fire:function(b,o){var b=b||{},c=""+this.type,k,h,g=a[c]||{};k=!1!==g.bubbles;var n=this.currentTarget;if(!(g.fire&&!1===g.fire.call(n,o))&&(b instanceof m||(h=b,b=new m({currentTarget:n,type:c,target:n}),f.mix(b,h)),!(g.preFire&&!1===g.preFire.call(n,b,o)))){var i=n,v=d.getWindow(i),s=v.document;h=[];g=0;do h.push(i),i=i.parentNode||i.ownerDocument||i===s&&v;while(!o&&i&&k);i=h[g];do b.currentTarget=i,(k=j.getDomEventObservable(i,c))&&k.notify(b),i=
h[++g];while(!o&&i&&!b.isPropagationStopped());if(!o&&!b.isDefaultPrevented()){try{n[c]&&!f.isWindow(n)&&(j.triggeredEvent=c,n[c]())}catch(u){}j.triggeredEvent=""}}},on:function(b){var f=this.observers,c=a[this.type]||{},b=b instanceof q?b:new q(b);-1==this.findObserver(b)&&(b.filter?(f.splice(this.delegateCount,0,b),this.delegateCount++):b.last?(f.push(b),this.lastCount++):f.splice(f.length-this.lastCount,0,b),c.add&&c.add.call(this.currentTarget,b))},detach:function(b){var f,c=a[this.type]||{},
k="filter"in b,h=b.filter,g=b.context,n=b.fn,i=this.currentTarget,d=this.observers,b=b.groups;if(d.length){b&&(f=p.getGroupsRe(b));var s,u,r,m,j=d.length;if(n||k||f){g=g||i;s=b=0;for(u=[];b<j;++b)r=d[b],m=r.context||i,g!=m||n&&n!=r.fn||k&&(h&&h!=r.filter||!h&&!r.filter)||f&&!r.groups.match(f)?u[s++]=r:(r.filter&&this.delegateCount&&this.delegateCount--,r.last&&this.lastCount&&this.lastCount--,c.remove&&c.remove.call(i,r));this.observers=u}else this.reset();this.checkMemory()}},checkMemory:function(){var d=
this.type,m,c,k=a[d]||{},h=this.currentTarget,g=b.data(h);if(g&&(m=g.observables,this.hasObserver()||(c=g.handle,(!k.tearDown||!1===k.tearDown.call(h,d))&&b.simpleRemove(h,d,c),delete m[d]),f.isEmptyObject(m)))g.handle=null,b.removeData(h)}});j.triggeredEvent="";j.getDomEventObservable=function(a,f){var c=b.data(a),k;c&&(k=c.observables);return k?k[f]:null};j.getDomEventObservablesHolder=function(a,f){var c=b.data(a);!c&&f&&b.data(a,c={});return c};return j},{requires:"dom,./special,./utils,./observer,./object,event/base".split(",")});
KISSY.add("event/dom/base/dom-event",function(f,d,a,b,q,m,t){function j(a,b){var c=q[b]||{},f;if(!a.originalType&&(f=c.typeFix))a.originalType=b,b=f;return b}function p(a,b,c){var d,i,v,c=f.merge(c),b=j(c,b);d=m.getDomEventObservablesHolder(a,1);if(!(v=d.handle))v=d.handle=function(a){var b=a.type,c=v.currentTarget;if(!(m.triggeredEvent==b||"undefined"==typeof KISSY))if(b=m.getDomEventObservable(c,b))return a.currentTarget=c,a=new t(a),b.notify(a)},v.currentTarget=a;if(!(i=d.observables))i=d.observables=
{};d=i[b];d||(d=i[b]=new m({type:b,currentTarget:a}),d.setup());d.on(c);a=null}function l(a,b,c){var c=f.merge(c),b=j(c,b),a=m.getDomEventObservablesHolder(a),d=(a||{}).observables;if(a&&d)if(b)(b=d[b])&&b.detach(c);else for(b in d)d[b].detach(c)}var o=d.Utils,c={};f.mix(c,{on:function(a,c,g,d){a=b.query(a);o.batchForType(function(a,b,c,d){for(var c=o.normalizeParam(b,c,d),g,b=c.type,d=a.length-1;0<=d;d--)g=a[d],p(g,b,c)},1,a,c,g,d);return a},detach:function(a,c,d,f){a=b.query(a);o.batchForType(function(a,
b,c,d){for(var c=o.normalizeParam(b,c,d),g,f,b=c.type,d=a.length-1;0<=d;d--)if(g=a[d],l(g,b,c),c.deep&&g.getElementsByTagName){f=g.getElementsByTagName("*");for(g=f.length-1;0<=g;g--)l(f[g],b,c)}},1,a,c,d,f);return a},delegate:function(a,b,d,f,i){return c.on(a,b,{fn:f,context:i,filter:d})},undelegate:function(a,b,d,f,i){return c.detach(a,b,{fn:f,context:i,filter:d})},fire:function(a,c,d,f){var i=void 0,d=d||{};d.synthetic=1;o.splitAndRun(c,function(c){var h,j,l;o.fillGroupsForEvent(c,d);c=d.type;
if((j=q[c])&&j.typeFix)c=j.typeFix;a=b.query(a);for(j=a.length-1;0<=j;j--)h=a[j],l=m.getDomEventObservable(h,c),!f&&!l&&(l=new m({type:c,currentTarget:h})),l&&(h=l.fire(d,f),!1!==i&&(i=h))});return i},fireHandler:function(a,b,d){return c.fire(a,b,d,1)},clone:function(b,c){var d;if(d=m.getDomEventObservablesHolder(b)){var j=a.data(b);j&&j===a.data(c)&&a.removeData(c);f.each(d.observables,function(a,b){f.each(a.observers,function(a){p(c,b,a)})})}}});return c},{requires:"event/base,./utils,dom,./special,./observable,./object".split(",")});
KISSY.add("event/dom/base/key-codes",function(f){var d=f.UA,a={MAC_ENTER:3,BACKSPACE:8,TAB:9,NUM_CENTER:12,ENTER:13,SHIFT:16,CTRL:17,ALT:18,PAUSE:19,CAPS_LOCK:20,ESC:27,SPACE:32,PAGE_UP:33,PAGE_DOWN:34,END:35,HOME:36,LEFT:37,UP:38,RIGHT:39,DOWN:40,PRINT_SCREEN:44,INSERT:45,DELETE:46,ZERO:48,ONE:49,TWO:50,THREE:51,FOUR:52,FIVE:53,SIX:54,SEVEN:55,EIGHT:56,NINE:57,QUESTION_MARK:63,A:65,B:66,C:67,D:68,E:69,F:70,G:71,H:72,I:73,J:74,K:75,L:76,M:77,N:78,O:79,P:80,Q:81,R:82,S:83,T:84,U:85,V:86,W:87,X:88,
Y:89,Z:90,META:91,WIN_KEY_RIGHT:92,CONTEXT_MENU:93,NUM_ZERO:96,NUM_ONE:97,NUM_TWO:98,NUM_THREE:99,NUM_FOUR:100,NUM_FIVE:101,NUM_SIX:102,NUM_SEVEN:103,NUM_EIGHT:104,NUM_NINE:105,NUM_MULTIPLY:106,NUM_PLUS:107,NUM_MINUS:109,NUM_PERIOD:110,NUM_DIVISION:111,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,NUMLOCK:144,SEMICOLON:186,DASH:189,EQUALS:187,COMMA:188,PERIOD:190,SLASH:191,APOSTROPHE:192,SINGLE_QUOTE:222,OPEN_SQUARE_BRACKET:219,BACKSLASH:220,CLOSE_SQUARE_BRACKET:221,
WIN_KEY:224,MAC_FF_META:224,WIN_IME:229,isTextModifyingKeyEvent:function(b){if(b.altKey&&!b.ctrlKey||b.metaKey||b.keyCode>=a.F1&&b.keyCode<=a.F12)return!1;switch(b.keyCode){case a.ALT:case a.CAPS_LOCK:case a.CONTEXT_MENU:case a.CTRL:case a.DOWN:case a.END:case a.ESC:case a.HOME:case a.INSERT:case a.LEFT:case a.MAC_FF_META:case a.META:case a.NUMLOCK:case a.NUM_CENTER:case a.PAGE_DOWN:case a.PAGE_UP:case a.PAUSE:case a.PRINT_SCREEN:case a.RIGHT:case a.SHIFT:case a.UP:case a.WIN_KEY:case a.WIN_KEY_RIGHT:return!1;
default:return!0}},isCharacterKey:function(b){if(b>=a.ZERO&&b<=a.NINE||b>=a.NUM_ZERO&&b<=a.NUM_MULTIPLY||b>=a.A&&b<=a.Z||d.webkit&&0==b)return!0;switch(b){case a.SPACE:case a.QUESTION_MARK:case a.NUM_PLUS:case a.NUM_MINUS:case a.NUM_PERIOD:case a.NUM_DIVISION:case a.SEMICOLON:case a.DASH:case a.EQUALS:case a.COMMA:case a.PERIOD:case a.SLASH:case a.APOSTROPHE:case a.SINGLE_QUOTE:case a.OPEN_SQUARE_BRACKET:case a.BACKSLASH:case a.CLOSE_SQUARE_BRACKET:return!0;default:return!1}}};return a});
KISSY.add("event/dom/base/gesture",function(){return{start:"mousedown",move:"mousemove",end:"mouseup",tap:"click",doubleTap:"dblclick"}});
KISSY.add("event/dom/base/special-events",function(f,d,a){var b=b;return f.mix(a,{mousewheel:{typeFix:f.UA.gecko?"DOMMouseScroll":"mousewheel"},load:{bubbles:!1},click:{fire:function(a){return!a&&"checkbox"===""+this.type&&this.click&&"input"==this.nodeName.toLowerCase()?(this.click(),!1):b}},focus:{bubbles:!1,preFire:function(a,b){b||d.fire(this,"focusin")},fire:function(a){return!a&&this.ownerDocument&&this!==this.ownerDocument.activeElement&&this.focus?(this.focus(),!1):b}},blur:{bubbles:!1,preFire:function(a,
b){b||d.fire(this,"focusout")},fire:function(a){return!a&&this.ownerDocument&&this===this.ownerDocument.activeElement&&this.blur?(this.blur(),!1):b}}})},{requires:["./dom-event","./special"]});
KISSY.add("event/dom/base/mouseenter",function(f,d,a){f.each([{name:"mouseenter",fix:"mouseover"},{name:"mouseleave",fix:"mouseout"}],function(b){a[b.name]={typeFix:b.fix,handle:function(a,b,f){var j=a.currentTarget,p=a.relatedTarget;if(!p||p!==j&&!d.contains(j,p))return[b.simpleNotify(a,f)]}}})},{requires:["dom","./special"]});
KISSY.add("event/dom/base/valuechange",function(f,d,a,b){function q(b){if(a.hasData(b,g)){var c=a.data(b,g);clearTimeout(c);a.removeData(b,g)}}function m(a){q(a.target)}function t(b){var f=b.value,g=a.data(b,h);f!==g&&(d.fireHandler(b,c,{prevVal:g,newVal:f}),a.data(b,h,f))}function j(b){a.hasData(b,g)||a.data(b,g,setTimeout(function(){t(b);a.data(b,g,setTimeout(arguments.callee,n))},n))}function p(b){var c=b.target;"focus"==b.type&&a.data(c,h,c.value);j(c)}function l(a){t(a.target)}function o(b){a.removeData(b,
h);q(b);d.detach(b,"blur",m);d.detach(b,"webkitspeechchange",l);d.detach(b,"mousedown keyup keydown focus",p)}var c="valuechange",k=a.nodeName,h="event/valuechange/history",g="event/valuechange/poll",n=50;b[c]={setup:function(){var a=k(this);if("input"==a||"textarea"==a)o(this),d.on(this,"blur",m),d.on(this,"webkitspeechchange",l),d.on(this,"mousedown keyup keydown focus",p)},tearDown:function(){o(this)}};return d},{requires:["./dom-event","dom","./special"]});
KISSY.add("event/dom/base",function(f,d,a,b,q){return f.merge({add:d.on,remove:d.detach,KeyCode:a,Gesture:b,Special:q},d)},{requires:"./base/dom-event,./base/key-codes,./base/gesture,./base/special-events,./base/mouseenter,./base/valuechange".split(",")});
/*
Copyright 2013, KISSY UI Library v1.40dev
MIT Licensed
build time: Jul 3 19:20
*/
KISSY.add("event/dom/shake",function(d,k,f){function l(a){var b=a.accelerationIncludingGravity,a=b.x,d=b.y,b=b.z,g;c!==f&&(g=n(h(a-c),h(d-i),h(b-j)),g>o&&m(),g>p&&(e=1));c=a;i=d;j=b}var q=k.Special,o=5,p=20,e=0,c,i,j,n=Math.max,h=Math.abs,a=d.Env.host,m=d.buffer(function(){e&&(k.fireHandler(a,"shake",{accelerationIncludingGravity:{x:c,y:i,z:j}}),c=f,e=0)},250);q.shake={setup:function(){this==a&&a.addEventListener("devicemotion",l,!1)},tearDown:function(){this==a&&(m.stop(),c=f,e=0,a.removeEventListener("devicemotion",
l,!1))}}},{requires:["event/dom/base"]});
/*
Copyright 2013, KISSY UI Library v1.40dev
MIT Licensed
build time: Jul 3 13:48
*/
KISSY.add("anim/base/queue",function(c,e){function h(b,d,a){var d=d||g,c,j=e.data(b,i);!j&&!a&&e.data(b,i,j={});j&&(c=j[d],!c&&!a&&(c=j[d]=[]));return c}var i=c.guid("ks-queue-"+c.now()+"-"),g=c.guid("ks-queue-"+c.now()+"-"),f;return f={queueCollectionKey:i,queue:function(b,c,a){b=h(b,c);b.push(a);return b},remove:function(b,d,a){var e=h(b,d,1);e&&(a=c.indexOf(a,e),-1<a&&e.splice(a,1));e&&!e.length&&f.clearQueue(b,d);return e},clearQueues:function(b){e.removeData(b,i)},clearQueue:function(b,d){var d=
d||g,a=e.data(b,i);a&&delete a[d];c.isEmptyObject(a)&&e.removeData(b,i)},dequeue:function(b,c){var a=h(b,c,1);a&&(a.shift(),a.length||f.clearQueue(b,c));return a}}},{requires:["dom"]});
KISSY.add("anim/base/utils",function(c,e,h,i){var g=c.guid("ks-anim-unqueued-"+c.now()+"-"),f=c.guid("ks-anim-paused-"+c.now()+"-");return{saveRunningAnim:function(b){var d=b.node,a=e.data(d,g);a||e.data(d,g,a={});a[c.stamp(b)]=b},removeRunningAnim:function(b){var d=b.node,a=e.data(d,g);a&&(delete a[c.stamp(b)],c.isEmptyObject(a)&&e.removeData(d,g))},isAnimPaused:function(b){var d=e.data(b.node,f);return d?!!d[c.stamp(b)]:0},removePausedAnim:function(b){var d=b.node,a=e.data(d,f);a&&(delete a[c.stamp(b)],
c.isEmptyObject(a)&&e.removeData(d,f))},savePausedAnim:function(b){var d=b.node,a=e.data(d,f);a||e.data(d,f,a={});a[c.stamp(b)]=b},isAnimRunning:function(b){var d=e.data(b.node,g);return d?!!d[c.stamp(b)]:0},isElPaused:function(b){return(b=e.data(b,f))&&!c.isEmptyObject(b)},isElRunning:function(b){return(b=e.data(b,g))&&!c.isEmptyObject(b)},pauseOrResumeQueue:function(b,d,a){b=e.data(b,"resume"==a?f:g);b=c.merge(b);c.each(b,function(b){if(d===i||b.config.queue==d)b[a]()})},stopEl:function(b,d,a,f){a&&
(f===i?h.clearQueues(b):!1!==f&&h.clearQueue(b,f));b=e.data(b,g);b=c.merge(b);c.each(b,function(a){(f===i||a.config.queue==f)&&a.stop(d)})}}},{requires:["dom","./queue"]});
KISSY.add("anim/base",function(c,e,h,i,g){function f(a){this.config=a;this.node=this.el=e.get(a.node);this._backupProps={};this._propsData={};if(a=a.complete)this.on("complete",a)}var b=e.NodeType,d={toggle:1,hide:1,show:1};c.augment(f,i.Target,{prepareFx:function(){},runInternal:function(){var a=this,f=a.config,j=a.node,g,i=a._backupProps,m=a._propsData,k=f.to,o=f.delay||0,p=f.duration;h.saveRunningAnim(a);if(!1===a.fire("beforeStart"))a.stop(0);else{c.each(k,function(a,b){c.isPlainObject(a)||(a=
{value:a});m[b]=c.mix({delay:o,easing:f.easing,frame:f.frame,duration:p},a)});if(j.nodeType==b.ELEMENT_NODE){if(k.width||k.height)k=j.style,c.mix(i,{overflow:k.overflow,"overflow-x":k.overflowX,"overflow-y":k.overflowY}),k.overflow="hidden","inline"===e.css(j,"display")&&"none"===e.css(j,"float")&&(c.UA.ie?k.zoom=1:k.display="inline-block");var n,l;l="none"===e.css(j,"display");c.each(m,function(b,c){g=b.value;if(d[g]){if("hide"==g&&l||"show"==g&&!l)return a.stop(1),n=!1;i[c]=e.style(j,c);"toggle"==
g?g=l?"show":"hide":"hide"==g?(b.value=0,i.display="none"):(b.value=e.css(j,c),e.css(j,c,0),e.show(j))}});if(!1===n)return}a.startTime=c.now();a.prepareFx();a.doStart()}},isRunning:function(){return h.isAnimRunning(this)},isPaused:function(){return h.isAnimPaused(this)},pause:function(){this.isRunning()&&(this._runTime=c.now()-this.startTime,h.removeRunningAnim(this),h.savePausedAnim(this),this.doStop());return this},doStop:function(){},doStart:function(){},resume:function(){this.isPaused()&&(this.startTime=
c.now()-this._runTime,h.removePausedAnim(this),h.saveRunningAnim(this),this.beforeResume(),this.doStart());return this},beforeResume:function(){},run:function(){var a;a=this.config.queue;!1===a?this.runInternal():(a=g.queue(this.node,a,this),1==a.length&&this.runInternal());return this},stop:function(a){var b=this.node,d=this.config.queue;if(!this.isRunning()&&!this.isPaused())return!1!==d&&g.remove(b,d,this),this;h.removeRunningAnim(this);h.removePausedAnim(this);this.doStop(a);if(a){var f;c.isEmptyObject(f=
this._backupProps)||e.css(this.node,f);this.fire("complete")}!1!==d&&(a=g.dequeue(b,d))&&a[0]&&a[0].runInternal();this.fire("end");return this}});f.Utils=h;f.Q=g;return f},{requires:["dom","./base/utils","event/custom","./base/queue"]});
/*
Copyright 2013, KISSY UI Library v1.40dev
MIT Licensed
build time: Jul 3 13:48
*/
KISSY.add("anim",function(b,k,g,h,i){function a(a,e,d,f,c){if(a.node)c=a;else{"string"==typeof e?(e=b.unparam(""+e,";",":"),b.each(e,function(c,a){var d=b.trim(a);d&&(e[d]=b.trim(c));(!d||d!=a)&&delete e[a]})):e=b.clone(e);if(b.isPlainObject(d))c=b.clone(d);else if(c={complete:c},d&&(c.duration=d),f)c.easing=f;c.node=a;c.to=e}c=b.merge(j,c,{useTransition:b.config("anim/useTransition")});return c.useTransition&&i?new i(c):new h(c)}var f=g.Utils,j={duration:1,easing:"linear"};b.each(["pause","resume"],
function(b){a[b]=function(a,d){return null===d||"string"==typeof d||!1===d?f.pauseOrResumeQueue(a,d,b):f.pauseOrResumeQueue(a,void 0,b)}});a.isRunning=f.isElRunning;a.isPaused=f.isElPaused;a.stop=f.stopEl;a.Easing=h.Easing;b.Anim=a;a.Q=g.Q;return a},{requires:["dom","anim/base","anim/timer",KISSY.Features.isTransitionSupported()?"anim/transition":""]});
/*
Copyright 2013, KISSY UI Library v1.40dev
MIT Licensed
build time: Jul 3 19:20
*/
KISSY.add("event/base/utils",function(e){function f(a){if(0>a.indexOf("."))return[a,""];var b=a.match(/([^.]+)?(\..+)?$/),a=[b[1]];(b=b[2])?(b=b.split(".").sort(),a.push(b.join("."))):a.push("");return a}var d,c;return{splitAndRun:d=function(a,b){e.isArray(a)?e.each(a,b):(a=e.trim(a),-1==a.indexOf(" ")?b(a):e.each(a.split(/\s+/),b))},normalizeParam:function(a,b,c){var d=b||{},d=e.isFunction(b)?{fn:b,context:c}:e.merge(d),b=f(a),a=b[0];d.groups=b[1];d.type=a;return d},batchForType:function(a,b){var c=
e.makeArray(arguments),f=c[2+b];f&&"object"==typeof f?e.each(f,function(d,f){var e=[].concat(c);e.splice(0,2);e[b]=f;e[b+1]=d;a.apply(null,e)}):d(f,function(d){var e=[].concat(c);e.splice(0,2);e[b]=d;a.apply(null,e)})},fillGroupsForEvent:function(a,b){var d=f(a),e=d[1];e&&(e=c(e),b._ks_groups=e);b.type=d[0]},getGroupsRe:c=function(a){return RegExp(a.split(".").join(".*\\.")+"(?:\\.|$)")}}});
KISSY.add("event/base/object",function(e,f){function d(){this.timeStamp=e.now();this.currentTarget=this.target=f}var c=function(){return!1},a=function(){return!0};d.prototype={constructor:d,isDefaultPrevented:c,isPropagationStopped:c,isImmediatePropagationStopped:c,preventDefault:function(){this.isDefaultPrevented=a},stopPropagation:function(){this.isPropagationStopped=a},stopImmediatePropagation:function(){this.isImmediatePropagationStopped=a;this.stopPropagation()},halt:function(a){a?this.stopImmediatePropagation():
this.stopPropagation();this.preventDefault()}};return d});
KISSY.add("event/base/observer",function(e,f){function d(c){e.mix(this,c)}d.prototype={constructor:d,equals:function(c){var a=this;return!!e.reduce(a.keys,function(b,d){return b&&a[d]===c[d]},1)},simpleNotify:function(c,a){var b;b=this.fn.call(this.context||a.currentTarget,c,this.data);this.once&&a.removeObserver(this);return b},notifyInternal:function(c,a){return this.simpleNotify(c,a)},notify:function(c,a){var b;if((b=c._ks_groups)&&(!this.groups||!this.groups.match(b)))return f;b=this.notifyInternal(c,
a);!1===b&&c.halt();return b}};return d});
KISSY.add("event/base/observable",function(e){function f(d){this.currentTarget=null;e.mix(this,d);this.reset()}f.prototype={constructor:f,hasObserver:function(){return!!this.observers.length},reset:function(){this.observers=[]},removeObserver:function(d){var c,a=this.observers,b=a.length;for(c=0;c<b;c++)if(a[c]==d){a.splice(c,1);break}this.checkMemory()},checkMemory:function(){},findObserver:function(d){var c=this.observers,a;for(a=c.length-1;0<=a;--a)if(d.equals(c[a]))return a;return-1}};return f});
KISSY.add("event/base",function(e,f,d,c,a){return{Utils:f,Object:d,Observer:c,Observable:a}},{requires:["./base/utils","./base/object","./base/observer","./base/observable"]});
/*
Copyright 2013, KISSY UI Library v1.40dev
MIT Licensed
build time: Jul 3 13:48
*/
KISSY.add("anim/timer/easing",function(){function h(a){return a}function f(a,b,o,d){var m=3*a-3*o+1,e=3*o-6*a,g=3*a,c=3*b-3*d+1,h=3*d-6*b,f=3*b;return function(a){a:{for(var b=a,o,d,l=0;8>l;l++){d=((m*b+e)*b+g)*b-a;if(n(d)<j){a=b;break a}o=(3*m*b+2*e)*b+g;if(n(o)<j)break;b-=d/o}o=1;l=0;for(b=a;o>l;){d=((m*b+e)*b+g)*b-a;if(n(d)<j)break;0<d?o=b:l=b;b=(o+l)/2}a=b}return((c*a+h)*a+f)*a}}var i=Math.PI,c=Math.pow,k=Math.sin,b=parseFloat,g=/^cubic-bezier\(([^,]+),([^,]+),([^,]+),([^,]+)\)$/i,e={swing:function(a){return-Math.cos(a*
i)/2+0.5},easeNone:h,linear:h,easeIn:function(a){return a*a},ease:f(0.25,0.1,0.25,1),"ease-in":f(0.42,0,1,1),"ease-out":f(0,0,0.58,1),"ease-in-out":f(0.42,0,0.58,1),"ease-out-in":f(0,0.42,1,0.58),toFn:function(a){var j;return(j=a.match(g))?f(b(j[1]),b(j[2]),b(j[3]),b(j[4])):e[a]||h},easeOut:function(a){return(2-a)*a},easeBoth:function(a){return 1>(a*=2)?0.5*a*a:0.5*(1- --a*(a-2))},easeInStrong:function(a){return a*a*a*a},easeOutStrong:function(a){return 1- --a*a*a*a},easeBothStrong:function(a){return 1>
(a*=2)?0.5*a*a*a*a:0.5*(2-(a-=2)*a*a*a)},elasticIn:function(a){return 0===a||1===a?a:-(c(2,10*(a-=1))*k((a-0.075)*2*i/0.3))},elasticOut:function(a){return 0===a||1===a?a:c(2,-10*a)*k((a-0.075)*2*i/0.3)+1},elasticBoth:function(a){return 0===a||2===(a*=2)?a:1>a?-0.5*c(2,10*(a-=1))*k((a-0.1125)*2*i/0.45):0.5*c(2,-10*(a-=1))*k((a-0.1125)*2*i/0.45)+1},backIn:function(a){1===a&&(a-=0.001);return a*a*(2.70158*a-1.70158)},backOut:function(a){return(a-=1)*a*(2.70158*a+1.70158)+1},backBoth:function(a){var b,
o=(b=2.5949095)+1;return 1>(a*=2)?0.5*a*a*(o*a-b):0.5*((a-=2)*a*(o*a+b)+2)},bounceIn:function(a){return 1-e.bounceOut(1-a)},bounceOut:function(a){return a<1/2.75?7.5625*a*a:a<2/2.75?7.5625*(a-=1.5/2.75)*a+0.75:a<2.5/2.75?7.5625*(a-=2.25/2.75)*a+0.9375:7.5625*(a-=2.625/2.75)*a+0.984375},bounceBoth:function(a){return 0.5>a?0.5*e.bounceIn(2*a):0.5*e.bounceOut(2*a-1)+0.5}},j=1.0E-6,n=Math.abs;return e});
KISSY.add("anim/timer/manager",function(h,f){var i=h.stamp,c=h.Env.host,k=c.requestAnimationFrame,b=c.cancelAnimationFrame;if(!k)for(var g=["ms","moz","webkit","o"],e=0;e<g.length&&!k;++e)k=c[g[e]+"RequestAnimationFrame"],b=c[g[e]+"CancelAnimationFrame"]||c[g[e]+"CancelRequestAnimationFrame"];if(!k||h.UA.chrome)k=function(b){return setTimeout(b,15)},b=function(b){clearTimeout(b)};return{runnings:{},timer:null,start:function(b){var e=i(b);this.runnings[e]||(this.runnings[e]=b,this.startTimer())},stop:function(b){this.notRun(b)},
notRun:function(b){delete this.runnings[i(b)];h.isEmptyObject(this.runnings)&&this.stopTimer()},pause:function(b){this.notRun(b)},resume:function(b){this.start(b)},startTimer:function(){var b=this;b.timer||(b.timer=k(function a(){b.runFrames()?b.stopTimer():b.timer=k(a)}))},stopTimer:function(){var e=this.timer;e&&(b(e),this.timer=0)},runFrames:function(){var b,e,a=this.runnings;for(b in a)a[b].frame(),e=0;return e===f}}});
KISSY.add("anim/timer/fx",function(h,f,i){function c(b){this.load(b)}function k(b,g){return(!b.style||null==b.style[g])&&null!=f.attr(b,g,i,1)?1:0}c.prototype={isBasicFx:1,constructor:c,load:function(b){h.mix(this,b);this.pos=0;this.unit=this.unit||""},frame:function(b){this.pos=b;this.update();this.finished=this.finished||1==b},interpolate:function(b,g,e){return h.isNumber(b)&&h.isNumber(g)?(b+(g-b)*e).toFixed(3):i},update:function(){var b=this.prop,g=this.anim.node,e=this.to,c=this.interpolate(this.from,
e,this.pos);c===i?this.finished||(this.finished=1,f.css(g,b,e)):(c+=this.unit,k(g,b)?f.attr(g,b,c,1):f.css(g,b,c))},cur:function(){var b=this.prop,c=this.anim.node;if(k(c,b))return f.attr(c,b,i,1);var e,b=f.css(c,b);return isNaN(e=parseFloat(b))?!b||"auto"===b?0:b:e}};c.Factories={};c.getPos=function(b,c){var e=h.now(),f=c.duration,e=e-b.startTime-c.delay;return 0>=e?0:e>=f?1:c.easing(e/f)};c.getFx=function(b){return new (c.Factories[b.prop]||c)(b)};return c},{requires:["dom"]});
KISSY.add("anim/timer/short-hand",function(){return{background:[],border:["borderBottomWidth","borderLeftWidth","borderRightWidth","borderTopWidth"],borderBottom:["borderBottomWidth"],borderLeft:["borderLeftWidth"],borderTop:["borderTopWidth"],borderRight:["borderRightWidth"],font:["fontSize","fontWeight"],margin:["marginBottom","marginLeft","marginRight","marginTop"],padding:["paddingBottom","paddingLeft","paddingRight","paddingTop"]}});
KISSY.add("anim/timer/color",function(h,f,i,c){function k(b){var b=b+"",d;if(d=b.match(n))return[parseInt(d[1]),parseInt(d[2]),parseInt(d[3])];if(d=b.match(a))return[parseInt(d[1]),parseInt(d[2]),parseInt(d[3]),parseInt(d[4])];if(d=b.match(l)){for(b=1;b<d.length;b++)2>d[b].length&&(d[b]+=d[b]);return[parseInt(d[1],g),parseInt(d[2],g),parseInt(d[3],g)]}return j[b=b.toLowerCase()]?j[b]:[255,255,255]}function b(){b.superclass.constructor.apply(this,arguments)}var g=16,e=Math.floor,j={black:[0,0,0],silver:[192,
192,192],gray:[128,128,128],white:[255,255,255],maroon:[128,0,0],red:[255,0,0],purple:[128,0,128],fuchsia:[255,0,255],green:[0,128,0],lime:[0,255,0],olive:[128,128,0],yellow:[255,255,0],navy:[0,0,128],blue:[0,0,255],teal:[0,128,128],aqua:[0,255,255]},n=/^rgb\(([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+)\)$/i,a=/^rgba\(([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+),\s*([0-9]+)\)$/i,l=/^#?([0-9A-F]{1,2})([0-9A-F]{1,2})([0-9A-F]{1,2})$/i;c.background.push("backgroundColor");c.borderColor=["borderBottomColor","borderLeftColor",
"borderRightColor","borderTopColor"];c.border.push("borderBottomColor","borderLeftColor","borderRightColor","borderTopColor");c.borderBottom.push("borderBottomColor");c.borderLeft.push("borderLeftColor");c.borderRight.push("borderRightColor");c.borderTop.push("borderTopColor");h.extend(b,i,{load:function(){b.superclass.load.apply(this,arguments);this.from&&(this.from=k(this.from));this.to&&(this.to=k(this.to))},interpolate:function(a,d,c){var l=b.superclass.interpolate;return 3==a.length&&3==d.length?
"rgb("+[e(l(a[0],d[0],c)),e(l(a[1],d[1],c)),e(l(a[2],d[2],c))].join(", ")+")":4==a.length||4==d.length?"rgba("+[e(l(a[0],d[0],c)),e(l(a[1],d[1],c)),e(l(a[2],d[2],c)),e(l(a[3]||1,d[3]||1,c))].join(", ")+")":h.log("anim/color unknown value : "+a)}});h.each("backgroundColor,borderBottomColor,borderLeftColor,borderRightColor,borderTopColor,color,outlineColor".split(","),function(a){i.Factories[a]=b});return b},{requires:["dom","./fx","./short-hand"]});
KISSY.add("anim/timer",function(h,f,i,c,k,b,g,e){function j(){var a;j.superclass.constructor.apply(this,arguments);h.each(a=this.to,function(b,d){var c=n(d);d!=c&&(a[c]=a[d],delete a[d])})}var n=f._camelCase,a=/^([+\-]=)?([\d+.\-]+)([a-z%]*)$/i;h.extend(j,c,{prepareFx:function(){var b=this.node,c=this._propsData;h.each(c,function(a){a.duration*=1E3;a.delay*=1E3;"string"==typeof a.easing&&(a.easing=k.toFn(a.easing))});h.each(e,function(a,d){var e,m=c[d],g;m&&!m.fx&&(g=m.value,e={},h.each(a,function(a){e[a]=
f.css(b,a)}),f.css(b,d,g),h.each(e,function(a,d){d in c||(c[d]=h.merge(m,{value:f.css(b,d)}));f.css(b,d,a)}),delete c[d])});var d,m,p,j,i,n,r,q;for(d in c)if(m=c[d],m.fx)m.fx.prop=d;else{p=m.value;n={prop:d,anim:this,propData:m};r=g.getFx(n);j=p;i=r.cur();p+="";q="";if(p=p.match(a)){j=parseFloat(p[2]);if((q=p[3])&&"px"!==q&&i){var s=0,t=j;do++t,f.css(b,d,t+q),s=r.cur();while(0==s);i*=t/s;f.css(b,d,i+q)}p[1]&&(j=("-="===p[1]?-1:1)*j+i)}n.from=i;n.to=j;n.unit=q;r.load(n);m.fx=r}},frame:function(){var a,
b=1,d,c,e,f,h=this._propsData;for(a in h)if(f=h[a],c=f.fx,!c.finished&&(e=g.getPos(this,f),0!=e)){c.pos=e;if(c.isBasicFx){if(c.from==c.to){c.finished=c.finished||1==e;continue}d=0;if(f.frame&&(d=f.frame(this,c),!this.isRunning()))return;!1!==d&&c.frame(c.finished||e)}else if(c.finished=c.finished||1==e,c.frame(this,c),!this.isRunning())return;b&=c.finished}(!1===this.fire("step")||b)&&this.stop(b)},doStop:function(a){var c,d,e,f=this._propsData;b.stop(this);if(a)for(c in f)if(e=f[c],(a=e.fx)&&!a.finished)a.pos=
1,a.isBasicFx?(d=0,e.frame&&(d=e.frame(this,a)),!1!==d&&a.frame(1)):a.frame(this,a),a.finished=1},doStart:function(){b.start(this)}});j.Easing=k;return j},{requires:"dom,event,./base,./timer/easing,./timer/manager,./timer/fx,./timer/short-hand,./timer/color".split(",")});
/*
Copyright 2013, KISSY UI Library v1.40dev
MIT Licensed
build time: Jul 3 13:48
*/
KISSY.add("anim/transition",function(c,h,k,n){function o(b){var a="";c.each(b,function(b,f){a&&(a+=",");a+=f+" "+b.duration+"s "+b.easing+" "+b.delay+"s"});return a}function j(b){j.superclass.constructor.apply(this,arguments)}var l=c.Features.getTransitionPrefix(),m=l?l.toLowerCase()+"TransitionEnd":"transitionend",i=c.Features.getTransitionProperty();c.extend(j,n,{doStart:function(){var b=this,a=b.node,d=a.style,f=b._propsData,e=d[i],g={};c.each(f,function(f,d){var e=f.value,c=h.css(a,d);"number"==
typeof e&&(c=parseFloat(c));c==e&&setTimeout(function(){b._onTransitionEnd({originalEvent:{propertyName:d}})},0);g[d]=e});-1!=e.indexOf("none")?e="":e&&(e+=",");d[i]=e+o(f);k.on(a,m,b._onTransitionEnd,b);h.css(a,g)},beforeResume:function(){var b=this._propsData,a=c.merge(b),d=this._runTime/1E3;c.each(a,function(a,e){var c=d;a.delay>=c?a.delay-=c:(c-=a.delay,a.delay=0,a.duration>=c?a.duration-=c:delete b[e])})},_onTransitionEnd:function(b){var b=b.originalEvent,a=1,d=this._propsData;d[b.propertyName]&&
(d[b.propertyName].finished=1,c.each(d,function(b){if(!b.finished)return a=0,!1}),a&&this.stop(!0))},doStop:function(b){var a=this.node,d=a.style,f=this._propsData,e=[],g={};k.detach(a,m,this._onTransitionEnd,this);c.each(f,function(c,d){b||(g[d]=h.css(a,d));e.push(d)});f=c.trim(d[i].replace(RegExp("(^|,)\\s*(?:"+e.join("|")+")\\s+[^,]+","gi"),"$1")).replace(/^,|,,|,$/g,"")||"none";d[i]=f;h.css(a,g)}});return j},{requires:["dom","event","./base"]});
/*
Copyright 2013, KISSY UI Library v1.40dev
MIT Licensed
build time: Jul 3 19:20
*/
KISSY.add("event/custom/observer",function(h,m){function f(){f.superclass.constructor.apply(this,arguments)}h.extend(f,m.Observer,{keys:["fn","context","groups"]});return f},{requires:["event/base"]});KISSY.add("event/custom/object",function(h,m){function f(j){f.superclass.constructor.call(this);h.mix(this,j)}h.extend(f,m.Object);return f},{requires:["event/base"]});
KISSY.add("event/custom/observable",function(h,m,f,j){function i(){i.superclass.constructor.apply(this,arguments);this.defaultFn=null;this.defaultTargetOnly=!1;this.bubbles=!0}var b=j.Utils;h.extend(i,j.Observable,{on:function(a){a=new m(a);-1==this.findObserver(a)&&this.observers.push(a)},fire:function(a){var a=a||{},c=this.bubbles,d=this.currentTarget,e,l=this.type,k=this.defaultFn,n,g=a,b;a.type=l;g instanceof f||(g.target=d,g=new f(g));g.currentTarget=d;a=this.notify(g);!1!==b&&(b=a);if(c&&!g.isPropagationStopped()){e=
(c=d.getTargets(1))&&c.length||0;for(n=0;n<e&&!g.isPropagationStopped();n++)a=c[n].fire(l,g),!1!==b&&(b=a)}if(k&&!g.isDefaultPrevented()&&(l=i.getCustomEventObservable(g.target,g.type),!this.defaultTargetOnly&&!l.defaultTargetOnly||d==g.target))b=k.call(d,g);return b},notify:function(a){var c=[].concat(this.observers),d,e,b=c.length,k;for(k=0;k<b&&!a.isImmediatePropagationStopped();k++)d=c[k].notify(a,this),!1!==e&&(e=d),!1===d&&a.halt();return e},detach:function(a){var c,d=a.fn,e=a.context,l=this.currentTarget,
k=this.observers,a=a.groups;if(k.length){a&&(c=b.getGroupsRe(a));var n,g,f,h,j=k.length;if(d||c){e=e||l;n=a=0;for(g=[];a<j;++a)if(f=k[a],h=f.context||l,e!=h||d&&d!=f.fn||c&&!f.groups.match(c))g[n++]=f;this.observers=g}else this.reset()}}});i.getCustomEventObservable=function(a,c,d){var e,b=i.getCustomEventObservables(a,d);e=b&&b[c];!e&&d&&(e=b[c]=new i({currentTarget:a,type:c}));return e};i.getCustomEventObservables=function(a,b){!a["__~ks_custom_events"]&&b&&(a["__~ks_custom_events"]={});return a["__~ks_custom_events"]};
return i},{requires:["./observer","./object","event/base"]});
KISSY.add("event/custom/target",function(h,m,f){var j=m.Utils,i=j.splitAndRun;return{isTarget:1,fire:function(b,a){var c=this,d=void 0,e=c.getTargets(1),l=e&&e.length,a=a||{};i(b,function(b){var e;j.fillGroupsForEvent(b,a);b=a.type;if((e=f.getCustomEventObservable(c,b))||l){if(e){if(!e.hasObserver()&&!e.defaultFn&&(e.bubbles&&!l||!e.bubbles))return}else e=new f({currentTarget:c,type:b});b=e.fire(a);!1!==d&&(d=b)}});return d},publish:function(b,a){var c,d=this;i(b,function(e){c=f.getCustomEventObservable(d,
e,1);h.mix(c,a)});return d},addTarget:function(b){var a=this.getTargets();h.inArray(b,a)||a.push(b);return this},removeTarget:function(b){var a=this.getTargets(),b=h.indexOf(b,a);-1!=b&&a.splice(b,1);return this},getTargets:function(b){b||(this["__~ks_bubble_targets"]=this["__~ks_bubble_targets"]||[]);return this["__~ks_bubble_targets"]},on:function(b,a,c){var d=this;j.batchForType(function(a,b,c){b=j.normalizeParam(a,b,c);a=b.type;if(a=f.getCustomEventObservable(d,a,1))a.on(b)},0,b,a,c);return d},
detach:function(b,a,c){var d=this;j.batchForType(function(a,b,c){var i=j.normalizeParam(a,b,c);(a=i.type)?(a=f.getCustomEventObservable(d,a,1))&&a.detach(i):(a=f.getCustomEventObservables(d),h.each(a,function(a){a.detach(i)}))},0,b,a,c);return d}}},{requires:["event/base","./observable"]});KISSY.add("event/custom",function(h,m){return{Target:m}},{requires:["./custom/target"]});
/*
Copyright 2013, KISSY UI Library v1.40dev
MIT Licensed
build time: Jul 10 23:07
*/
KISSY.add("dom/base/api",function(e){var a=e.Env.host||{},h=a.document,p=e.UA,k={ELEMENT_NODE:1,ATTRIBUTE_NODE:2,TEXT_NODE:3,CDATA_SECTION_NODE:4,ENTITY_REFERENCE_NODE:5,ENTITY_NODE:6,PROCESSING_INSTRUCTION_NODE:7,COMMENT_NODE:8,DOCUMENT_NODE:9,DOCUMENT_TYPE_NODE:10,DOCUMENT_FRAGMENT_NODE:11,NOTATION_NODE:12},m={isCustomDomain:function(e){var e=e||a,e=m.get(e),i=e.document.domain,e=e.location.hostname;return i!=e&&i!="["+e+"]"},getEmptyIframeSrc:function(e){e=e||a;e=m.get(e);return p.ie&&m.isCustomDomain(e)?
"javascript:void(function(){"+encodeURIComponent("document.open();document.domain='"+e.document.domain+"';document.close();")+"}())":""},NodeType:k,getWindow:function(h){if(!h)return a;h=m.get(h);if(e.isWindow(h))return h;var i=h;i.nodeType!==k.DOCUMENT_NODE&&(i=h.ownerDocument);return i.defaultView||i.parentWindow},getDocument:function(a){if(!a)return h;a=m.get(a);return e.isWindow(a)?a.document:a.nodeType==k.DOCUMENT_NODE?a:a.ownerDocument},isDomNodeList:function(a){return a&&!a.nodeType&&a.item&&
!a.setTimeout},nodeName:function(a){var e=m.get(a),a=e.nodeName.toLowerCase();p.ie&&(e=e.scopeName)&&"HTML"!=e&&(a=e.toLowerCase()+":"+a);return a},_RE_NUM_NO_PX:RegExp("^("+/[\-+]?(?:\d*\.|)\d+(?:[eE][\-+]?\d+|)/.source+")(?!px)[a-z%]+$","i")};e.mix(m,k);return m});
KISSY.add("dom/base/attr",function(e,a,h){function p(a,g){var g=o[g]||g,c=x[g];return c&&c.get?c.get(a,g):a[g]}var k=e.Env.host.document,m=a.NodeType,k=k&&k.documentElement,s=a.nodeName,i=/^(?:autofocus|autoplay|async|checked|controls|defer|disabled|hidden|loop|multiple|open|readonly|required|scoped|selected)$/i,f=/^(?:button|input|object|select|textarea)$/i,j=/^a(?:rea)?$/i,t=/:|^on/,d=/\r/g,b={},l={val:1,css:1,html:1,text:1,data:1,width:1,height:1,offset:1,scrollTop:1,scrollLeft:1},w={tabindex:{get:function(a){var g=
a.getAttributeNode("tabindex");return g&&g.specified?parseInt(g.value,10):f.test(a.nodeName)||j.test(a.nodeName)&&a.href?0:h}}},o={hidefocus:"hideFocus",tabindex:"tabIndex",readonly:"readOnly","for":"htmlFor","class":"className",maxlength:"maxLength",cellspacing:"cellSpacing",cellpadding:"cellPadding",rowspan:"rowSpan",colspan:"colSpan",usemap:"useMap",frameborder:"frameBorder",contenteditable:"contentEditable"},z={get:function(c,g){return a.prop(c,g)?g.toLowerCase():h},set:function(c,g,d){!1===g?
a.removeAttr(c,d):(g=o[d]||d,g in c&&(c[g]=!0),c.setAttribute(d,d.toLowerCase()));return d}},x={},c={},n={select:{get:function(c){var g=c.selectedIndex,d=c.options,b;if(0>g)return null;if("select-one"===""+c.type)return a.val(d[g]);c=[];g=0;for(b=d.length;g<b;++g)d[g].selected&&c.push(a.val(d[g]));return c},set:function(c,g){var d=e.makeArray(g);e.each(c.options,function(g){g.selected=e.inArray(a.val(g),d)});d.length||(c.selectedIndex=-1);return d}}};e.each(["radio","checkbox"],function(c){n[c]={get:function(a){return null===
a.getAttribute("value")?"on":a.value},set:function(g,c){return e.isArray(c)?g.checked=e.inArray(a.val(g),c):h}}});w.style={get:function(a){return a.style.cssText}};e.mix(a,{_valHooks:n,_propFix:o,_attrHooks:w,_propHooks:x,_attrNodeHook:c,_attrFix:b,prop:function(c,g,d){var b=a.query(c),l,q;if(e.isPlainObject(g))return e.each(g,function(c,g){a.prop(b,g,c)}),h;g=o[g]||g;q=x[g];if(d!==h)for(c=b.length-1;0<=c;c--)l=b[c],q&&q.set?q.set(l,d,g):l[g]=d;else if(b.length)return p(b[0],g);return h},hasProp:function(c,
g){var d=a.query(c),b,e=d.length,q;for(b=0;b<e;b++)if(q=d[b],p(q,g)!==h)return!0;return!1},removeProp:function(c,g){var g=o[g]||g,d=a.query(c),b,e;for(b=d.length-1;0<=b;b--){e=d[b];try{e[g]=h,delete e[g]}catch(q){}}},attr:function(d,g,f,n){var j=a.query(d),q=j[0];if(e.isPlainObject(g)){var n=f,u;for(u in g)a.attr(j,u,g[u],n);return h}if(n&&l[g])return a[g](d,f);g=g.toLowerCase();if(n&&l[g])return a[g](d,f);g=b[g]||g;d=i.test(g)?z:t.test(g)?c:w[g];if(f===h){if(q&&q.nodeType===m.ELEMENT_NODE){"form"==
s(q)&&(d=c);if(d&&d.get)return d.get(q,g);f=q.getAttribute(g);return""===f&&(g=q.getAttributeNode(g),!g||!g.specified)?h:null===f?h:f}}else for(n=j.length-1;0<=n;n--)if((q=j[n])&&q.nodeType===m.ELEMENT_NODE)"form"==s(q)&&(d=c),d&&d.set?d.set(q,f,g):q.setAttribute(g,""+f);return h},removeAttr:function(c,d){var d=d.toLowerCase(),d=b[d]||d,e=a.query(c),f,n,q;for(q=e.length-1;0<=q;q--)if(n=e[q],n.nodeType==m.ELEMENT_NODE&&(n.removeAttribute(d),i.test(d)&&(f=o[d]||d)in n))n[f]=!1},hasAttr:k&&!k.hasAttribute?
function(d,c){var c=c.toLowerCase(),b=a.query(d),e,f;for(e=0;e<b.length;e++)if(f=b[e],(f=f.getAttributeNode(c))&&f.specified)return!0;return!1}:function(d,c){var b=a.query(d),e,f=b.length;for(e=0;e<f;e++)if(b[e].hasAttribute(c))return!0;return!1},val:function(c,b){var f,l,j,q,u;if(b===h){if(j=a.get(c)){if((f=n[s(j)]||n[j.type])&&"get"in f&&(l=f.get(j,"value"))!==h)return l;l=j.value;return"string"===typeof l?l.replace(d,""):null==l?"":l}return h}l=a.query(c);for(q=l.length-1;0<=q;q--){j=l[q];if(1!==
j.nodeType)break;u=b;null==u?u="":"number"===typeof u?u+="":e.isArray(u)&&(u=e.map(u,function(a){return a==null?"":a+""}));f=n[s(j)]||n[j.type];if(!f||!("set"in f)||f.set(j,u,"value")===h)j.value=u}return h},text:function(d,c){var b,e,f,q;if(c===h)return b=a.get(d),a._getText(b);e=a.query(d);for(f=e.length-1;0<=f;f--)if(b=e[f],q=b.nodeType,q==m.ELEMENT_NODE)a.empty(b),b.appendChild(b.ownerDocument.createTextNode(c));else if(q==m.TEXT_NODE||q==m.CDATA_SECTION_NODE)b.nodeValue=c;return h},_getText:function(a){return a.textContent}});
return a},{requires:["./api"]});
KISSY.add("dom/base/class",function(e,a){function h(a){for(var a=e.trim(a||""),a=a.split(i),j=[],h,d=a.length,b=0;b<d;b++)(h=a[b])&&j.push(h);return j}function p(a){return function(e,h){var d,b,l,i=e.classList,o=m.call(arguments,2);d=0;for(b=h.length;d<b;d++)(l=h[d])&&i[a].apply(i,[l].concat(o))}}function k(e){return function(j,i){var d=h(i),b=m.call(arguments,2);a.query(j).each(function(l){l.nodeType==s.ELEMENT_NODE&&a[e].apply(a,[l,d].concat(b))})}}var m=[].slice,s=a.NodeType,i=/[\.\s]\s*\.?/;e.mix(a,
{_hasClass:function(a,e){var h,d,b,l=a.classList;if(l.length){h=0;for(d=e.length;h<d;h++)if((b=e[h])&&!l.contains(b))return!1;return!0}return!1},_addClass:p("add"),_removeClass:p("remove"),_toggleClass:p("toggle"),hasClass:function(e,j){var i=a.get(e);return i&&i.nodeType==s.ELEMENT_NODE&&a._hasClass(i,h(j))},replaceClass:function(e,h,i){a.removeClass(e,h);a.addClass(e,i)},addClass:k("_addClass"),removeClass:k("_removeClass"),toggleClass:k("_toggleClass")});return a},{requires:["./api"]});
KISSY.add("dom/base/create",function(e,a,h){function p(d){var c=e.require("event/dom");c&&c.detach(d);a.removeData(d)}function k(a,c){var e=c&&c!=f?c.createElement(d):b;e.innerHTML="m<div>"+a+"</div>";return e.lastChild}function m(a,c,d){var b=c.nodeType;if(b==j.DOCUMENT_FRAGMENT_NODE){c=c.childNodes;d=d.childNodes;for(b=0;c[b];)d[b]&&m(a,c[b],d[b]),b++}else if(b==j.ELEMENT_NODE){c=c.getElementsByTagName("*");d=d.getElementsByTagName("*");for(b=0;c[b];)d[b]&&a(c[b],d[b]),b++}}function s(c,d){var b=
e.require("event/dom"),g,r;if(d.nodeType!=j.ELEMENT_NODE||a.hasData(c)){g=a.data(c);for(r in g)a.data(d,r,g[r]);b&&b.clone(c,d)}}function i(a){var c=null,d,b;if(a&&(a.push||a.item)&&a[0]){c=a[0].ownerDocument;c=c.createDocumentFragment();a=e.makeArray(a);d=0;for(b=a.length;d<b;d++)c.appendChild(a[d])}return c}var f=e.Env.host.document,j=a.NodeType,t=e.UA.ie,d="div",b=f&&f.createElement(d),l=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/ig,w=/<([\w:]+)/,o=/^\s+/,z=/\s+$/,x=
t&&9>t,c=/<|&#?\w+;/,n=f&&"outerHTML"in f.documentElement,B=/^<(\w+)\s*\/?>(?:<\/\1>)?$/;e.mix(a,{create:function(b,g,n,A){var r=null;if(!b)return r;if(b.nodeType)return a.clone(b);if("string"!=typeof b)return r;A===h&&(A=!0);A&&(b=e.trim(b));var A=a._creators,y,D,n=n||f,E,F=d;if(c.test(b))if(E=B.exec(b))r=n.createElement(E[1]);else{b=b.replace(l,"<$1></$2>");if((E=w.exec(b))&&(y=E[1]))F=y.toLowerCase();y=(A[F]||k)(b,n);x&&(D=b.match(o))&&y.insertBefore(n.createTextNode(D[0]),y.firstChild);x&&/\S/.test(b)&&
(D=b.match(z))&&y.appendChild(n.createTextNode(D[0]));b=y.childNodes;1===b.length?r=b[0].parentNode.removeChild(b[0]):b.length&&(r=i(b))}else r=n.createTextNode(b);e.isPlainObject(g)&&(r.nodeType==j.ELEMENT_NODE?a.attr(r,g,!0):r.nodeType==j.DOCUMENT_FRAGMENT_NODE&&a.attr(r.childNodes,g,!0));return r},_fixCloneAttributes:function(c,d){"textarea"===a.nodeName(c)&&(d.defaultValue=c.defaultValue,d.value=c.value)},_creators:{div:k},_defaultCreator:k,html:function(c,d,b){var c=a.query(c),g=c[0],e=!1,y,
n;if(!g)return null;if(d===h)return g.nodeType==j.ELEMENT_NODE?g.innerHTML:null;d+="";if(!d.match(/<(?:script|style|link)/i)&&(!x||!d.match(o))&&!v[(d.match(w)||["",""])[1].toLowerCase()])try{for(y=c.length-1;0<=y;y--)n=c[y],n.nodeType==j.ELEMENT_NODE&&(p(n.getElementsByTagName("*")),n.innerHTML=d);e=!0}catch(f){}e||(d=a.create(d,0,g.ownerDocument,0),a.empty(c),a.append(d,c,b));return h},outerHtml:function(c,g,e){var l=a.query(c),r=l.length,c=l[0];if(!c)return null;if(g===h){if(n)return c.outerHTML;
g=(g=c.ownerDocument)&&g!=f?g.createElement(d):b;g.innerHTML="";g.appendChild(a.clone(c,!0));g.appendChild(a.clone(c,!0));return g.innerHTML}g+="";if(!g.match(/<(?:script|style|link)/i)&&n)for(e=r-1;0<=e;e--)c=l[e],c.nodeType==j.ELEMENT_NODE&&(p(c),p(c.getElementsByTagName("*")),c.outerHTML=g);else c=a.create(g,0,c.ownerDocument,0),a.insertBefore(c,l,e),a.remove(l);return h},remove:function(c,d){var b,g=a.query(c),r,y,n=e.require("event/dom"),l;for(l=g.length-1;0<=l;l--)b=g[l],!d&&b.nodeType==j.ELEMENT_NODE&&
(r=e.makeArray(b.getElementsByTagName("*")),r.push(b),a.removeData(r),n&&n.detach(r)),(y=b.parentNode)&&y.removeChild(b)},clone:function(c,d,b,g){"object"===typeof d&&(g=d.deepWithDataAndEvent,b=d.withDataAndEvent,d=d.deep);var c=a.get(c),e,n=a._fixCloneAttributes,l;if(!c)return null;l=c.nodeType;e=c.cloneNode(d);if(l==j.ELEMENT_NODE||l==j.DOCUMENT_FRAGMENT_NODE)n&&l==j.ELEMENT_NODE&&n(c,e),d&&n&&m(n,c,e);b&&(s(c,e),d&&g&&m(s,c,e));return e},empty:function(c){var c=a.query(c),d,b;for(b=c.length-1;0<=
b;b--)d=c[b],a.remove(d.childNodes)},_nodeListToFragment:i});a.outerHTML=a.outerHtml;var g=a._creators,A=a.create,v={option:"select",optgroup:"select",area:"map",thead:"table",td:"tr",th:"tr",tr:"tbody",tbody:"table",tfoot:"table",caption:"table",colgroup:"table",col:"colgroup",legend:"fieldset"},C;for(C in v)(function(a){g[C]=function(c,d){return A("<"+a+">"+c+"</"+a+">",null,d)}})(v[C]);return a},{requires:["./api"]});
KISSY.add("dom/base/data",function(e,a,h){var p=e.Env.host,k="_ks_data_"+e.now(),m={},s={},i={applet:1,object:1,embed:1},f={hasData:function(a,b){if(a)if(b!==h){if(b in a)return!0}else if(!e.isEmptyObject(a))return!0;return!1}},j={hasData:function(a,b){return a==p?j.hasData(s,b):f.hasData(a[k],b)},data:function(a,b,e){if(a==p)return j.data(s,b,e);var f=a[k];if(e!==h)f=a[k]=a[k]||{},f[b]=e;else return b!==h?f&&f[b]:f=a[k]=a[k]||{}},removeData:function(a,b){if(a==p)return j.removeData(s,b);var l=a[k];
if(b!==h)delete l[b],e.isEmptyObject(l)&&j.removeData(a);else try{delete a[k]}catch(f){a[k]=h}}},t={hasData:function(a,b){var e=a[k];return!e?!1:f.hasData(m[e],b)},data:function(a,b,l){if(i[a.nodeName.toLowerCase()])return h;var f=a[k];if(!f){if(b!==h&&l===h)return h;f=a[k]=e.guid()}a=m[f];if(l!==h)a=m[f]=m[f]||{},a[b]=l;else return b!==h?a&&a[b]:a=m[f]=m[f]||{}},removeData:function(a,b){var f=a[k],i;if(f)if(i=m[f],b!==h)delete i[b],e.isEmptyObject(i)&&t.removeData(a);else{delete m[f];try{delete a[k]}catch(j){a[k]=
h}a.removeAttribute&&a.removeAttribute(k)}}};e.mix(a,{__EXPANDO:k,hasData:function(d,b){for(var e=!1,f=a.query(d),h=0;h<f.length&&!(e=f[h],e=e.nodeType?t.hasData(e,b):j.hasData(e,b));h++);return e},data:function(d,b,f){var d=a.query(d),i=d[0];if(e.isPlainObject(b)){for(var o in b)a.data(d,o,b[o]);return h}if(f===h){if(i)return i.nodeType?t.data(i,b):j.data(i,b)}else for(o=d.length-1;0<=o;o--)i=d[o],i.nodeType?t.data(i,b,f):j.data(i,b,f);return h},removeData:function(d,b){var e=a.query(d),f,h;for(h=
e.length-1;0<=h;h--)f=e[h],f.nodeType?t.removeData(f,b):j.removeData(f,b)}});return a},{requires:["./api"]});
KISSY.add("dom/base/insertion",function(e,a){function h(a,b){var e=[],k,o,p;for(k=0;a[k];k++)if(o=a[k],p=i(o),o.nodeType==m.DOCUMENT_FRAGMENT_NODE)e.push.apply(e,h(f(o.childNodes),b));else if("script"===p&&(!o.type||t.test(o.type)))o.parentNode&&o.parentNode.removeChild(o),b&&b.push(o);else{if(o.nodeType==m.ELEMENT_NODE&&!s.test(p)){p=[];var x,c,n=o.getElementsByTagName("script");for(c=0;c<n.length;c++)x=n[c],(!x.type||t.test(x.type))&&p.push(x);j.apply(a,[k+1,0].concat(p))}e.push(o)}return e}function p(a){a.src?
e.getScript(a.src):(a=e.trim(a.text||a.textContent||a.innerHTML||""))&&e.globalEval(a)}function k(d,b,f,i){d=a.query(d);i&&(i=[]);d=h(d,i);a._fixInsertionChecked&&a._fixInsertionChecked(d);var b=a.query(b),j,k,x,c,n=b.length;if((d.length||i&&i.length)&&n){d=a._nodeListToFragment(d);1<n&&(c=a.clone(d,!0),b=e.makeArray(b));for(j=0;j<n;j++)k=b[j],d&&(x=0<j?a.clone(c,!0):d,f(x,k)),i&&i.length&&e.each(i,p)}}var m=a.NodeType,s=/^(?:button|input|object|select|textarea)$/i,i=a.nodeName,f=e.makeArray,j=[].splice,
t=/\/(java|ecma)script/i;e.mix(a,{_fixInsertionChecked:null,insertBefore:function(a,b,e){k(a,b,function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)},e)},insertAfter:function(a,b,e){k(a,b,function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)},e)},appendTo:function(a,b,e){k(a,b,function(a,b){b.appendChild(a)},e)},prependTo:function(a,b,e){k(a,b,function(a,b){b.insertBefore(a,b.firstChild)},e)},wrapAll:function(e,b){b=a.clone(a.get(b),!0);e=a.query(e);e[0].parentNode&&a.insertBefore(b,
e[0]);for(var f;(f=b.firstChild)&&1==f.nodeType;)b=f;a.appendTo(e,b)},wrap:function(d,b){d=a.query(d);b=a.get(b);e.each(d,function(e){a.wrapAll(e,b)})},wrapInner:function(d,b){d=a.query(d);b=a.get(b);e.each(d,function(e){var d=e.childNodes;d.length?a.wrapAll(d,b):e.appendChild(b)})},unwrap:function(d){d=a.query(d);e.each(d,function(b){b=b.parentNode;a.replaceWith(b,b.childNodes)})},replaceWith:function(e,b){var f=a.query(e),b=a.query(b);a.remove(b,!0);a.insertBefore(b,f);a.remove(f)}});e.each({prepend:"prependTo",
append:"appendTo",before:"insertBefore",after:"insertAfter"},function(e,b){a[b]=a[e]});return a},{requires:["./api"]});
KISSY.add("dom/base/offset",function(e,a,h){function p(a){var c,e=a.ownerDocument.body;if(!a.getBoundingClientRect)return{left:0,top:0};c=a.getBoundingClientRect();a=c[b];c=c[l];a-=j.clientLeft||e.clientLeft||0;c-=j.clientTop||e.clientTop||0;return{left:a,top:c}}function k(b,c){var e={left:0,top:0},d=t(b),g,f=b,c=c||d;do{if(d==c){var i=f;g=p(i);i=t(i);g.left+=a[o](i);g.top+=a[z](i)}else g=p(f);e.left+=g.left;e.top+=g.top}while(d&&d!=c&&(f=d.frameElement)&&(d=d.parent));return e}var m=e.Env.host,s=
e.UA,i=m.document,f=a.NodeType,j=i&&i.documentElement,t=a.getWindow,d=Math.max,b="left",l="top",w=e.isNumber,o="scrollLeft",z="scrollTop";e.mix(a,{offset:function(b,c,e){if(c===h){var b=a.get(b),d;b&&(d=k(b,e));return d}e=a.query(b);for(d=e.length-1;0<=d;d--){var b=e[d],g=c;"static"===a.css(b,"position")&&(b.style.position="relative");var f=k(b),i={},j=void 0,l=void 0;for(l in g)j=parseFloat(a.css(b,l))||0,i[l]=j+g[l]-f[l];a.css(b,i)}return h},scrollIntoView:function(d,c,i,j){var g,k,v,m;if(v=a.get(d)){c&&
(c=a.get(c));c||(c=v.ownerDocument);c.nodeType==f.DOCUMENT_NODE&&(c=t(c));e.isPlainObject(i)&&(j=i.allowHorizontalScroll,m=i.onlyScrollIfNeeded,i=i.alignWithTop);j=j===h?!0:j;k=e.isWindow(c);var d=a.offset(v),q=a.outerHeight(v);g=a.outerWidth(v);var o,p,s,r;k?(k=c,o=a.height(k),p=a.width(k),r={left:a.scrollLeft(k),top:a.scrollTop(k)},k=d[b]-r[b],v=d[l]-r[l],g=d[b]+g-(r[b]+p),d=d[l]+q-(r[l]+o)):(o=a.offset(c),p=c.clientHeight,s=c.clientWidth,r={left:a.scrollLeft(c),top:a.scrollTop(c)},k=d[b]-(o[b]+
(parseFloat(a.css(c,"borderLeftWidth"))||0)),v=d[l]-(o[l]+(parseFloat(a.css(c,"borderTopWidth"))||0)),g=d[b]+g-(o[b]+s+(parseFloat(a.css(c,"borderRightWidth"))||0)),d=d[l]+q-(o[l]+p+(parseFloat(a.css(c,"borderBottomWidth"))||0)));if(m){if(0>v||0<d)!0===i?a.scrollTop(c,r.top+v):!1===i?a.scrollTop(c,r.top+d):0>v?a.scrollTop(c,r.top+v):a.scrollTop(c,r.top+d)}else(i=i===h?!0:!!i)?a.scrollTop(c,r.top+v):a.scrollTop(c,r.top+d);if(j)if(m){if(0>k||0<g)!0===i?a.scrollLeft(c,r.left+k):!1===i?a.scrollLeft(c,
r.left+g):0>k?a.scrollLeft(c,r.left+k):a.scrollLeft(c,r.left+g)}else(i=i===h?!0:!!i)?a.scrollLeft(c,r.left+k):a.scrollLeft(c,r.left+g)}},docWidth:0,docHeight:0,viewportHeight:0,viewportWidth:0,scrollTop:0,scrollLeft:0});e.each(["Left","Top"],function(b,c){var e="scroll"+b;a[e]=function(d,g){if(w(d))return arguments.callee(m,d);var d=a.get(d),i,j,l,k;d&&d.nodeType==f.ELEMENT_NODE?g!==h?d[e]=parseFloat(g):i=d[e]:(k=t(d),g!==h?(g=parseFloat(g),j="Left"==b?g:a.scrollLeft(k),l="Top"==b?g:a.scrollTop(k),
k.scrollTo(j,l)):(i=k["page"+(c?"Y":"X")+"Offset"],w(i)||(j=k.document,i=j.documentElement[e],w(i)||(i=j.body[e]))));return i}});e.each(["Width","Height"],function(b){a["doc"+b]=function(c){c=a.get(c);c=a.getDocument(c);return d(c.documentElement["scroll"+b],c.body["scroll"+b],a["viewport"+b](c))};a["viewport"+b]=function(c){var c=a.get(c),e=t(c),c=e["inner"+b];if(s.mobile&&c)return c;var c="client"+b,e=e.document,d=e.body,g=e.documentElement[c];return"CSS1Compat"===e.compatMode&&g||d&&d[c]||g}});
return a},{requires:["./api"]});
KISSY.add("dom/base/style",function(e,a,h){function p(a,c){return c.toUpperCase()}function k(a){return a.replace(c,"ms-").replace(u,p)}function m(a,c,b){var e={},d;for(d in c)e[d]=a[l][d],a[l][d]=c[d];b.call(a);for(d in c)a[l][d]=e[d]}function s(a,c,b){var e,d,f;if(3===a.nodeType||8===a.nodeType||!(e=a[l]))return h;c=k(c);f=v[c];c=C[c]||c;if(b!==h){null===b||b===B?b=B:!isNaN(Number(b))&&!x[c]&&(b+=g);f&&f.set&&(b=f.set(a,b));if(b!==h){try{e[c]=b}catch(i){}b===B&&e.removeAttribute&&e.removeAttribute(c)}e.cssText||
a.removeAttribute("style");return h}if(!f||!("get"in f&&(d=f.get(a,!1))!==h))d=e[c];return d===h?"":d}function i(a){var c,b=arguments;0!==a.offsetWidth?c=f.apply(h,b):m(a,G,function(){c=f.apply(h,b)});return c}function f(c,b,d){if(e.isWindow(c))return b==o?a.viewportWidth(c):a.viewportHeight(c);if(9==c.nodeType)return b==o?a.docWidth(c):a.docHeight(c);var g=b===o?["Left","Right"]:["Top","Bottom"],f=b===o?c.offsetWidth:c.offsetHeight;if(0<f)return"border"!==d&&e.each(g,function(b){d||(f-=parseFloat(a.css(c,
"padding"+b))||0);f="margin"===d?f+(parseFloat(a.css(c,d+b))||0):f-(parseFloat(a.css(c,"border"+b+"Width"))||0)}),f;f=a._getComputedStyle(c,b);if(null==f||0>Number(f))f=c.style[b]||0;f=parseFloat(f)||0;d&&e.each(g,function(b){f+=parseFloat(a.css(c,"padding"+b))||0;"padding"!==d&&(f+=parseFloat(a.css(c,"border"+b+"Width"))||0);"margin"===d&&(f+=parseFloat(a.css(c,d+b))||0)});return f}var j=e.Env.host,t=e.UA,d=a.nodeName,b=j.document,l="style",w=/^margin/,o="width",z="display"+e.now(),x={fillOpacity:1,
fontWeight:1,lineHeight:1,opacity:1,orphans:1,widows:1,zIndex:1,zoom:1},c=/^-ms-/,n=/([A-Z]|^ms)/g,B="",g="px",A=/\d(?!px)[a-z%]+$/i,v={},C={"float":"cssFloat"},q={},u=/-([a-z])/ig;e.mix(a,{_camelCase:k,_CUSTOM_STYLES:v,_cssProps:C,_getComputedStyle:function(c,b){var e="",d,f,g,i,h;f=c.ownerDocument;b=b.replace(n,"-$1").toLowerCase();if(d=f.defaultView.getComputedStyle(c,null))e=d.getPropertyValue(b)||d[b];""===e&&!a.contains(f,c)&&(b=C[b]||b,e=c[l][b]);a._RE_NUM_NO_PX.test(e)&&w.test(b)&&(h=c.style,
f=h.width,g=h.minWidth,i=h.maxWidth,h.minWidth=h.maxWidth=h.width=e,e=d.width,h.width=f,h.minWidth=g,h.maxWidth=i);return e},style:function(c,b,d){var c=a.query(c),f,g=c[0];if(e.isPlainObject(b)){for(f in b)for(g=c.length-1;0<=g;g--)s(c[g],f,b[f]);return h}if(d===h)return f="",g&&(f=s(g,b,d)),f;for(g=c.length-1;0<=g;g--)s(c[g],b,d);return h},css:function(c,b,d){var c=a.query(c),f=c[0],g;if(e.isPlainObject(b)){for(g in b)for(f=c.length-1;0<=f;f--)s(c[f],g,b[g]);return h}b=k(b);g=v[b];if(d===h){d="";
if(f&&(!g||!("get"in g&&(d=g.get(f,!0))!==h)))d=a._getComputedStyle(f,b);return"undefined"==typeof d?"":d}for(f=c.length-1;0<=f;f--)s(c[f],b,d);return h},show:function(c){var c=a.query(c),d,e,f;for(f=c.length-1;0<=f;f--)if(e=c[f],e[l].display=a.data(e,z)||B,"none"===a.css(e,"display")){d=e.tagName.toLowerCase();var g=void 0,i=q[d],h=void 0;q[d]||(g=b.body||b.documentElement,h=b.createElement(d),a.prepend(h,g),i=a.css(h,"display"),g.removeChild(h),q[d]=i);d=i;a.data(e,z,d);e[l].display=d}},hide:function(c){var c=
a.query(c),b,d;for(d=c.length-1;0<=d;d--){b=c[d];var e=b[l],f=e.display;"none"!==f&&(f&&a.data(b,z,f),e.display="none")}},toggle:function(c){var c=a.query(c),b,d;for(d=c.length-1;0<=d;d--)b=c[d],"none"===a.css(b,"display")?a.show(b):a.hide(b)},addStyleSheet:function(c,b,d){"string"==typeof c&&(d=b,b=c,c=j);var c=a.getDocument(c),e;if(d&&(d=d.replace("#",B)))e=a.get("#"+d,c);e||(e=a.create("<style>",{id:d},c),a.get("head",c).appendChild(e),e.styleSheet?e.styleSheet.cssText=b:e.appendChild(c.createTextNode(b)))},
unselectable:function(c){var c=a.query(c),b,f,g=0,i,h;for(f=c.length-1;0<=f;f--)if(b=c[f],h=b[l],h.UserSelect="none",t.gecko)h.MozUserSelect="none";else if(t.webkit)h.WebkitUserSelect="none";else if(t.ie||t.opera){h=b.getElementsByTagName("*");b.setAttribute("unselectable","on");for(i=["iframe","textarea","input","select"];b=h[g++];)e.inArray(d(b),i)||b.setAttribute("unselectable","on")}},innerWidth:0,innerHeight:0,outerWidth:0,outerHeight:0,width:0,height:0});e.each([o,"height"],function(c){a["inner"+
e.ucfirst(c)]=function(b){return(b=a.get(b))&&i(b,c,"padding")};a["outer"+e.ucfirst(c)]=function(b,d){var e=a.get(b);return e&&i(e,c,d?"margin":"border")};a[c]=function(b,d){var e=a.css(b,c,d);e&&(e=parseFloat(e));return e};v[c]={get:function(a,b){var d;b&&(d=i(a,c)+"px");return d}}});var G={position:"absolute",visibility:"hidden",display:"block"};e.each(["left","top"],function(c){v[c]={get:function(d,e){var f,g,i;if(e){i=a.css(d,"position");if("static"===i)return"auto";f=a._getComputedStyle(d,c);
if((g="auto"===f)&&"relative"===i)return"0px";if(g||A.test(f)){i={top:0,left:0};if("fixed"==a.css(d,"position"))g=d.getBoundingClientRect();else{for(f=d.offsetParent||(d.ownerDocument||b).body;f&&!H.test(f.nodeName)&&"static"===a.css(f,"position");)f=f.offsetParent;g=a.offset(d);i=a.offset(f);i.top+=parseFloat(a.css(f,"borderTopWidth"))||0;i.left+=parseFloat(a.css(f,"borderLeftWidth"))||0}g.top-=parseFloat(a.css(d,"marginTop"))||0;g.left-=parseFloat(a.css(d,"marginLeft"))||0;f={top:g.top-i.top,left:g.left-
i.left}[c]+"px"}}return f}}});var H=/^(?:body|html)$/i;return a},{requires:["./api"]});
KISSY.add("dom/base/selector",function(e,a,h){function p(a){var b=this.length,d;for(d=0;d<b&&!1!==a(this[d],d);d++);}function k(c,i){var j,g,m="string"==typeof c,t=i!==h?k(i):(g=1)&&[f],s=t.length;j=/^\.([\w-]+)$/;var q=/^#([\w-]*)$/,u=/^[\w-]+$/,w=/^[\w-]+#[\w-]+$/,z=/^[\w-]+\.[\w-]+$/;if(c)if(m){c=x(c);a:{for(var m=c,r=[/\+/,/\=/,/\~/,/\[/,/\]/,/:/,/>/,/\|/,/\$/,/\^/,/\*/,/\(/,/\)/,/[\w-]+\.[\w-]+/i,/[\w-]+\#[\w-]+/i],y=0;y<r.length;y++)if(m.match(r[y])){m=!1;break a}m=!0}if(g&&"body"==c)j=[f.body];
else if(!m&&"querySelectorAll"in document&&1===s)console.log("simple querySelector"),j=t[0].querySelectorAll(c);else if(g&&q.test(c))j=(t=f.getElementById(c.substr(1)))?[t]:[];else if(g&&j.test(c)&&"getElementsByClassName"in document)j=f.getElementsByClassName(c.substr(1)),console.log("getElementsByClassName");else if(g&&u.test(c)&&"getElementsByTagName"in document)j=f.getElementsByTagName(c);else if(g&&w.test(c))j=(t=f.getElementById(c.replace(/^.+#/,"")))?[t]:[];else if(g&&z.test(c))j=f.querySelectorAll(c),
console.log("tag.cls");else if("getElementsByTagName"in document&&"getElementsByClassName"in document&&m)j=f.querySelectorAll(c);else{j=[];for(g=0;g<s;g++)"querySelectorAll"in document?(console.log("chain's querySelector"),j=j.concat(e.makeArray(t[g].querySelectorAll(c)))):o.apply(j,a._selectInternal(c,t[g]));1<j.length&&1<s&&a.unique(j);console.log("normal")}}else{if(j=c.nodeType||c.setTimeout?[c]:c.getDOMNodes?c.getDOMNodes():d(c)?c:l(c)?b(c):[c],!g){q=j;w=q.length;j=[];for(g=0;g<w;g++)for(u=0;u<
s;u++)if(a._contains(t[u],q[g])){j.push(q[g]);break}}}else j=[];j.each=p;return j}function m(a,b){var d=a&&(a.className||s(a,"class"));return d&&-1<(w+d+w).indexOf(w+b+w)}function s(a,b){var d=a&&a.getAttributeNode(b);return d&&d.specified?d.nodeValue:h}function i(a,b){return"*"==b||a.nodeName.toLowerCase()===b.toLowerCase()}var f=e.Env.host.document,j=f.documentElement,t=j.matches||j.webkitMatchesSelector||j.mozMatchesSelector||j.oMatchesSelector||j.msMatchesSelector,d=e.isArray,b=e.makeArray,l=
a.isDomNodeList,w=" ",o=Array.prototype.push,z=/^(?:#([\w-]+))?\s*([\w-]+|\*)?\.?([\w-]+)?$/,x=e.trim;e.mix(a,{_compareNodeOrder:function(a,b){return!a.compareDocumentPosition||!b.compareDocumentPosition?a.compareDocumentPosition?-1:1:a.compareDocumentPosition(b)&4?-1:1},_getSimpleAttr:s,_isTag:i,_hasSingleClass:m,_matchesInternal:function(a,b){for(var d=[],e=0,f,i=b.length;e<i;e++)f=b[e],t.call(f,a)&&d.push(f);return d},_selectInternal:function(a,d){return b(d.querySelectorAll(a))},query:k,get:function(a,
b){return k(a,b)[0]||null},unique:function(){function b(c,e){return c==e?(d=!0,0):a._compareNodeOrder(c,e)}var d,e=!0;[0,0].sort(function(){e=!1;return 0});return function(a){d=e;a.sort(b);if(d)for(var f=1,i=a.length;f<i;)a[f]===a[f-1]?(a.splice(f,1),--i):f++;return a}}(),filter:function(b,d,f){var b=k(b,f),g,h,j,l,f=[];if("string"==typeof d&&(d=x(d))&&(j=z.exec(d)))g=j[1],h=j[2],l=j[3],g?g&&!h&&!l&&(d=function(a){return s(a,"id")==g}):d=function(a){var b=!0,c=!0;h&&(b=i(a,h));l&&(c=m(a,l));return c&&
b};return f=e.isFunction(d)?e.filter(b,d):a._matchesInternal(d,b)},test:function(b,d,e){b=k(b,e);return b.length&&a.filter(b,d,e).length===b.length}});return a},{requires:["./api"]});
KISSY.add("dom/base/traversal",function(e,a,h){function p(i,f,j,m,d,b,l){if(!(i=a.get(i)))return null;if(0===f)return i;b||(i=i[j]);if(!i)return null;d=d&&a.get(d)||null;f===h&&(f=1);var b=[],p=e.isArray(f),o,z;e.isNumber(f)&&(o=0,z=f,f=function(){return++o===z});for(;i&&i!=d;){if((i.nodeType==s.ELEMENT_NODE||i.nodeType==s.TEXT_NODE&&l)&&k(i,f)&&(!m||m(i)))if(b.push(i),!p)break;i=i[j]}return p?b:b[0]||null}function k(i,f){if(!f)return!0;if(e.isArray(f)){var h,k=f.length;if(!k)return!0;for(h=0;h<k;h++)if(a.test(i,
f[h]))return!0}else if(a.test(i,f))return!0;return!1}function m(i,f,h,k){var d=[],b,l;if((b=i=a.get(i))&&h)b=i.parentNode;if(b){h=e.makeArray(b.childNodes);for(b=0;b<h.length;b++)l=h[b],(k||l.nodeType==s.ELEMENT_NODE)&&l!=i&&d.push(l);f&&(d=a.filter(d,f))}return d}var s=a.NodeType;e.mix(a,{_contains:function(a,e){return!!(a.compareDocumentPosition(e)&16)},closest:function(a,e,h,k){return p(a,e,"parentNode",function(a){return a.nodeType!=s.DOCUMENT_FRAGMENT_NODE},h,!0,k)},parent:function(a,e,j){return p(a,
e,"parentNode",function(a){return a.nodeType!=s.DOCUMENT_FRAGMENT_NODE},j,h)},first:function(e,f,j){e=a.get(e);return p(e&&e.firstChild,f,"nextSibling",h,h,!0,j)},last:function(e,f,j){e=a.get(e);return p(e&&e.lastChild,f,"previousSibling",h,h,!0,j)},next:function(a,e,j){return p(a,e,"nextSibling",h,h,h,j)},prev:function(a,e,j){return p(a,e,"previousSibling",h,h,h,j)},siblings:function(a,e,h){return m(a,e,!0,h)},children:function(a,e){return m(a,e,h)},contents:function(a,e){return m(a,e,h,1)},contains:function(e,
f){e=a.get(e);f=a.get(f);return e&&f?a._contains(e,f):!1},index:function(h,f){var j=a.query(h),k,d=0;k=j[0];if(!f){j=k&&k.parentNode;if(!j)return-1;for(;k=k.previousSibling;)k.nodeType==s.ELEMENT_NODE&&d++;return d}d=a.query(f);return"string"===typeof f?e.indexOf(k,d):e.indexOf(d[0],j)},equals:function(e,f){e=a.query(e);f=a.query(f);if(e.length!=f.length)return!1;for(var h=e.length;0<=h;h--)if(e[h]!=f[h])return!1;return!0}});return a},{requires:["./api"]});
KISSY.add("dom/base",function(e,a){e.mix(e,{DOM:a,get:a.get,query:a.query});return a},{requires:"./base/api,./base/attr,./base/class,./base/create,./base/data,./base/insertion,./base/offset,./base/style,./base/selector,./base/traversal".split(",")});
/*
Copyright 2013, KISSY UI Library v1.40dev
MIT Licensed
build time: Jul 3 19:20
*/
KISSY.add("event",function(a,c,b){a.EventTarget=b.Target;return a.Event=a.merge(c,b)},{requires:["event/dom","event/custom"]});
/*
Copyright 2013, KISSY UI Library v1.40dev
MIT Licensed
build time: Jul 3 13:57
*/
KISSY.add("node/base",function(b,h,i,j){function f(c,m,g){if(!(this instanceof f))return new f(c,m,g);if(c)if("string"==typeof c){if(c=h.create(c,m,g),c.nodeType===l.DOCUMENT_FRAGMENT_NODE)return d.apply(this,a(c.childNodes)),this}else{if(b.isArray(c)||e(c))return d.apply(this,a(c)),this}else return this;this[0]=c;this.length=1;return this}var g=Array.prototype,k=g.slice,l=h.NodeType,d=g.push,a=b.makeArray,e=h.isDomNodeList;f.prototype={constructor:f,isNodeList:!0,length:0,item:function(c){return b.isNumber(c)?
c>=this.length?null:new f(this[c]):new f(c)},add:function(c,a,e){b.isNumber(a)&&(e=a,a=j);c=f.all(c,a).getDOMNodes();a=new f(this);e===j?d.apply(a,c):(e=[e,0],e.push.apply(e,c),g.splice.apply(a,e));return a},slice:function(c,a){return new f(k.apply(this,arguments))},getDOMNodes:function(){return k.call(this)},each:function(c,a){var e=this;b.each(e,function(d,b){d=new f(d);return c.call(a||d,d,b,e)});return e},getDOMNode:function(){return this[0]},end:function(){return this.__parent||this},filter:function(c){return new f(h.filter(this,
c))},all:function(c){c=0<this.length?f.all(c,this):new f;c.__parent=this;return c},one:function(c){c=this.all(c);if(c=c.length?c.slice(0,1):null)c.__parent=this;return c}};b.mix(f,{all:function(c,a){return"string"==typeof c&&(c=b.trim(c))&&3<=c.length&&b.startsWith(c,"<")&&b.endsWith(c,">")?(a&&(a.getDOMNode&&(a=a[0]),a=a.ownerDocument||a),new f(c,j,a)):new f(h.query(c,a))},one:function(a,d){var e=f.all(a,d);return e.length?e.slice(0,1):null}});f.NodeType=l;f.KeyCode=i.KeyCode;f.Gesture=i.Gesture;
f.REPLACE_HISTORY=i.REPLACE_HISTORY;return f},{requires:["dom","event/dom"]});
KISSY.add("node/attach",function(b,h,i,j,f){function g(d,a,e){e.unshift(a);d=h[d].apply(h,e);return d===f?a:d}var k=j.prototype,l=b.makeArray;j.KeyCode=i.KeyCode;b.each("nodeName,isCustomDomain,getEmptyIframeSrc,equals,contains,index,scrollTop,scrollLeft,height,width,innerHeight,innerWidth,outerHeight,outerWidth,addStyleSheet,appendTo,prependTo,insertBefore,before,after,insertAfter,test,hasClass,addClass,removeClass,replaceClass,toggleClass,removeAttr,hasAttr,hasProp,scrollIntoView,remove,empty,removeData,hasData,unselectable,wrap,wrapAll,replaceWith,wrapInner,unwrap".split(","),function(d){k[d]=
function(){var a=l(arguments);return g(d,this,a)}});b.each("getWindow,getDocument,filter,first,last,parent,closest,next,prev,clone,siblings,contents,children".split(","),function(d){k[d]=function(){var a=l(arguments);a.unshift(this);a=h[d].apply(h,a);return a===f?this:a===null?null:new j(a)}});b.each({attr:1,text:0,css:1,style:1,val:0,prop:1,offset:0,html:0,outerHTML:0,outerHtml:0,data:1},function(d,a){k[a]=function(){var e;e=l(arguments);e[d]===f&&!b.isObject(e[0])?(e.unshift(this),e=h[a].apply(h,
e)):e=g(a,this,e);return e}});b.each("on,detach,fire,fireHandler,delegate,undelegate".split(","),function(d){k[d]=function(){var a=l(arguments);a.unshift(this);i[d].apply(i,a);return this}})},{requires:["dom","event/dom","./base"]});
KISSY.add("node/override",function(b,h,i){var j=i.prototype;b.each(["append","prepend","before","after"],function(b){j[b]=function(g){"string"==typeof g&&(g=h.create(g));if(g)h[b](g,this);return this}});b.each(["wrap","wrapAll","replaceWith","wrapInner"],function(b){var g=j[b];j[b]=function(b){"string"==typeof b&&(b=i.all(b,this[0].ownerDocument));return g.call(this,b)}})},{requires:["dom","./base"]});
KISSY.add("node/anim",function(b,h,i,j,f){function g(b,d,a){for(var e=[],c={},a=a||0;a<d;a++)e.push.apply(e,k[a]);for(a=0;a<e.length;a++)c[e[a]]=b;return c}var k=[["height","margin-top","margin-bottom","padding-top","padding-bottom"],["width","margin-left","margin-right","padding-left","padding-right"],["opacity"]];b.augment(j,{animate:function(g){var d=b.makeArray(arguments);b.each(this,function(a){var e=b.clone(d),c=e[0];c.to?(c.node=a,i(c).run()):i.apply(f,[a].concat(e)).run()});return this},stop:function(f,
d,a){b.each(this,function(b){i.stop(b,f,d,a)});return this},pause:function(f,d){b.each(this,function(a){i.pause(a,d)});return this},resume:function(f,d){b.each(this,function(a){i.resume(a,d)});return this},isRunning:function(){for(var b=0;b<this.length;b++)if(i.isRunning(this[b]))return!0;return!1},isPaused:function(){for(var b=0;b<this.length;b++)if(i.isPaused(this[b]))return!0;return!1}});b.each({show:g("show",3),hide:g("hide",3),toggle:g("toggle",3),fadeIn:g("show",3,2),fadeOut:g("hide",3,2),fadeToggle:g("toggle",
3,2),slideDown:g("show",1),slideUp:g("hide",1),slideToggle:g("toggle",1)},function(f,d){j.prototype[d]=function(a,e,c){if(h[d]&&!a)h[d](this);else b.each(this,function(b){i(b,f,a,c,e).run()});return this}})},{requires:["dom","anim","./base"]});KISSY.add("node",function(b,h){b.mix(b,{Node:h,NodeList:h,one:h.one,all:h.all});return h},{requires:["node/base","node/attach","node/override","node/anim"]});
