" ~/.vimrc by Jayli (拔赤)
"
set nocompatible        "使用vim默认配置

"reset默认后退键
set backspace=indent,eol,start

"读写.viminfo文件，但不存储太多行
set viminfo='20,\"50
set formatoptions=mtcql

au BufNewFile,BufRead * set foldlevel=99

highlight Folded ctermbg=darkgray ctermfg=lightmagenta

if has ( "autocmd" )
	" 当编辑一个文件时，总是滚屏到光标所在的最终位置
	autocmd BufReadPost *
	\ if line("'\"") > 0 && line ("'\"") <= line("$") |
	\   exe "normal g'\"" |
	\ endif
endif  " has ("autocmd") 


"编辑器样式的 hack,只针对term终端作 hack，在gui终端沿用默认样式
hi Comment      term=bold ctermfg=darkcyan
hi Constant     term=underline ctermfg=Red
hi Special      term=bold ctermfg=Magenta
hi Identifier   term=underline ctermfg=cyan
hi Statement    term=bold ctermfg=Brown
hi PreProc      term=bold ctermfg=DarkYellow
hi Type         term=bold ctermfg=DarkGreen
hi Ignore       ctermfg=white
hi Error        term=reverse ctermbg=Red ctermfg=White
hi Todo         term=standout ctermbg=Yellow ctermfg=Red
hi Search       term=standout ctermbg=Yellow ctermfg=Black
hi ErrorMsg     term=reverse ctermbg=Red ctermfg=White
hi StatusLine   ctermfg=darkblue  ctermbg=gray
hi StatusLineNC ctermfg=brown   ctermbg=darkblue

"鼠标隐藏
set mouse=v

"高亮搜索结果
set incsearch
set hlsearch

"显示行号
set nu

"状态栏
set laststatus=2
set statusline=%<[%n]\ %F\ %h%m%r%=%k[%{(&fenc==\"\")?&enc:&fenc}%{(&bomb?\",BOM\":\"\")}][%{&ff}][ASCII=\%03.3b]\ %-10.(%l,%c%V%)\ %P

"欢迎文字,这里可以换成你想要的任意文字
autocmd VimEnter * echo "Welcome back jayli :)"
autocmd VimLeave * echo "Byebye jayli.."

"一个tab占4个空格
set ts=4
set sw=4

"自动缩进动作，粘贴自动缩进
set smartindent
"自动缩进长度
set cino=:0g0               

"长句在单词间折行
set wrap

"搜索忽略大小写
set ignorecase

"编辑源备份
set backupcopy=yes

"编辑模式自动缩进
set autoindent 

"记录历史
set history=150 

"标尺
set ruler

"显示不完整的命令
set showcmd

" Linux 系统中的行模式重置
set modelines=0

"文件编码可自动识别utf系列和gb系列,新建文件采用utf8编码
set fileencodings=ucs-bom,utf-8,GB18030,gbk

"gui字体，随意模式
set guifontset=*-r-*

"语法高亮
syntax enable
syntax on

"F功能键定义,使用频度较低
map <F2> <ESC>zA<CR>            
map <F3> <ESC>*
map <F4> <ESC>#                
map <F11> :bp<CR>              
map <F12> :bn<CR>               
map <F7> <ESC>:wa<CR>:make<CR>
map <F8> <ESC>"0p

"tab操作多文件
map <C-t> :tabnew 
nmap wm :tabnew .<CR>
map <Tab> :tabnext<CR> 
map <S-Tab> :tabprevious<CR>

"使用 Ctrl+C 或者 Y 复制到系统剪贴板
vnoremap <C-C> "+y
vnoremap Y "+y

"快速左右移动光标
map <C-l> <ESC>10l
map <C-h> <ESC>10h

"tab尺寸
set shiftwidth=4
set tabstop=4   "tab

"tab自动补全
function! CleverTab()
if strpart( getline('.'), 0, col('.')-1 ) =~ '^\s*$'
		return "\<Tab>"
		else
		return "\<C-N>"
endfunction
inoremap <Tab> <C-R>=CleverTab()<CR>

"退出模式,退出时保留残余窗口
set t_ti=
set t_te= 

"折叠配置
set fdm=manual

"选择编辑器主题
"colorscheme evening
"colorscheme blue
"colorscheme darkblue
"colorscheme default
"colorscheme delek
"colorscheme desert
colorscheme elflord
"colorscheme evening
"colorscheme koehler
"colorscheme morning
"colorscheme murphy
"colorscheme pablo
"colorscheme peachpuff
"colorscheme ron
"colorscheme shine
"colorscheme torte
"colorscheme zellner

"状态栏样式hack，针对evening,包括gui模式下的状态栏样式
hi StatusLine	cterm=bold ctermbg=blue ctermfg=white guifg=darkblue guibg=white
hi StatusLineNC	cterm=bold ctermbg=blue ctermfg=black guifg=darkblue guibg=white
hi TabLine cterm=bold ctermbg=lightgray ctermfg=black guibg=blue guifg=white
hi TabLineSel cterm=bold ctermbg=darkblue ctermfg=white guibg=blue guifg=white
hi CursorLine cterm=bold ctermbg=darkgray guibg=gold guifg=blue

"显示tab line
"set showtabline=2

"最大tab个数
set tabpagemax=20


"高亮光标所在的行
":hi cursorline ctermbg=Red

